### ISSUE TITLE
How to change device parameters on Huawei HG8245A

### ISSUE THREAD

**Issue by miguelet17** [zaidka/genieacs#103]
Hello and congratulations for this awesome software.

I'm quite newbie with genieacs and I'm having an issue I don't know how to resolve.

I have changed some parameters of some openwrt routers successfull whitin the genieacs web.
For instance, I have changed SSID, SSID_pass, ppp, etc.

However, I'm trying to change some parameters of my Huawei HG8245A but it only shows me a few "Device parameters" and, moreover, they are not editable. See image.

![image](https://cloud.githubusercontent.com/assets/9483801/8703214/7289a4fe-2b1c-11e5-81d1-0abf99212645.png)

Is there any way to change parameters that the router is not showing by default?

Thank you so much in advance, hope you could help me.

**Comment by akcoder** [comment]
This is for issue tracking, not support. Please kindly take this over to
the mailing list <http://lists.genieacs.com/mailman/listinfo>.

**Comment by miguelet17** [comment]
Sorry, I didn't realize. :(

I've taken this over to the mailing list.
Thank you very much!!
