### ISSUE TITLE
GenieACS Behind NAT

### ISSUE THREAD

**Issue by slyruss** [zaidka/genieacs#104]
Hello Zaid,

Have you got recommendations about firewalling and NAT ?
My config.json : 
{
  "MONGODB_CONNECTION_URL" : "mongodb://127.0.0.1/genieacs",
  "REDIS_PORT" : "6379",
  "REDIS_HOST" : "127.0.0.1",
  "CWMP_INTERFACE" : "0.0.0.0",
  "CWMP_PORT" : 7547,
  "CWMP_SSL" : false,
  "NBI_INTERFACE" : "0.0.0.0",
  "NBI_PORT" : 7557,
  "FS_INTERFACE" : "0.0.0.0",
  "FS_PORT" : 7567,
  "FS_IP" : "WAN_IP",
}

I don't have any problem when FS_IP is a private address IP. But, when I change the FS_IP to a WAN address IP, I have some workers died and some tasks like refreshObject don't work.

My GenieACS is behind firewall solution and there is some NAT rules (7547, 7557, 7567).
My genieacs-cwmp-err.log : 
2015-07-20T14:34:06.011Z - Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

Thanks you in advance.

Regards,

**Comment by zaidka** [comment]
FS_IP shouldn't cause any crash. Maybe you changed FS_INTERFACE instead? The only use of FS_IP is when generating the URL for download RPC so no value could cause a crash.

**Comment by slyruss** [comment]
Ok thanks you.

**Comment by zaidka** [comment]
Do you have this sorted out? What was the problem?

**Comment by slyruss** [comment]
I cleaned my firewall / NAT conf and I set the FS_IP with WAN IP.
I have to set QoS better then 128ko for the CPE to complete successfully download task.
