### ISSUE TITLE
genieacs installation process fails

### ISSUE THREAD

**Issue by fbesbes** [zaidka/genieacs#105]
I am trying to install genieacs on LinuxMint 17 machine (64bits).
All dependencies packages are installed(Node.js, Redis and MongoDB).
I tired to install with "npm install -g genieacs" and from source but the same problem is reproduced.

After running "npm install" I got the following error:
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/genieacs/node_modules/libxmljs
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by zaidka** [comment]
Try installing the package "nodejs-legacy".

**Comment by fbesbes** [comment]
It's OK problem resolved.
Thank you
