### ISSUE TITLE
Automated firmware update

### ISSUE THREAD

**Issue by xujianningkp** [zaidka/genieacs#106]
Hello All,

I was able to push firmware to CPE manually, but is there any way I can preset firmware updates for group of CPEs? Any suggestion will be appreciated. Thank you.

**Comment by zaidka** [comment]
There's a preset option for that, but it'll only push the file when the device checks for update (not all devices have that feature). Pushing firmware actively (as opposed to the current passive approach) will come in a future release but for now you need to do that using the API and an external script.

**Comment by xujianningkp** [comment]
Thank you so much for your reply. Is it possible to change admin login username and password?

**Comment by akcoder** [comment]
Look in the config directory. There is an auth file

-dan

**Comment by Saidurga21** [comment]
I am unable to push the file and getting the "task name not recognized" error
How can I resolve this issue

**Comment by akcoder** [comment]
Please take this to the mailing list <http://lists.genieacs.com/>. The
issue tracker is not for help requests.
