### ISSUE TITLE
Some APIs Return Nothing

### ISSUE THREAD

**Issue by garyyu** [zaidka/genieacs#108]
I read the API document on the Wiki, and these APIs are wonderful!
I try to use some examples to test these APIs, but for some APIs I always get nothing, please refer to the following output. Is this a normal behaviour? I suppose not.

1. Find a device by its MAC address. This one always return nothing.
$ curl -i 'http://localhost:7557/devices/?query=%7B%22Device.LAN.MACAddress%22%3A%2200:0B:82:69:08:B6%22%7D'
HTTP/1.1 200 OK
Content-Type: application/json
total: 0
Date: Tue, 01 Sep 2015 05:55:43 GMT
Connection: keep-alive
Transfer-Encoding: chunked
[
]

2. setParameterValues. This one works well!
$ curl -i 'http://localhost:7557/devices/000b826908b6/tasks?timeout=3000?connection_request' -X POST --data '{ "name": "setParameterValues", "parameterValues": [["Device.ManagementServer.PeriodicInformInterval",180]] }'
HTTP/1.1 202 Accepted
Content-Type: application/json
Date: Tue, 01 Sep 2015 05:57:36 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{"name":"setParameterValues","parameterValues":[],"device":"000b826908b6","timestamp":"2015-09-01T05:57:36.158Z","_id":"55e53e5095862b57119d172d"}

3. Get specific parameters for a given device. This one always return nothing.

$ curl -i 'http://localhost:7557/devices/?query=%7B%22_id%22%3A%22000b826908b6%22%7D'
HTTP/1.1 200 OK
Content-Type: application/json
total: 0
Date: Tue, 01 Sep 2015 06:01:19 GMT
Connection: keep-alive
Transfer-Encoding: chunked
[
]

$ curl -i 'http://localhost:7557/devices/?query=%7B%22_id%22%3A%22000b826908b6%22%7D&projection=Device.ManagementServer.PeriodicInformInterval'
HTTP/1.1 200 OK
Content-Type: application/json
total: 0
Date: Tue, 01 Sep 2015 06:01:36 GMT
Connection: keep-alive
Transfer-Encoding: chunked

[
]

$ cat genieacs-nbi.log
1 Sep 17:14:10 - Worker 1486 listening to 0.0.0.0:7557
1 Sep 17:14:10 - Worker 1484 listening to 0.0.0.0:7557

Please see the enclosed snapshot for the device info page.
![screen shot 2015-09-01 at 3 19 20 pm](https://cloud.githubusercontent.com/assets/1852227/9598348/18846e0a-50bd-11e5-8d39-24eb3392957d.png)

**Comment by zaidka** [comment]
Many of these queries aren't using the correct device ID. Use the one you see in the screenshot.

May I suggest using the mailing list for questions like this (unless of course you're confident it's a bug). This is mostly for tracking of bugs and feature requests.

**Comment by garyyu** [comment]
Thanks Zaidka! 
Indeed, my mistake, here what I used was "Serial number" instead of "Device ID".
When I use correct "Device ID", everything is OK except this one:

$ curl -i 'http://localhost:7557/devices/?query=%7B%22Device.LAN.MACAddress%22%3A%2200:0B:82:69:08:B6%22%7D'
It still return nothing.

And thanks for your suggestion, I will paste this question into mail list.
