### ISSUE TITLE
nbi

### ISSUE THREAD

**Issue by metalsoft10** [zaidka/genieacs#118]
i try to change nbi port and always  Worker 31465 listening to 0.0.0.0:7557
how to change to another port i change it in genieacs/config/config.json
{
  "MONGODB_CONNECTION_URL" : "mongodb://127.0.0.1/genieacs",
  "REDIS_PORT" : "6379",
  "REDIS_HOST" : "127.0.0.1",
  "CWMP_INTERFACE" : "0.0.0.0",
  "CWMP_PORT" : 7547,
  "CWMP_SSL" : false,
  "NBI_INTERFACE" : "0.0.0.0",
  "NBI_PORT" : 7333 ,
  "FS_INTERFACE" : "0.0.0.0",
  "FS_PORT" : 7567,
  "FS_IP" : "127.0.0.1",
  "LOG_INFORMS" : true,
  "DEBUG" : false,
  "XML_PARSE_RECOVER" : true,
  "XML_PARSE_IGNORE_ENC" : true,
  "GET_PARAMETER_NAMES_DEPTH_THRESHOLD" : 3

}

**Comment by akcoder** [comment]
You need to restart the NBI after changing the port it listens on.

**Comment by metalsoft10** [comment]
i do restart ctrl+c 
then start it again port not change

**Comment by metalsoft10** [comment]
fixed thank you
