### ISSUE TITLE
Custom Commands Not Found

### ISSUE THREAD

**Issue by rplatel** [zaidka/genieacs#123]
GenieACS is looking for custom commands .js files in a hardcoded relative path rather than (say)  the GENIEACS_CONFIG_DIR env variable

    exports.execute = (deviceId, command, callback) ->
      args = command.split(/\s+/)
      f = args.shift()
      c = args.shift()

      file = require "../config/custom_commands/#{f}"
      file[c](deviceId, args.join(' '), callback)

    exports.getFileCommands = (filename) ->
      commands = []
      f = require("../config/custom_commands/#{filename}")
      for k,v of f
        commands.push(k)
      return commands

Furthermore, I think GenieACS is sending custom command errors to the CPE:

    200.001.001.XXX.54088-010.000.149.047.07547: POST / HTTP/1.1
    
    200.001.001.XXX.54088-010.000.149.047.07547: Host: acs.ac.dev.tucows.net:7547
    User-Agent: BCM_TR69_CPE_04_00
    Connection: keep-alive
    Cookie: session=a9ab8d7e55d54f35
    Content-Length: 0

    010.000.149.047.07547-200.001.001.XXX.54088: HTTP/1.1 500 Internal Server Error
    Connection: close
    Date: Mon, 07 Dec 2015 15:35:01 GMT
    Transfer-Encoding: chunked
    
    3b
    Error: Cannot find module '../config/custom_commands/bloop'
    0

**Comment by zaidka** [comment]
You seem to have configured "bloop" custom command in config/custom_commands.json but didn't include the corresponding js file under config/custom_commands/ directory.

**Comment by rplatel** [comment]
Hi, thanks for the quick reply.

I have GENIEACS_CONFIG_DIR set: 
    GENIEACS_CONFIG_DIR=/ac/genieacs/config
Settings are being read from there, and I have boop.js there:
    /ac/genieacs/config$ ls custom_commands
    bloop.js  greenpacket_frequencies.js  seowon_frequencies.js

I believe GenieACS is looking for boop.js in /usr/lib/node_modules/genieacs/config/custom_commands (which I happen to have mounted read only)

**Comment by rplatel** [comment]
I have GENIEACS_CONFIG_DIR set

    GENIEACS_CONFIG_DIR=/ac/genieacs/config

I've confirmed that settings are being read from the files in that dir, and I have bloop.js there:

    rplatel@acs01:/ac/genieacs/config ls -l custom_commands
    total 20
    -rw-r--r-- 1 root root  296 Dec  4 21:07 bloop.js
    -rw-r--r-- 1 root root 7215 Nov 11 19:14 greenpacket_frequencies.js
    -rw-r--r-- 1 root root 7818 Nov 11 19:14 seowon_frequencies.js

I think GenieACS is looking for bloop.js in /usr/lib/node_modules/genieacs/config/custom_commands (which I happen to have mounted read-only)

**Comment by zaidka** [comment]
Oh, I see what you mean now. Sorry for missing that in your original comment. This does indeed look like a bug. Will patch soon. Thanks.
