### ISSUE TITLE
TypeError: Cannot read property 'Device' of null 

### ISSUE THREAD

**Issue by engee974** [zaidka/genieacs#125]
i'm testing GenieACS API and have an issue to get/set device's parameters.

First, impossible to obtain device ID from MAC address : 
```
# curl -i 'http://localhost:7557/devices/?query=%7B%22InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MACAddress%22%3A%22F4:E3:FB:71:FC:ED%22%7D'
HTTP/1.1 200 OK
Content-Type: application/json
total: 0
Date: Sat, 19 Dec 2015 05:15:32 GMT
Connection: keep-alive
Transfer-Encoding: chunked

[

]
```

Then, NBI crash when i try to reboot the device :
```
# curl -i 'http://localhost:7557/devices/00E0FC-HG658%20V2-C2T7S15409000107/tasks?timeout=3000&connection_request' -X POST --data '{ "name": "reboot" }'
HTTP/1.1 500 Internal Server Error
Connection: close
Date: Sat, 19 Dec 2015 05:20:08 GMT
Transfer-Encoding: chunked

TypeError: Cannot read property 'Device' of null
```

**Comment by zaidka** [comment]
Looks like URL encoding issue. Make sure your query in the first request and the device ID in the second request are URL-encoded.

**Comment by engee974** [comment]
Hi Zaid,
First query : For you, what is malformed in the query ? For me it's URL-encoded
Second query (missing "/" after 'devices') : the device has following parameters
  OUI : 00E0FC
  Product Class : HG658 V2  (URL-encoded : HG658%20V2)
  Serial Number : C2T7S15409000107
Device ID URL-Encoded is exactly : 00E0FC-HG658%20V2-C2T7S15409000107

Could you help me please ?

Thanks,
Nicolas

**Comment by zaidka** [comment]
The %20 is part of the device ID so the encoded ID needs to be 00E0FC-HG658%2520V2-C2T7S15409000107.

**Comment by engee974** [comment]
Thanks Zaid.
This a little bit confusing. It works when "double url-encoded".
Why is the device ID URL-encoded ?
It would be simpler not to URL-encode it when stored in database.

**Comment by zaidka** [comment]
We have to encode special characters when generating the ID to guarantee a unique and predictable ID.
