### ISSUE TITLE
Device.Config.ConfigFile

### ISSUE THREAD

**Issue by tim-isako** [zaidka/genieacs#126]
Hi. I configured genieacs. I use the phone setup Yealink T19. Phone settings are sent to the server. 
In Device parameters -> Device.Config.ConfigFile, I get an error message "The configuration file is larger than the parameter sizeplease use the Upload and Download RPCs witha FileType of "1 Vendor Configuration File"". How to fix it?

**Comment by zaidka** [comment]
Not a bug. Please use the mailing list.
