### ISSUE TITLE
Presets Help

### ISSUE THREAD

**Issue by koizo** [zaidka/genieacs#127]
Hello

First of all, thanks for GenieACS :)

I have the following preset:
{
  "_id": "Teste 2",
  "weight": 1,
  "precondition": "{\"_tags\":\"test\"}",
  "configurations": [
    {
      "type": "value",
      "name": "Device.ManagementServer.PeriodicInformEnable",
      "value": "true"
    },
    {
      "type": "value",
      "name": "Device.ManagementServer.PeriodicInformInterval",
      "value": "10"
    }
  ]
}

And i have the Device:
{..... ,
  "_tags": [
    "test"
  ]
}

I see on the Genieacs-gui:
Device.ManagementServer.PeriodicInformEnable false 
Device.ManagementServer.PeriodicInformInterval 0

Every time the device connects, the preset is not applied.
I can't see nothing on the logs also.
Even when it runs a refresh task.

Am i doing something wrong?

Best regards

**Comment by zaidka** [comment]
Looks good. Can't guess why it isn't working. Try removing the precondition or check on a different device.

**Comment by koizo** [comment]
Solved
