### ISSUE TITLE
new INFO in index page

### ISSUE THREAD

**Issue by jaluapen** [zaidka/genieacs#140]
Hi All,

I've just started using genieacs, not bad. I've been running it for a few days and sometimes it will break. How can I trace that what breaks it? Also when the terminal running the BG stuff disconnects so does the web service and whole genieacs. Is there a way to do it so it does not happen? I run it with & for BG but still the problem persists. 

I'm also trying to add an info in the index page : InternetGatewayDevice.WEB_GUI.Status.LTE_Status.LTE_System.IMSI

How can I do this?

Thanks,

Jalu

**Comment by jaluapen** [comment]
This is running on the latest Fedora 23, have to disable Firewall for it to work

**Comment by okraits** [comment]
You can use tmux or screen to be able to detach it from a terminal and have it running in the background.

To debug genieacs, you can look at stdout and additionally enable debugging in config.json. The log dump can then be found in the debug directory.

**Comment by jaluapen** [comment]
Thanks okraits. I also need help on how to add an info (IMSI) on website index. The other issue is to increase the number of devices per page.

Thanks to any replies,

Jalu

**Comment by okraits** [comment]
To increase the number of devices listed per page, modify config.page_size in application.rb.

**Comment by jaluapen** [comment]
That was easy cool. Thanks Just that other part about new info. I tried using the tutorial but when I compiled npm, none of the devices updated. Will try again, might be doing something wrong.

Thanks okraits 
Jalu

**Comment by jaluapen** [comment]
heres hte debug log when I try npm compile

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'compile' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 error Error: ENOENT, open '/opt/genieacs/config/package.json'
5 error If you need help, you may report this *entire* log,
5 error including the npm and node versions, at:
5 error     <http://github.com/npm/npm/issues>
6 error System Linux 4.2.3-300.fc23.x86_64
7 error command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
8 error cwd /opt/genieacs/config
9 error node -v v0.10.28
10 error npm -v 1.4.9
11 error path /opt/genieacs/config/package.json
12 error code ENOENT
13 error errno 34
14 verbose exit [ 34, true ]

**Comment by jaluapen** [comment]
seems there;s quite alot of similar errors - I don't have package.json in that directory /config/package.json... I found over 50 files :-) so which is the correct one? Is this a npm config standard?

**Comment by jaluapen** [comment]
I just need the correct package file and to create sym link in that directory and hopefully should fix.

**Comment by jaluapen** [comment]
figured it out,,, need to be in genieacs file but still that info is not showing in the device infos... I am still doing something wrong... has anyone done IMSI parameters? 

Thanks
Jalu

**Comment by zaidka** [comment]
I'm closing this one. Please discuss in the mailing list if you need any help.
