### ISSUE TITLE
From customCommands to Presets

### ISSUE THREAD

**Issue by ivoabr** [zaidka/genieacs#144]
Hi,

I would like to contact an external server to get parameters that later should be set to a CPE. 

I'm running a customCommand to set those values and I can see them on MongoDB, but I cannot find a way to set them on a Preset. How can I do this?

Additionally, is there a way to execute a customCommand on every Inform Event?

Thank you,
Regards,
Ivo

**Comment by zaidka** [comment]
Not an Issue. Please review the [contributing guidelines](https://github.com/zaidka/genieacs/blob/master/CONTRIBUTING.md).
