### ISSUE TITLE
500 error at cpe and typeError:cannot call method value of 'null' at ACS

### ISSUE THREAD

**Issue by Babubsp** [zaidka/genieacs#146]
Hi,

i am getting response from acs as POST http://10.226.129.15:7547/ returned a response status of 500 Internal Server Error.

and at ACS side getting TypeError : Cannot call method value of 'null' 

can anyone help me to solve this issue.

**Comment by zaidka** [comment]
Looks like a device related issue. Please review the [contributing guidelines](https://github.com/zaidka/genieacs/blob/master/CONTRIBUTING.md).
