### ISSUE TITLE
Connection Request Reset

### ISSUE THREAD

**Issue by xujianningkp** [zaidka/genieacs#148]
Hello All,

Is there a such thing or a way to increase connection request timeout? seems like the connection will be reset when ACS is trying to authenticate. I have to click "refresh" twice in order to get this to work. Any suggestions will be greatly appreciated. Thank you.

![image](https://cloud.githubusercontent.com/assets/6878935/14468458/52bd8be0-00a5-11e6-9e10-447013a58cab.png)

**Comment by zaidka** [comment]
The timeout is hardcoded at 2 seconds. You can change it in connectionRequest function in lib/api-functions.coffee. Let me know if that solves the issue. I guess we can make that configurable.

**Comment by crawc** [comment]
Thanks, is this the line you are referring to?

https://github.com/zaidka/genieacs/blob/ba33fc0fe09b9d1b0cd12dc876d0fafda1c9fa33/lib/api-functions.coffee#L87

**Comment by xujianningkp** [comment]
I increased socket.setTimeout(2000) to 10 seconds (10000), but it still fails the first ConnectionRequest when i click refresh, and it shows "Device is offline" on the GUI. Although I do see the modem and server exchange XML information. Any idea what else I should try?
![image](https://cloud.githubusercontent.com/assets/6878935/15303961/3eba4f7a-1b80-11e6-9a1e-39849a404139.png)

**Comment by xujianningkp** [comment]
Finally got it to work. Seems like I have to modify socket.setTimeout(2000) in the lib/api-functions.js, instead of api-functions.coffee. Thank you so much for your help!!

**Comment by zaidka** [comment]
You should modify the dot coffee files and then run "npm run compile" to generate the js files. However, this has now been implemented as a configuration option. Add CONNECTION_REQUEST_TIMEOUT in config.json (defaults to 2000).
