### ISSUE TITLE
Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by DrumSergio** [zaidka/genieacs#149]
When trying to execute `genieacs-cwmp` or its brothers in the CLI of Ubuntu (tried it in v14.04, v15.10, v16.10...) I get the following output:

    root@GenieACS:~# genieacs-nbi
    { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
    js-bson: Failed to load c++ bson extension, using pure JS version
    { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
    js-bson: Failed to load c++ bson extension, using pure JS version
    25 Apr 18:17:24 - Worker 12220 listening to 0.0.0.0:7557
    25 Apr 18:17:24 - Worker 12225 listening to 0.0.0.0:7557

This error can be found in all these places:
https://github.com/Automattic/mongoose/issues/2285
https://github.com/Automattic/mongoose/issues/3436
http://stackoverflow.com/questions/21656420/failed-to-load-c-bson-extension

I don't know for sure, but maybe it's a code problem. Some time ago I read that incorporating the module calling it alone, instead of giving the full path, would work. I don't know where did I found it, sorry for being so inexact, but I can't find it. I just wanted to post this issue in order to have it registered.

Normally, I've noticed that it occurs when version 4.X or 5.X of Node.JS is installed.

PS. No, doing `npm install mongoose` doesn't work

**Comment by zaidka** [comment]
Just guessing here, it could be that you're using a different Nodejs version when running genieacs-nbi than the version you used when installing dependencies. Try clearing npm_modules directory and reinstall the dependencies.

**Comment by sohaildeen** [comment]
Hi Zaidka
I'm had the same issue as Drum Sergio.
Clearing the npm_modules directory and reinstalling dependencies didn't work for me.

I had to run the below commands to get it working as suggested in the wiki:
https://github.com/zaidka/genieacs/wiki/Installation-in-Ubuntu-14.04-&-15.10

```
sudo apt-get install build-essential
sudo npm cache clean -f 
sudo npm install n -g 
sudo n 0.10.25 -g
sudo npm install npm -g 
sudo npm install genieacs -g
sudo cp /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/obj.target/xmljs.node /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
```

We would very much like to use the latest version of nodejs, will you be able to look into it please

**Comment by zaidka** [comment]
Current stable requires Node.js v0.10. I believe it works on v0.12 too. Next release will use the latest LTS version of Node.js and may even support the latest non-LTS at time of release.
