### ISSUE TITLE
Fault 9002, "GPV handler error (code -1)" from CPE

### ISSUE THREAD

**Issue by DrumSergio** [zaidka/genieacs#150]
Hello!

I am facing with this error with an Android IP phone.

### RESPONSE Fri Apr 29 2016 11:22:19 GMT-0400 (EDT)
{"Server":"GenieACS/1.0.6","SOAPServer":"GenieACS/1.0.6","Content-Type":"text/xml; charset=\"utf-8\""}
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-0"><soap-env:Header><cwmp:ID soap-env:mustUnderstand="1">5723132a4aa3f41104b8e6b7</cwmp:ID></soap-env:Header><soap-env:Body><cwmp:GetParameterValues><ParameterNames soap-enc:arrayType="xsd:string[32]"><string>Device.Services.VoiceService.1.VoiceProfile.1.STUNServer</string><string>Device.Services.VoiceService.1.VoiceProfile.1.LineNumberOfEntries</string><string>Device.Services.VoiceService.1.VoiceProfile.1.RTP.X_GRANDSTREAM_SymmetricRTP</string><string>Device.Services.VoiceService.1.VoiceProfile.1.RTP.X_GRANDSTREAM_VoiceFramesPerTX</string><string>Device.Services.VoiceService.1.VoiceProfile.1.RTP.LocalPortMin</string><string>Device.Services.VoiceService.1.VoiceProfile.1.RTP.LocalPortMax</string><string>Device.Services.VoiceService.1.VoiceProfile.1.RTP.DSCPMark</string><string>Device.Services.VoiceService.1.VoiceProfile.1.RTP.TelephoneEventPayloadType</string><string>Device.Services.VoiceService.1.VoiceProfile.1.RTP.SRTP.X_GRANDSTREAM_AvailableSRTPMode</string><string>Device.Services.VoiceService.1.VoiceProfile.1.RTP.SRTP.X_GRANDSTREAM_SRTPMode</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.X_GRANDSTREAM_EnableCallFeatures</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.X_GRANDSTREAM_RingTimeOut</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.DirectoryNumber</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.Enable</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.Status</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallState</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.SessionNumberOfEntries</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.X_GRANDSTREAM_AutoAnswer</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.X_GRANDSTREAM_RegisterationEnable</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.X_GRANDSTREAM_TransferOnConfHangup</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.MWIEnable</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.CallForwardOnNoAnswerRingCount</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.AnonymousCalEnable</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.AnonymousCallBlockEnable</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.CallForwardUnconditionalNumber</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.CallForwardOnBusyNumber</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.CallingFeatures.CallForwardOnNoAnswerNumber</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.Codec.X_GRANDSTREAM_StartVideoAuto</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.Codec.X_GRANDSTREAM_EnableRFC5168support</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.Codec.X_GRANDSTREAM_SilenceSuppression</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.Codec.X_GRANDSTREAM_iLBCPayloadType</string><string>Device.Services.VoiceService.1.VoiceProfile.1.Line.1.Codec.X_GRANDSTREAM_iLBCFramSize</string></ParameterNames></cwmp:GetParameterValues></soap-env:Body></soap-env:Envelope>

### REQUEST Fri Apr 29 2016 11:22:19 GMT-0400 (EDT)
{"host":"acs2.streamnow.ch:7547","user-agent":"GRANDSTREAM CPE-1.0.1.49 (3.2.3)","cookie":"Version=1;session=0dc97a67094e45f3","content-type":"text/xml; charset=utf-8","soapaction":"","content-length":"614"}
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cwmp="urn:dslforum-org:cwmp-1-0"><soap:Header><cwmp:ID soap:mustUnderstand="1">5723132a4aa3f41104b8e6b7</cwmp:ID></soap:Header><soap:Body><soap:Fault><faultcode>Server</faultcode><faultstring>CWMP Fault</faultstring><detail><cwmp:Fault><FaultCode>9002</FaultCode><FaultString>GPV handler error (code -1)</FaultString></cwmp:Fault></detail></soap:Fault></soap:Body></soap:Envelope>

I just wanted to know if the problem is of GenieACS, which doesn't sends the right parameters, or from the Android IP phone, which just collapses. If you want, I can send the whole conversation.

Thank you!

**Comment by zaidka** [comment]
These interoperability issues are almost always device related problems. I'll close this, but feel free to reopen it if you have a reason to believe it's actually a bug.
