### ISSUE TITLE
"Device is offline" when trying to send anything to CPEs

### ISSUE THREAD

**Issue by DrumSergio** [zaidka/genieacs#152]
I currently am working with GrandStream devices.

I've noticed that when you try, for example, to change some parameter from within GenieACS GUI, it says something like "Device is offline. Changes will be queued until next inform"

All the CPEs are set to 60sec inform interval. So I have to wait until next inform to get the task sent.

Do you know why is this happening? Which info would you need to capture this behaviour?

Thank you.

**Comment by crawc** [comment]
What happens when you refresh the device after committing the task?

Chris

**Comment by zaidka** [comment]
Looks like a device interoperability issue. Best to post this to the mailing list.
