### ISSUE TITLE
enable/disable UPnP from API?

### ISSUE THREAD

**Issue by vsharma10286** [zaidka/genieacs#153]
Hello everyone,

Please tell me how do i enable/disable UPnP option from API?

**Comment by okraits** [comment]
Please have a look at the API documentation at https://github.com/zaidka/genieacs/wiki/API-Reference.
Add a setParameterValues task with the parameter you want to change like this:

`curl -i 'http://localhost:7557/devices/202BC1-BM632w-0000000/tasks?connection_request' \
-X POST \
--data '{"name":"setParameterValues", "parameterValues":[["InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID", "GenieACS", "xsd:string"]]}'
`

Also, please use the mailing list for general usage questions not related to issues in the software.

**Comment by vsharma10286** [comment]
Hi Okraits,
I don't know what "setParameterValues" to use for setting "UPnP" option.
Although i have already use the option you descrive above for setting SSID or Password for WiFi.
But for UPnP i am having Problem, what parameter to use?

**Comment by okraits** [comment]
I'm sorry, we don't use UPnP. Is UPnP already exposed to easy/freecwmp through a script?

**Comment by vsharma10286** [comment]
Actually i dont know about easy/freecwmp script. i have used only API's.

**Comment by zaidka** [comment]
Not sure if this is solved. But if not, please take it to the Users mailing list.
