### ISSUE TITLE
IP is always 0.0.0.0

### ISSUE THREAD

**Issue by bpbp-boop** [zaidka/genieacs#154]
Hi,

While the ACS is mostly working well, one issue we've encountered is that IP is always either blank or "0.0.0.0" (depending on the CPE vendor) 

We're using the default parameters.json configuration and the regex for ExternalIPAddress looks fine for the devices - what else can we try? Does the order matter? Should GenieACS skip blank or 0.0.0.0 values?

**Comment by zaidka** [comment]
Not an Issue. Please review the [contributing guidelines](https://github.com/zaidka/genieacs/blob/master/CONTRIBUTING.md).

**Comment by bpbp-boop** [comment]
Apologies. I've emailed the list and my message is awaiting moderation.
