### ISSUE TITLE
API doesn't work properly involving specific CPEs

### ISSUE THREAD

**Issue by DrumSergio** [zaidka/genieacs#159]
Sorry Dan, I didn't send the text with the issue. Here's what I wrote:

Via curl or via navigator, when I perform some tasks in v1.0.7 of GenieACS, I dont't get the specific CPE I am expecting. GenieACS API returns all the CPEs. These are some examples:

When I go to `http://my.genieacs.server:7557/devices/?query{%22device%22=%22XXXXXX-ZZZZZZ-YYYYYYYYYYYY%22}&projection=summary.wlanSsid` in my navigator (Or via curl I get the same result) I get a list with the summary.wlanSsid of **ALL** CPEs. No matter how I change the slashes, the CPE, the type, the translation (quoting mark instead of %22)...

Also when doing `curl -i 'http://my.server:7557/devices/?query=%7B%22device%22%3A%22XXXXXX-ZZZZZZ-YYYYYYYYYYYY%22%7D'` (or visiting via web) doesn't get me back results. I can print out the logs:

```
HTTP/1.1 200 OK
Content-Type: application/json
total: 0
Date: Tue, 21 Jun 2016 11:15:06 GMT
Connection: keep-alive
Transfer-Encoding: chunked

[

]
```

Why could this be happening?

**Comment by akcoder** [comment]
Can you provide more information? Test cases, packet captures, logs, etc?

**Comment by harryfoster** [comment]
Did you mean to do this instead?

`curl -i 'http://my.server:7557/devices/?query=%7B%22_id%22%3A%22XXXXXX-ZZZZZZ-YYYYYYYYYYYY%22%7D'`

Presumably you are querying for the '_id' in the devices collection, not the 'device' in the devices collection.
