### ISSUE TITLE
GenieACS CWMP not start

### ISSUE THREAD

**Issue by skylinqnl** [zaidka/genieacs#160]
Hello,

I have an issue with genieacs-cwmp. It dont start and I have follow this link: https://github.com/zaidka/genieacs/issues/56. The other proces runs fine: genieacs-nbi, genieacs-fs, rails server, mongod and redis-server.

What can I do? There's also an issue with myself, I'm not very familiar with Linux.

`
^Cskylinq@ACS:~sudo genieacs-cwmp

/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/default/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/compiled/0.10.25/linux/x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:456:26)
24 Jun 23:08:59 - Worker 4346 died (8)

/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/default/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/compiled/0.10.25/linux/x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:456:26)
24 Jun 23:08:59 - Worker 4347 died (8)

/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/default/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/compiled/0.10.25/linux/x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:456:26)

/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Debug/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/out/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/Release/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/build/default/xmljs.node
 â /usr/local/lib/node_modules/genieacs/node_modules/libxmljs/compiled/0.10.25/linux/x64/xmljs.node
    at bindings (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:456:26)
24 Jun 23:09:00 - Worker 4348 died (8)
24 Jun 23:09:00 - Worker 4350 died (8)
`

**Comment by DrumSergio** [comment]
That's because the `xmljs.node` file isn't in the good place. If you follow my guide [here](https://github.com/zaidka/genieacs/wiki/Installation-in-Ubuntu-14.04-Server) that wouldn't have happened to you.

**Comment by skylinqnl** [comment]
Hi Sergio,

Thanks for your manual!! I’ve run it step by step with option A. I have the following errors. Can you help me out? I’ve try a lot of tutorials but none of them works well. ☹

skylinq@ACS:~$ cd /
skylinq@ACS:/$ git clone https://github.com/zaidka/genieacs-gui
fatal: could not create work tree dir 'genieacs-gui'.: Permission denied
skylinq@ACS:/$ sudo git clone https://github.com/zaidka/genieacs-gui
[sudo] password for skylinq:
Cloning into 'genieacs-gui'...
remote: Counting objects: 1035, done.
remote: Total 1035 (delta 0), reused 0 (delta 0), pack-reused 1035
Receiving objects: 100% (1035/1035), 252.56 KiB | 0 bytes/s, done.
Resolving deltas: 100% (639/639), done.
Checking connectivity... done.
skylinq@ACS:/$ cd genieacs-gui
skylinq@ACS:/genieacs-gui$ sudo cp config/graphs-sample.json.erb config/graphs.json.erb
skylinq@ACS:/genieacs-gui$ sudo cp config/index_parameters-sample.yml config/index_parameters.yml
skylinq@ACS:/genieacs-gui$ sudo cp config/summary_parameters-sample.yml config/summary_parameters.yml
skylinq@ACS:/genieacs-gui$ sudo cp config/parameters_edit-sample.yml config/parameters_edit.yml
skylinq@ACS:/genieacs-gui$ sudo cp config/parameter_renderers-sample.yml config/parameter_renderers.yml
skylinq@ACS:/genieacs-gui$
skylinq@ACS:/genieacs-gui$ sudo cp config/roles-sample.yml config/roles.yml
skylinq@ACS:/genieacs-gui$ sudo cp config/users-sample.yml config/users.yml
skylinq@ACS:/genieacs-gui$ bundle update json
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Installing rake 10.3.2
Installing i18n 0.6.11
Using json 1.8.3 (was 1.8.1)
Installing minitest 5.4.0
Installing thread_safe 0.3.4
Using builder 3.2.2
Using erubis 2.7.0
Installing rack 1.5.2
Installing mime-types 1.25.1
Installing polyglot 0.3.5
Installing arel 5.0.1.20140414130214
Using bundler 1.12.5
Installing coffee-script-source 1.7.1
Installing execjs 2.2.1
Using thor 0.19.1
Installing hike 1.2.3
Installing multi_json 1.10.1
Installing libv8 3.16.14.3
Installing tilt 1.4.1
Installing ref 1.0.5
Installing sass 3.2.19
Installing sqlite3 1.3.9 with native extensions
Installing rdoc 4.1.1
Using tzinfo 1.2.2
Installing rack-test 0.6.2
Installing treetop 1.4.15
Installing coffee-script 2.3.0
Installing uglifier 2.5.3
Installing sprockets 2.11.0
Installing therubyracer 0.12.1 with native extensions
Installing sdoc 0.4.1
Installing activesupport 4.1.4
Installing mail 2.5.4
Installing actionview 4.1.4
Installing activemodel 4.1.4
Installing jbuilder 2.1.3
Installing actionpack 4.1.4
Installing activerecord 4.1.4
Installing actionmailer 4.1.4
Installing railties 4.1.4
Installing sprockets-rails 2.1.3
Installing coffee-rails 4.0.1
Installing jquery-rails 3.1.1
Installing rails 4.1.4
Installing sass-rails 4.0.3
Installing turbolinks 2.2.2
There was an error while trying to write to `/genieacs-gui/Gemfile.lock`. It is likely that you need to grant
write permissions for that path.
skylinq@ACS:/genieacs-gui$ sudo bundle update json
sudo: bundle: command not found
skylinq@ACS:/genieacs-gui$ bundle update json
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using rake 10.3.2
Using i18n 0.6.11
Using json 1.8.3 (was 1.8.1)
Using minitest 5.4.0
Using thread_safe 0.3.4
Using builder 3.2.2
Using erubis 2.7.0
Using rack 1.5.2
Using mime-types 1.25.1
Using polyglot 0.3.5
Using arel 5.0.1.20140414130214
Using bundler 1.12.5
Using coffee-script-source 1.7.1
Using execjs 2.2.1
Using thor 0.19.1
Using hike 1.2.3
Using multi_json 1.10.1
Using libv8 3.16.14.3
Using tilt 1.4.1
Using ref 1.0.5
Using sass 3.2.19
Using sqlite3 1.3.9
Using rdoc 4.1.1
Using tzinfo 1.2.2
Using rack-test 0.6.2
Using treetop 1.4.15
Using coffee-script 2.3.0
Using uglifier 2.5.3
Using sprockets 2.11.0
Using therubyracer 0.12.1
Using sdoc 0.4.1
Using activesupport 4.1.4
Using mail 2.5.4
Using actionview 4.1.4
Using activemodel 4.1.4
Using jbuilder 2.1.3
Using actionpack 4.1.4
Using activerecord 4.1.4
Using actionmailer 4.1.4
Using railties 4.1.4
Using sprockets-rails 2.1.3
Using coffee-rails 4.0.1
Using jquery-rails 3.1.1
Using rails 4.1.4
Using sass-rails 4.0.3
Using turbolinks 2.2.2
There was an error while trying to write to `/genieacs-gui/Gemfile.lock`. It is likely that you need to grant
write permissions for that path.
skylinq@ACS:/genieacs-gui$ bundle exec rake db:migrate RAILS_ENV=development
Could not find json-1.8.1 in any of the sources
Run `bundle install` to install missing gems.
skylinq@ACS:/genieacs-gui$ bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Using rake 10.3.2
Using i18n 0.6.11
Installing json 1.8.1 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
/home/skylinq/.rbenv/versions/2.3.1/bin/ruby -r ./siteconf20160628-18199-1sbo242.rb extconf.rb
creating Makefile

current directory: /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function âfbuffer_to_sâ:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [enabled by default]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-1.8.1 for inspection.
Results logged to /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/json-1.8.1/gem_make.out
Using minitest 5.4.0
Using thread_safe 0.3.4
Using builder 3.2.2
Using erubis 2.7.0
Using rack 1.5.2
Using mime-types 1.25.1
Using polyglot 0.3.5
Using arel 5.0.1.20140414130214
Using coffee-script-source 1.7.1
Using execjs 2.2.1
Using thor 0.19.1
Using hike 1.2.3
Using multi_json 1.10.1
Using libv8 3.16.14.3
Using bundler 1.12.5
Using tilt 1.4.1
Using ref 1.0.5
Using sass 3.2.19
Using sqlite3 1.3.9
An error occurred while installing json (1.8.1), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.1'` succeeds before bundling.
skylinq@ACS:/genieacs-gui$ gem install json -v '1.8.1'
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    current directory: /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
/home/skylinq/.rbenv/versions/2.3.1/bin/ruby -r ./siteconf20160628-18612-ekglhc.rb extconf.rb
creating Makefile

current directory: /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function âfbuffer_to_sâ:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [enabled by default]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json-1.8.1 for inspection.
Results logged to /home/skylinq/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/json-1.8.1/gem_make.out
skylinq@ACS:/genieacs-gui$

Met vriendelijke groet,

Harm van den Dikkenberg

[EMAIL skylinq_logo bg white_RGB_080116]
Kaaistraat 14
4695 CJ Sint Maartensdijk
T. 0166-760005
E. harm@skylinq.nl<mailto:harm@skylinq.nl>
I. www.skylinq.nl<http://www.skylinq.nl/>

KVK. 65472594
Op al onze producten en diensten zijn onze algemene voorwaarden<http://skylinq.nl/wp-content/uploads/2016/03/Algemene-voorwaarden-Skylinq.pdf> van toepassing.

Deze e-mail en de hierbij verzonden informatie is uitsluitend bestemd voor de geadresseerde(n) en bevat mogelijk vertrouwelijke gegevens. Het ongeautoriseerde gebruik, openbaarmaking of kopieren van deze gegevens door anderen dan de geadresseerde(n) is niet toegestaan. Indien u niet een geadresseerde bent en deze e-mail abusievelijk heeft ontvangen, verzoeken wij u direct contact met Skylinq op te nemen. Skylinq staat niet in voor de juiste en complete verzending van de informatie, noch is zij aansprakelijk voor enige vertraging in de ontvangst hiervan.

Van: Sergio Fernández Rubio [mailto:notifications@github.com]
Verzonden: maandag 27 juni 2016 15:51
Aan: zaidka/genieacs <genieacs@noreply.github.com>
CC: Harm van den Dikkenberg | Skylinq BV <harm@skylinq.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [zaidka/genieacs] GenieACS CWMP not start (#160)


That's because the xmljs.node file isn't in the good place. If you follow my guide here<https://github.com/zaidka/genieacs/wiki/Installation-in-Ubuntu-14.04-Server> that wouldn't have happened to you.

**Comment by DrumSergio** [comment]
The only thing I see is that you've not used root user. This guide is supposed to work only if you work while logged in as the root user. I've not tried it installing it in a non-root account. I know it's not recommended but for the moment it is working. I will prepare another guide using a non-root account.

**Comment by skylinqnl** [comment]
Thanks! With the root account works fine. That detail waste a lot of my time.

Greetings, Harm



Verzonden vanaf mijn Samsung-apparaat


-------- Oorspronkelijk bericht --------
Van: Sergio Fernández Rubio <notifications@github.com>
Datum: 28-06-16 00:58 (GMT+01:00)
Aan: zaidka/genieacs <genieacs@noreply.github.com>
Cc: Harm van den Dikkenberg | Skylinq BV <harm@skylinq.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [zaidka/genieacs] GenieACS CWMP not start (#160)


The only thing I see is that you've not used root user. This guide is supposed to work only if you work while logged in as the root user. I've not tried it installing it in a non-root account. I know it's not recommended but for the moment it is working. I will prepare another guide using a non-root account.

-

**Comment by skylinqnl** [comment]
Good evening,

I’ve reinstall on a brand new Ubuntu 14.04 installation with root access. But for me ist hard to get it working.

The CWMP dont work:

root@ACS:~# cd /genieacs-gui
root@ACS:/genieacs-gui# genieacs-cwmp

events.js:72

        throw er; // Unhandled 'error' event
              ^
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:106:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:459:13)
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:106:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:459:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:106:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:459:13)
29 Jun 00:06:05 - Worker 7618 died (8)
29 Jun 00:06:06 - Worker 7612 died (8)
29 Jun 00:06:06 - Worker 7623 died (8)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:106:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickDomainCallback (node.js:459:13)
29 Jun 00:06:07 - Worker 7619 died (8)
^Croot@ACS:/genieacs-gui#


AND this is the message on the webinterface. I’ve done the installation exactly of your tutorial and used option A.
==========================
Errno::ECONNREFUSED in HomeController#index
Failed to open TCP connection to localhost:7557 (Connection refused - connect(2) for "localhost" port 7557)
Extracted source (around line #17):
15
16
17
18
19
20


              threads << Thread.new(slice) do |slice|
                http = create_api_conn()
                res = http.head("/devices/?query=#{CGI::escape ActiveSupport::JSON.encode(slice['query'])}")
                slice['data'] = res['Total'].to_i
                slice['href'] = url_for(controller: 'devices', action: 'index', params: {query: ActiveSupport::JSON.encode(slice['query'])}, only_path: true)
                slice.delete('query')


Rails.root: /genieacs-gui
Application Trace<http://185.146.188.6:3000/> | Framework Trace<http://185.146.188.6:3000/> | Full Trace<http://185.146.188.6:3000/>
app/controllers/home_controller.rb:17:in `block (6 levels) in index'


Can you help me to make it working?

Met vriendelijke groet,

Harm van den Dikkenberg

[EMAIL skylinq_logo bg white_RGB_080116]
Kaaistraat 14
4695 CJ Sint Maartensdijk
T. 0166-760005
E. harm@skylinq.nl<mailto:harm@skylinq.nl>
I. www.skylinq.nl<http://www.skylinq.nl/>

KVK. 65472594
Op al onze producten en diensten zijn onze algemene voorwaarden<http://skylinq.nl/wp-content/uploads/2016/03/Algemene-voorwaarden-Skylinq.pdf> van toepassing.

Deze e-mail en de hierbij verzonden informatie is uitsluitend bestemd voor de geadresseerde(n) en bevat mogelijk vertrouwelijke gegevens. Het ongeautoriseerde gebruik, openbaarmaking of kopieren van deze gegevens door anderen dan de geadresseerde(n) is niet toegestaan. Indien u niet een geadresseerde bent en deze e-mail abusievelijk heeft ontvangen, verzoeken wij u direct contact met Skylinq op te nemen. Skylinq staat niet in voor de juiste en complete verzending van de informatie, noch is zij aansprakelijk voor enige vertraging in de ontvangst hiervan.

Van: Sergio Fernández Rubio [mailto:notifications@github.com]
Verzonden: dinsdag 28 juni 2016 00:58
Aan: zaidka/genieacs <genieacs@noreply.github.com>
CC: Harm van den Dikkenberg | Skylinq BV <harm@skylinq.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [zaidka/genieacs] GenieACS CWMP not start (#160)


The only thing I see is that you've not used root user. This guide is supposed to work only if you work while logged in as the root user. I've not tried it installing it in a non-root account. I know it's not recommended but for the moment it is working. I will prepare another guide using a non-root account.

**Comment by okraits** [comment]
Please discuss installation issues on the mailing list first and only create an issue if you think it's a bug in GenieACS.
