### ISSUE TITLE
TypeError: Cannot read property 'script' of undefined (genieacs-cwmp)

### ISSUE THREAD

**Issue by KiNGKiMO** [zaidka/genieacs#165]
Hello again,
I've one device to test new features, but I'm getting this error flooding the screen:-

27 Jul 08:25:56 - Worker 6279 died (0)
27 Jul 08:25:57 - 00E0FC-HG531%20V1-G6J8W15322005468: Inform (2 PERIODIC); retry count 1
(node) util.error is deprecated. Use console.error instead.
2016-07-27T06:25:57.605Z - TypeError: Cannot read property 'script' of undefined
at runVirtualParameters (/root/genieacs/lib/session.js:484:66)
at f (/root/genieacs/lib/session.js:581:12)
at /root/genieacs/lib/session.js:578:16
at /root/genieacs/lib/session.js:161:12
at /root/genieacs/lib/db.js:688:12
at handleCallback (/root/genieacs/node_modules/mongodb/lib/utils.js:96:12)
at /root/genieacs/node_modules/mongodb/lib/collection.js:1364:5
at handleCallback (/root/genieacs/node_modules/mongodb/lib/utils.js:96:12)
at /root/genieacs/node_modules/mongodb/lib/cursor.js:662:5
at handleCallback (/root/genieacs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:156:5)
27 Jul 08:25:57 - Worker 6319 listening to 0.0.0.0:7547

Any solutions?

**Comment by lcalderonboix** [comment]
I have exactly the same problem. Is there any solution?

**Comment by KiNGKiMO** [comment]
No, zaidka never replied.

**Comment by zaidka** [comment]
Apologies for looking at this earlier. Could you update your code and try again? If you still get an error please show me your relevant presets.

**Comment by KiNGKiMO** [comment]
Updated and the error is gone, I added a new device but parameters not sent, I had to refresh "InternetGatewayDevice" for the parameters to appear at genieacs...

Maybe something wrong with the bootstrap?

**Comment by zaidka** [comment]
This is the expected behavior. It will no longer fetch the entire data model tree, but will fetch as little as it needs to process your presets (for better performance).

You can get the old behavior by adding a refresh preset, but don't use that just yet as it's very slow. If I don't manage to optimize it dramatically then I may consider adding a config flag instead.

**Comment by KiNGKiMO** [comment]
Aha, I see.

Thank you so much Zaid, keep up the good work.
