### ISSUE TITLE
Online but not PING

### ISSUE THREAD

**Issue by lcalderonboix** [zaidka/genieacs#167]
Hi zaidka,

When I try to ping from the server to a ONLINE CPE appears the following message:

"Device is offline"

It's weird because the state of the CPE is "online".

I connect to the server by ssh and the CPE is reachable by ping.

How can I troubleshoot it?

Regards.

**Comment by yilcheng** [comment]
I got the same problems now, any idea?

**Comment by akcoder** [comment]
Are you using the v1.0 branch of the GUI? This issue was fixed about 5
months ago.

https://github.com/zaidka/genieacs-gui/tree/v1.0
