### ISSUE TITLE
genieacs-cwmp

### ISSUE THREAD

**Issue by ibrahimelsawy** [zaidka/genieacs#170]
genieacs-cwmp is giving below output now after redoing recommended configuration. is it working properly? and please support in how to show gui interface of the genieacs application ?

![genieacs-cwmp](https://cloud.githubusercontent.com/assets/20560579/18463451/901b176a-798a-11e6-941b-46a4b2a10e1b.JPG)

**Comment by okraits** [comment]
Can you provide your config.json?

Besides that, genieacs-cwmp is not providing genieacs-gui.

**Comment by okraits** [comment]
To setup genieacs-gui, you should follow the available installation instructions.
