### ISSUE TITLE
TransferComplete Fault information lost

### ISSUE THREAD

**Issue by rplatel** [zaidka/genieacs#171]
If a Download task fails, the CPE sends a "7 TRANSFER COMPLETE" inform and in that session sends a TransferComplete message like 

```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
 <SOAP-ENV:Header>
  <cwmp:ID SOAP-ENV:mustUnderstand="1">XXXXXXXYYYYZZZ</cwmp:ID>
 </SOAP-ENV:Header>
 <SOAP-ENV:Body>
  <cwmp:TransferComplete>
   <CommandKey></CommandKey>
   <FaultStruct>
    <FaultCode>9015</FaultCode>
    <FaultString>File transfer failure: unable to contact file server</FaultString>
   </FaultStruct>
   <StartTime>0001-01-01T00:00:00Z</StartTime>
   <CompleteTime>0001-01-01T00:00:00Z</CompleteTime>
  </cwmp:TransferComplete>
 </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

It seems like this fault information is discarded and not available to API clients.

It would be ideal if the download task wasn't considered completed until GenieACS gets a TransferComplete message and then marked as a faulty task if appropriate.  Otherwise it would be nice to have  _lastTransferComplete and _lastTransferCompleteFault or something.

**Comment by zaidka** [comment]
Agreed. I'll be working on the file transfer methods next week and will keep that in mind. Thanks for the suggestion
