### ISSUE TITLE
got error "Migrations are pending" when I try yo  login at http://my_IP:3000/ 

### ISSUE THREAD

**Issue by zhayun** [zaidka/genieacs#173]
I try to  login at http://my_IP:3000/, but got some error:
root@ubuntu:/opt/genieacs-gui# rails server
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.5.2 (ruby 2.3.1-p112), codename: Amateur Raccoon Rocketry
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2016-09-23 04:04:38 -0700
  
ActiveRecord::PendingMigrationError (

Migrations are pending. To resolve this issue, run:

	bin/rails db:migrate RAILS_ENV=development

):
  
activerecord (5.0.0) lib/active_record/migration.rb:572:in `check_pending!'
activerecord (5.0.0) lib/active_record/migration.rb:548:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.3.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.1.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0) lib/active_support/cache/strategy/local_cache_middleware.r

**Comment by saberspb** [comment]
All hello. I have just the same problem. Prompt, please, what to do. Ubuntu 14.04.05 LTS system.

**Comment by BrandedAlok** [comment]
yes i have the same issue please tell me what to do ?

**Comment by zaidka** [comment]
From the error message itself:

> To resolve this issue, run:
> bin/rails db:migrate RAILS_ENV=development

**Comment by BrandedAlok** [comment]
where to type
bin/rails db:,igrate RAILS_ENV=development ?

**Comment by BrandedAlok** [comment]
sir i typed cd bin
and then typed
rails db:migrate RAILS_ENV=development
and now when i am typing localhost its working .thank you sir
