### ISSUE TITLE
Missed code from lib/cwmp.coffee

### ISSUE THREAD

**Issue by mtvs** [zaidka/genieacs#175]
What happened to the logic of `TransferComplete` and `RequestDownload` in  [this commit](https://github.com/zaidka/genieacs/commit/19fea2ac72813fe328e059ba576811b235f48d53#diff-4dec47fa526083072a7baedb0fb28883)?

**Comment by zaidka** [comment]
Those methods will be handled differently. Implementation not yet complete. Please use the mailing list other questions like this.
