### ISSUE TITLE
installation truble

### ISSUE THREAD

**Issue by veso266** [zaidka/genieacs#176]
Hi I've tried to install GenieACS using theese instructions: https://github.com/zaidka/genieacs/wiki/Script-Installation---Ubuntu

but the problem is that the script installs latest versions of everything exept ruby so for instance rails can't be installed if there is ruby 2.1 (I've also tried using lastest version of Ruby but the problem is that GenieACS doesn't like it and it won't start 

So do you think is it posible for someone to just post already installed Vmware or Virtual Box VM for me to test on or help me to install that)

Thanks for Anwsering and Best Regards

**Comment by sabueso** [comment]
You can yourself modify that script and change ruby2.1 by ruby2.2 With Ruby 2.2 al goes fine.

**Comment by veso266** [comment]
I've tried that ruby2.2 can't be installed throught apt-get

**Comment by krisgermann** [comment]
Have you taken a look through this?: https://gist.github.com/allanmc/9fae5b2f85c5b9785ae1

Read the comments for necessary changes to ruby etc...

**Comment by zhayun** [comment]
@veso266  I'm very glad to share my vmware to you if you need.

**Comment by veso266** [comment]
@ zhayun thanks that would be awsome

**Comment by krisgermann** [comment]
@zhayun A vmware OVA? I'd be interested in that as well.

**Comment by zhayun** [comment]
@veso266  @krisgermann
please tell me your email address, I will send you the download url and tell you the settings of my vmware ubuntu.

**Comment by krisgermann** [comment]
You can email me at kris[at]bitstack[dot]io

**Comment by veso266** [comment]
@zhayun And you can send me your vmware image on romana@dxing.si

**Comment by krisgermann** [comment]
@zhayun you can email me at kris[at]bitstack[dot]io

**Comment by barneo2206** [comment]
@zhayun Can you send me your vmware image too? My address: barneo@wp.pl

**Comment by zaidka** [comment]
Hope this is sorted out. Please take any further discussion to the mailing list.
