### ISSUE TITLE
Error while running ./genieacs-cwmp script

### ISSUE THREAD

**Issue by developer-Sh** [zaidka/genieacs#178]
I have installed latest genieacs on my system.I am using the version of node js as node v0.10.46 for compiling and running the application.When i execute the script ./genieacs-cwmp. I am getting following error

in lib/device.js:19

const common = require('./common');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (<directory>/lib/session.js:27:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Please help me out.I am unable to resolve this issue.

**Comment by reli92** [comment]
i have the exactly the same problem ,fresh install of ubunutu 14.04.5 lts , used the installation script to install genieacs, only changed the ruby download in script from 2.1 in to 2.2 , and added the command 'sudo' before 'npm install genieacs' in script,also the webgui was with errors. 
![screenshot from 2016-10-20 13 54 12](https://cloud.githubusercontent.com/assets/22957002/19557172/3fe54db4-96cd-11e6-9f1a-d4a996a19b03.png)

**Comment by sabueso** [comment]
@developer-Sh  @reli92 Try to use the stable branch. 
git clone https://github.com/zaidka/genieacs.git -b master

**Comment by developer-Sh** [comment]
@sabueso I am using stable branch only.I am getting error in stable branch

**Comment by sabueso** [comment]
@developer-Sh in both projects?

**Comment by developer-Sh** [comment]
From https://genieacs.com/docs/,first I am using git clone https://github.com/zaidka/genieacs.git --branch v1.0 it is perfectly installed and working fine.But in this branch there is no implementation of faults,provisions so it is giving error in UI which is mention in this issue https://github.com/zaidka/genieacs-gui/issues/48.

So I updated the code to a stable branch.

I look into the problem found that http://stackoverflow.com/questions/36789889/syntaxerror-use-of-const-in-strict-mode  they are saying to update the node.js version to stable version.

But Genieacs is compatible with Node.js version  >=0.10 <=0.12. 

Please Correct me if I am doing something wrong.How to fix this issue

**Comment by developer-Sh** [comment]
I solved the problem it is related to my node js version.

Thanks for your help.

**Comment by trmagis** [comment]
Hi @developer-Sh 
Could You provide us the versions on which Genieacs is working? 
I would to know versions of: Ubuntu, Ruby, Node.js, Redis, Genieacs?

**Comment by developer-Sh** [comment]
Hello @trmagis you can go through this link https://github.com/zaidka/genieacs/wiki/Script-Installation---Ubuntu for installation genieacs

You can use node.js version 4.4 or 4.6

**Comment by reli92** [comment]
thanks guys , problem solved with node.js 4.6 thanks to @developer-Sh , all working , found my device and all the parameters but i can't change any of them because when i click the edit button the change option menu appear and disappear very fast , in 0.1 sec , all i want for now is to enable the telnet service in my router from 'false' to 'true' because cwmp is the only way to access this option. 
![screenshot from 2016-10-25 16 35 32](https://cloud.githubusercontent.com/assets/22957002/19688231/86603602-9ad1-11e6-8a6c-db566f912f95.png)

**Comment by reli92** [comment]
solved! installed ubunutu 14.04.5 lts instead of 14.04 lts
