### ISSUE TITLE
HTTP-digest auth (auth.js) impl. incorrect

### ISSUE THREAD

**Issue by seimnseimn** [zaidka/genieacs#181]
Hi zaid,

I just had some issues with the connection-request authentication (HTTP-digest) with a cpe and came to the conclusion that your auth.js implementation is not entirely correct.

RFC 2617 says:
cnonce
     This MUST be specified if a qop directive is sent (see above), and
     MUST NOT be specified if the server did not send a qop directive in
     the WWW-Authenticate header field. ...
	 
nonce-count
     This MUST be specified if a qop directive is sent (see above), and
     MUST NOT be specified if the server did not send a qop directive in
     the WWW-Authenticate header field.
	 
I did not study the whole rfc entirely but I recommend also NOT sending qop and opaque if it's not coming from the server (CPE).

See below trace from your ACS (1.0.7 and 1.1)

GET /64:68:0c:ff:9f:de HTTP/1.1
Host: 172.16.20.100:7547
Connection: keep-alive

HTTP/1.1 401 Authorization Required
Content-Length: 0
Server: TR069 client TCP connection request Server
WWW-Authenticate: Digest realm="TR069 Client", nonce="2pJr8usqYwn8NJppFBybt5GVWAAAYms", algorithm="MD5", domain="/64:68:0c:ff:9f:de"

GET /64:68:0c:ff:9f:de HTTP/1.1
Authorization: Digest username="cpe",realm="TR069 Client",nonce="2pJr8usqYwn8NJppFBybt5GVWAAAYms",uri="/64:68:0c:ff:9f:de",algorithm=MD5,qop=undefined,nc=00000001,cnonce="0a4f113b",response="b65a81440212995da5a6fe364f701d20",opaque="undefined"
Host: 172.16.20.100:7547
Connection: keep-alive

HTTP/1.1 401 Authorization Required
Content-Length: 0
Server: TR069 client TCP connection request Server
WWW-Authenticate: Digest realm="TR069 Client", nonce="sjAeWKW1XCV51sUsJx1kbHIsZCrxNAf", algorithm="MD5", domain="/64:68:0c:ff:9f:de"

-> see, my poor device is totaly frustrated and let me know through a Auth required even though the response MD5 is actually correct.

sending just...
GET /64:68:0c:ff:9f:de HTTP/1.1
Authorization: Digest username="cpe",realm="TR069 Client",nonce="2pJr8usqYwn8NJppFBybt5GVWAAAYms",uri="/64:68:0c:ff:9f:de",algorithm=MD5,response="b65a81440212995da5a6fe364f701d20"
Host: 172.16.20.100:7547
Connection: keep-alive
...and all works well

br
Simon

**Comment by DrumSergio** [comment]
Sounds interesting.

Hey, @zaidka , what do you think about this?

**Comment by zaidka** [comment]
Good catch. Will patch shortly.
