### ISSUE TITLE
What is the Genieacs end point to connect from cpe 

### ISSUE THREAD

**Issue by mkandrat** [zaidka/genieacs#182]
Hi,
   We are writing our own TR-069 Client.Already we have installed and started the genieacs server with all services cwmp,nbi,fs and gui. We want to communicate genieacs to send inform SOAP request from Java. Could anyone please let me know what is the genieacs end point to connect. Also how ACS connect back from ACS to CPE for further request(Setparameter value)? I know its not a issue. Don't know where to get the support. So I posted here. 

Thanks,
mkandrat

**Comment by okraits** [comment]
Please use the mailing list for topics like that.

**Comment by mkandrat** [comment]
Thanks okraits, sent mail to users@lists.genieacs.com. Is this correct?

**Comment by okraits** [comment]
Yes.

**Comment by mkandrat** [comment]
I am not getting any response from mail list.

**Comment by ManojSethuraman** [comment]
@mkandrat  Did you get any reply for the above request??

**Comment by mkandrat** [comment]
No i didn't get any response

**Comment by akcoder** [comment]
Try asking your question again.
