### ISSUE TITLE
genieacs-1.1.0-alpha cannot do download method.

### ISSUE THREAD

**Issue by wasidola** [zaidka/genieacs#183]
When I do download method, cwmp will have an error. I capture the packets and saw there has an error message is "Error: Task name not recognized"

And I check the cwmp log. it show

/opt/genieacs/lib/cwmp.js:425
　　　　　　throw err;
　　　　　　^

**Comment by zaidka** [comment]
Download method isn't implemented in the alpha just yet. Will update this thread when that's implemented.

**Comment by wasidola** [comment]
OK, I see. Thank you so much for your response!!

2016年11月8日 17:36，"Zaid Abdulla" <notifications@github.com>寫道：

Download method isn't implemented in the alpha just yet. Will update this
thread when that's implemented.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/zaidka/genieacs/issues/183#issuecomment-259089234>, or mute
the thread

**Comment by DrumSergio** [comment]
I think it is implemented now as we can see [here](https://github.com/zaidka/genieacs/blob/4b5dc25010c0732a16b42ba0cc6c0326689701e6/lib/default-provisions.js#L72). Let's wait to Zaid to confirm it.

**Comment by zaidka** [comment]
Yep, it is implemented now. Sorry I forgot to update this thread.
