### ISSUE TITLE
How to use add object Please check the attached image

### ISSUE THREAD

**Issue by mushir3589** [zaidka/genieacs#189]
![newaaa](https://cloud.githubusercontent.com/assets/23330990/20827974/33219958-b89b-11e6-9560-e976182c7bc7.jpg)

**Comment by akcoder** [comment]
Please take this to the mailing list. Github is for defect tracking.

**Comment by DrumSergio** [comment]
Hi @mushir3589 !

As @akcoder said, it's best to take this to the mailing list: http://lists.genieacs.com/mailman/listinfo

There you will find the help you need, as this is not a bug.

We can close this issue.
