### ISSUE TITLE
MongoDB client does not learn primary

### ISSUE THREAD

**Issue by JamesHarrison** [zaidka/genieacs#191]
Most MongoDB clients, when faced with a replSet, will pick the elected primary to write to.

GenieACS should also adopt this behaviour, or accept an array of MongoDB servers to pick a primary from.

**Comment by zaidka** [comment]
I haven't tried it, but with the config option "MONGODB_CONNECTION_URL" it should be possible to specify more than one MongoDB server as described [here](https://docs.mongodb.com/v3.2/reference/connection-string/). Let me know if that works.

**Comment by JamesHarrison** [comment]
Quite right - specifying all the servers and the replica set ID seems to be working as desired now!
