### ISSUE TITLE
device with space 0876FF-Technicolor%20TG784n%20v3-CP1409SA6C1

### ISSUE THREAD

**Issue by chandi61** [zaidka/genieacs#192]
HI all, maybe some one can help me, i try to ffind or the post via api on this device (0876FF-Technicolor%20TG784n%20v3-CP1409SA6C1) but not sucess but other device with no espace intro id_device its work how i can resolv this , thankyou all

**Comment by akcoder** [comment]
Please take this to the mailing list. Github is not for general support.

**Comment by smano14** [comment]
We need little support on this one please.
Can't understand why the option dont work in config.json.
Their is a "." in the path can't out this and the worker die and came back?
Its not already set in the new version?
XML option for empty path working?
Please juste tell us how to set the path-set before it write in database?

One month trying make it work the news lettre dont work we never have answer where can we have support for this?

**Comment by smano14** [comment]
Hi guys:
I find in the code where is the pb and I find an old post in 2014:
https://github.com/zaidka/genieacs/issues/16

I dont know if you get true "chandi61" but this is the PB on V1.1 alpha: Its not a real pb cause its the CPE who send bad parameters... Thanks Thomson Technicolor...
But a software need patch.
Make it compatible is a real solution.

Have the same PB exactly with a Technicolor tg789:
"<Name>.ExternalIPAddress</Name>"

Looks like its solved on v1.0.7 but not on V1.1, You can confirme cause im not 100% sur maybe I do a curl -i for make it work and dont remember cause a millions thing I do and finish late by night? 

Maybe I have the wrong common.js or their is something more to do for make it work? (Works means put it blank inside DATABASE more a patch that working solution).

Maybe we can set a parameter script for strange devices?

Looks like you ignore them and for solves this issue with that bad CPE you put the right path in parameters or doing a preset that refresh the right path? Can you confirme?

The thing is till the CPE is not registered no presets possible so need solve the register pb first.

"So you need modifie common.js or the coffee script." (Im trying right now)

I wonder if it can be solved differently no documentation so we think and we never sur....
Im not sur 100% if we can copy past the code in common.js from the V1.0.7 cause it miss a lots of option... They are real different but Maybe?

Can we call a special command like your test for different model?

The real question is what is the best way to solve this compatibility PB. I see a lots of CPE using this parameters settings.

Maybe you already set this and I dont see it?

Im thinking about something: Can we register them manually? curl -i something for create the register manually? Not really good solution but still can play with the tg789?
Or make a script who take the model and patch for it. Cause we have that info in the code before the DATA. If technicolor xxx apply patch for right path.

I know people make it work I will be very interesting to know wich solution them used for technicolor?

Thank you for your time
Yours truly Smano.

ps: I will post the code when I find a correct hack for this.
If you can make me win a day on that month of work I will thank you very much.
Happy new year have fun.

**Comment by DrumSergio** [comment]
Hi @smano14 !

I haven't understood very well this issue, nor the explanation. It may be that I am not English, but it's best to remember that here we mainly speak English as a second language. Could you explain it with some more organization in the mailing list? http://lists.genieacs.com/mailman/listinfo

If you can, then, we'll help you better, as we're all volunteers.

Thank you!

**Comment by noorzaie** [comment]
if _id contains space, you should url_encode it before query.
