### ISSUE TITLE
firmware upgrade issue

### ISSUE THREAD

**Issue by yasing** [zaidka/genieacs#194]
Hi, 
I'm trying to upgrade firmware according to "Push file" function, but I failed, the file has been uploaded to ACS with "Add firmware". There are several logs listed below.

**genieacs-cwmp LOG:**
4 Jan 19:53:36 - 001478-947XXGR-0014781f1f1f: Inform (0 BOOTSTRAP); retry count 0
4 Jan 19:54:46 - 001478-947XXGR-0014781f1f1f: Inform (6 CONNECTION REQUEST); retry count 0
4 Jan 19:54:46 - 001478-947XXGR-0014781f1f1f: Download (1596954dbc900)
(node) util.error is deprecated. Use console.error instead.
2017-01-04T11:54:46.290Z - TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at new ObjectID (/opt/genieacs/node_modules/bson/lib/bson/objectid.js:52:32)
    at /opt/genieacs/lib/db.js:895:24
    at Object.clearTasks (/opt/genieacs/lib/db.js:898:9)
    at /opt/genieacs/lib/cwmp.js:542:17
    at Command.callback (/opt/genieacs/lib/session.js:1951:18)
    at normal_reply (/opt/genieacs/node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/opt/genieacs/node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (/opt/genieacs/node_modules/redis/index.js:188:18)

/opt/genieacs/lib/server.js:76
  throw err;
  ^
TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at new ObjectID (/opt/genieacs/node_modules/bson/lib/bson/objectid.js:52:32)
    at /opt/genieacs/lib/db.js:895:24
    at Object.clearTasks (/opt/genieacs/lib/db.js:898:9)
    at /opt/genieacs/lib/cwmp.js:542:17
    at Command.callback (/opt/genieacs/lib/session.js:1951:18)
    at normal_reply (/opt/genieacs/node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/opt/genieacs/node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (/opt/genieacs/node_modules/redis/index.js:188:18)
4 Jan 19:54:46 - Worker 32054 died (7) null
4 Jan 19:54:46 - Worker 9431 listening to 0.0.0.0:6000
4 Jan 19:55:09 - 001478-947XXGR-0014781f1f1f: Inform (M Download,7 TRANSFER COMPLETE); retry count 1
4 Jan 19:55:10 - 001478-947XXGR-0014781f1f1f: Fault occurred in channel task_586ce0b0fbc7d70319c49a1c (retries: 0)

**NBI info:**
genieacs-gui$ curl -i 'http://localhost:7557/files'                                                                           
HTTP/1.1 200 OK
GenieACS-Version: 1.1.0-alpha
Content-Type: application/json
total: 1
Date: Wed, 04 Jan 2017 12:02:30 GMT
Connection: keep-alive
Transfer-Encoding: chunked
[
{"_id":"V3.61_2LAN_upgrade","filename":"V3.61_2LAN_upgrade","contentType":"binary/octet-stream","length":6164480,"chunkSize":261120,"uploadDate":"2017-01-03T13:52:13.542Z","aliases":null,"metadata":{"fileType":"1 Firmware Upgrade Image","oui":"001478","productClass":"947XXGR","version":"V3.61"},"md5":"7f2657709c977c5dcaf7f6bc976d2729"}

**CPE LOG:**
POST / HTTP/1.1
Host: 192.168.110.182:6000
User-Agent: BCM_TR69_CPE_04_00
Connection: keep-alive
SOAPAction: 
Cookie: session=e0fd7bb9c6fcacdd
Content-Type: text/xml
Content-Length: 0

HTTP/1.1 200 OK
Server: GenieACS/1.1.0-alpha
SOAPServer: GenieACS/1.1.0-alpha
Content-Type: text/xml; charset="utf-8"
Content-Length: 751
Date: Wed, 04 Jan 2017 11:54:46 GMT
Connection: keep-alive

POST / HTTP/1.1
Host: 192.168.110.182:6000
User-Agent: BCM_TR69_CPE_04_00
Connection: keep-alive
SOAPAction: 
Cookie: session=e0fd7bb9c6fcacdd
Content-Type: text/xml
Content-Length: 668

<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
    <SOAP-ENV:Header>
      <cwmp:ID SOAP-ENV:mustUnderstand="1">1596954dbc900</cwmp:ID>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
      <cwmp:DownloadResponse>
        <Status>1</Status>
        <StartTime>0001-01-01T00:00:00Z</StartTime>
        <CompleteTime>0001-01-01T00:00:00Z</CompleteTime>
      </cwmp:DownloadResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
tr69c:error:977.285:postComplete:1093:Post to ACS failed, Status = 3 error: illegal http response or read failure

tr69c:error:977.286:acsDisconnect:303:ACS Disconnect with error 3
tr69c:error:977.287:retrySessionConnection:186:ACS connect failed, retryCount = 1, backOffTime = 6000ms
<0>e253POST / HTTP/1.1
Host: 192.168.110.182:6000
User-Agent: BCM_TR69_CPE_04_00
Connection: keep-alive
SOAPAction: 
Content-Type: text/xml
Content-Length: 3448

<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
    <SOAP-ENV:Header>
      <cwmp:ID SOAP-ENV:mustUnderstand="1">251110820</cwmp:ID>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
      <cwmp:Inform>
        <DeviceId>
          <Manufacturer>Broadcom</Manufacturer>
          <OUI>001478</OUI>
          <ProductClass>947XXGR</ProductClass>
          <SerialNumber>0014781f1f1f</SerialNumber>
        </DeviceId>
        <Event SOAP-ENC:arrayType="cwmp:EventStruct[2]">
          <EventStruct>
            <EventCode>M Download</EventCode>
            <CommandKey>1596954dbc900</CommandKey>
          </EventStruct>
          <EventStruct>
            <EventCode>7 TRANSFER COMPLETE</EventCode>
            <CommandKey></CommandKey>
          </EventStruct>
        </Event>
        <MaxEnvelopes>1</MaxEnvelopes>
        <CurrentTime>2011-11-19T00:03:20+00:00</CurrentTime>
        <RetryCount>1</RetryCount>
        <ParameterList SOAP-ENC:arrayType="cwmp:ParameterValueStruct[0009]">
            <ParameterValueStruct>
              <Name>InternetGatewayDevice.DeviceSummary</Name>
              <Value xsi:type="xsd:string">InternetGatewayDevice:1.1[](Baseline:1, EthernetLAN:1, USBLAN:1, WiFiLAN:1, ADSLWAN:1, Time:1, IPPing:1, ATMLoopback:1, DSLDiagnostics:1, DeviceAssociation:1)</Value>
            </ParameterValueStruct>
            <ParameterValueStruct>
              <Name>InternetGatewayDevice.DeviceInfo.SpecVersion</Name>
              <Value xsi:type="xsd:string">1.0</Value>
            </ParameterValueStruct>
            <ParameterValueStruct>
              <Name>InternetGatewayDevice.DeviceInfo.HardwareVersion</Name>
              <Value xsi:type="xsd:string">V2.1</Value>
            </ParameterValueStruct>
            <ParameterValueStruct>
              <Name>InternetGatewayDevice.DeviceInfo.SoftwareVersion</Name>
              <Value xsi:type="xsd:string">V3.61</Value>
            </ParameterValueStruct>
            <ParameterValueStruct>
              <Name>InternetGatewayDevice.DeviceInfo.ProvisioningCode</Name>
              <Value xsi:type="xsd:string"></Value>
            </ParameterValueStruct>
            <ParameterValueStruct>
              <Name>InternetGatewayDevice.ManagementServer.ConnectionRequestURL</Name>
              <Value xsi:type="xsd:string">http://192.168.110.159:30005/</Value>
            </ParameterValueStruct>
            <ParameterValueStruct>
              <Name>InternetGatewayDevice.ManagementServer.ParameterKey</Name>
              <Value xsi:type="xsd:string"></Value>
            </ParameterValueStruct>
            <ParameterValueStruct>
              <Name>InternetGatewayDevice.LANDevice.1.LANEthernetInterfaceConfig.2.MACAddress</Name>
              <Value xsi:type="xsd:string">00:14:78:1f:1f:1f</Value>
            </ParameterValueStruct>
            <ParameterValueStruct>
              <Name>InternetGatewayDevice.WANDevice.3.WANConnectionDevice.1.WANIPConnection.2.ExternalIPAddress</Name>
              <Value xsi:type="xsd:string">192.168.110.159</Value>
            </ParameterValueStruct>
        </ParameterList>
      </cwmp:Inform>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
                                        HTTP/1.1 200 OK
Server: GenieACS/1.1.0-alpha
SOAPServer: GenieACS/1.1.0-alpha
Content-Type: text/xml; charset="utf-8"
Set-Cookie: session=aa3a321f9f871239
Content-Length: 530
Date: Wed, 04 Jan 2017 11:55:09 GMT
Connection: keep-alive

POST / HTTP/1.1
Host: 192.168.110.182:6000
User-Agent: BCM_TR69_CPE_04_00
Connection: keep-alive
SOAPAction: 
Cookie: session=aa3a321f9f871239
Content-Type: text/xml
Content-Length: 743

<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
    <SOAP-ENV:Body>
      <cwmp:TransferComplete>
        <CommandKey>1596954dbc900</CommandKey>
        <FaultStruct>
          <FaultCode>9010</FaultCode>
          <FaultString>Unable to connect to download server</FaultString>
        </FaultStruct>
        <StartTime>2011-11-19T00:02:58+00:00</StartTime>
        <CompleteTime>2011-11-19T00:03:19+00:00</CompleteTime>
      </cwmp:TransferComplete>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
HTTP/1.1 200 OK
Server: GenieACS/1.1.0-alpha
SOAPServer: GenieACS/1.1.0-alpha
Content-Type: text/xml; charset="utf-8"
Content-Length: 484
Date: Wed, 04 Jan 2017 11:55:09 GMT
Connection: keep-alive

POST / HTTP/1.1
Host: 192.168.110.182:6000
User-Agent: BCM_TR69_CPE_04_00
Connection: keep-alive
SOAPAction: 
Cookie: session=aa3a321f9f871239
Content-Type: text/xml
Content-Length: 0

HTTP/1.1 204 No Content
Server: GenieACS/1.1.0-alpha
SOAPServer: GenieACS/1.1.0-alpha
Content-Length: 0
Date: Wed, 04 Jan 2017 11:55:10 GMT
Connection: keep-alive

Thank you in advance.

**Comment by zaidka** [comment]
It doesn't look like it's specific to download. Try other kinds of tasks like refreshing a parameter.

What version of node are you using?

**Comment by yasing** [comment]
Hi Zaid,
Thanks for your reply.
I can refreshing parameters like serial number and so on.
Other info.

~$ node -v
v4.2.6
~$ rails --version
Rails 5.0.1

Thanks.

**Comment by zaidka** [comment]
Try upgrading to Node 6. 4.4 should work too but can't guarantee that it'll still be supported by the time the final release is out.

**Comment by yasing** [comment]
Hi,
I upgrade node to 6.4. And still can not upgrade firmware successful. Bug the logs show some other information.

CPE log is the same like last time.

**genieacs-cwmp log**
6 Jan 13:19:06 - Worker 5666 listening to 0.0.0.0:7547
6 Jan 13:19:06 - Worker 5673 listening to 0.0.0.0:7547
6 Jan 13:19:07 - Worker 5672 listening to 0.0.0.0:7547
6 Jan 13:19:07 - Worker 5674 listening to 0.0.0.0:7547
6 Jan 13:19:09 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (2 PERIODIC); retry count 1
6 Jan 13:19:10 - e8a6c6-93384MWVG-E8A6C6FFD078: Download (1597237648100)
6 Jan 13:19:11 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (M Download,7 TRANSFER COMPLETE); retry count 0
6 Jan 13:19:11 - e8a6c6-93384MWVG-E8A6C6FFD078: Fault occurred in channel task_586f26d80f7037152ab84639 (retries: 1)
6 Jan 13:20:48 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (6 CONNECTION REQUEST); retry count 0
6 Jan 13:20:48 - e8a6c6-93384MWVG-E8A6C6FFD078: Download (1597238e4fe00)
6 Jan 13:20:49 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (M Download,7 TRANSFER COMPLETE); retry count 0
6 Jan 13:20:49 - e8a6c6-93384MWVG-E8A6C6FFD078: Fault occurred in channel task_586f29307980ea165f57c9d4 (retries: 0)
6 Jan 13:24:09 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (2 PERIODIC); retry count 0
6 Jan 13:26:15 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (6 CONNECTION REQUEST); retry count 0
6 Jan 13:26:15 - e8a6c6-93384MWVG-E8A6C6FFD078: Download (159723de2d100)
6 Jan 13:26:16 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (M Download,7 TRANSFER COMPLETE); retry count 0
6 Jan 13:26:17 - e8a6c6-93384MWVG-E8A6C6FFD078: Fault occurred in channel task_586f2a77a9c2011659a542ce (retries: 0)
6 Jan 13:27:55 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (6 CONNECTION REQUEST); retry count 0
6 Jan 13:27:55 - e8a6c6-93384MWVG-E8A6C6FFD078: Download (159723f6a1c00)
6 Jan 13:27:57 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (M Download,7 TRANSFER COMPLETE); retry count 0
6 Jan 13:27:57 - e8a6c6-93384MWVG-E8A6C6FFD078: Fault occurred in channel task_586f2adb7f20d617917ec5df (retries: 0)
6 Jan 13:29:09 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (2 PERIODIC); retry count 0
6 Jan 13:34:08 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (2 PERIODIC); retry count 0
6 Jan 13:34:08 - e8a6c6-93384MWVG-E8A6C6FFD078: Fault occurred in channel task_586f1cc6050dca10f4673b67 (retries: 0)
6 Jan 13:34:08 - e8a6c6-93384MWVG-E8A6C6FFD078: Download (15972451afc00)
6 Jan 13:34:09 - e8a6c6-93384MWVG-E8A6C6FFD078: Inform (M Download,7 TRANSFER COMPLETE); retry count 0
6 Jan 13:34:09 - e8a6c6-93384MWVG-E8A6C6FFD078: Fault occurred in channel task_586f2a77a9c2011659a542ce (retries: 1)

**genieacs-nbi log:**
Started POST "/devices/e8a6c6-93384MWVG-E8A6C6FFD078" for 10.123.1.188 at 2017-01-06 13:27:55 +0800
Cannot render console from 10.123.1.188! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by DevicesController#update as HTML
  Parameters: {"authenticity_token"=>"OXF1uQ1IdcC93Dw0Fr4mHuUfWtiTx3to7WtZt6V17LtbB8sqAjajA4OA2cACn9R3F0GVC2DERPRprtJIaejlGg==", "commit"=>"[{\"name\":\"download\",\"file\":\"FAST3686_COMHEM_4.22.10-20161223_monolithic.bin\",\"filename\":\"FAST3686_COMHEM_4.22.10-20161223_monolithic.bin\"}]", "id"=>"e8a6c6-93384MWVG-E8A6C6FFD078"}
Redirected to http://10.123.1.184:3000/devices/e8a6c6-93384MWVG-E8A6C6FFD078
Completed 302 Found in 573ms (ActiveRecord: 0.0ms)


Started GET "/devices/e8a6c6-93384MWVG-E8A6C6FFD078" for 10.123.1.188 at 2017-01-06 13:27:56 +0800
Cannot render console from 10.123.1.188! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by DevicesController#show as HTML
  Parameters: {"id"=>"e8a6c6-93384MWVG-E8A6C6FFD078"}
  Rendering devices/show.html.erb within layouts/application
  Rendered devices/_tags.html.erb (0.7ms)
  Rendered devices/_last_inform.html.erb (1.8ms)
  Rendered devices/_summary_group.html.erb (0.9ms)
  Rendered devices/_tasks.html.erb (0.9ms)
  Rendered devices/_params.html.erb (4.0ms)
  Rendered devices/_commands.html.erb (1.9ms)
  Rendered devices/show.html.erb within layouts/application (15.4ms)
  Rendered layouts/_menu.html.erb (2.4ms)
Completed 200 OK in 162ms (Views: 124.3ms | ActiveRecord: 0.0ms)

**genieacs listen ports:**
ubuntu:/opt/genieacs/config$ netstat -nat|grep 75
tcp        0      0 0.0.0.0:7557            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:7567            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:7547            0.0.0.0:*               LISTEN     
ubuntu:/opt/genieacs/config$ netstat -nat|grep 3000
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN     

Thanks.

**Comment by zaidka** [comment]
It's no longer crashing so I'll go ahead and close this. What you're seeing is a fault and you can look at the faults collection in MongoDB  to see why it's failing (GUI doesn't show fault details, yet).

**Comment by yasing** [comment]
It's works now. Thanks.

**Comment by rcmajhi** [comment]
Hi Yasing

Can you please help me with the version of
node---
Ruby---
redis--
mongo db--

that you are using. I am also facing the same issue as described by you.

Looking forward for your support in this context.

Regards
Rama

**Comment by yasing** [comment]
Hi Rama,
The following is the versions. Hoping it helps.
node v6.4.0
nodejs v6.9.4
redis-server v=3.0.6 
MongoDB version: 2.6.10
ruby v2.3.1p112

**Comment by rcmajhi** [comment]
Thanks a lot Yasing.

after installing i am getting error while trying to launch
http/localhost:3000

ERROR message---------------------------------

ArgumentError in HomeController#index key must be 32 bytes
Extracted source (around line *#72*):

707172737475

      cipher = new_cipher
      cipher.encrypt
      cipher.key = @secret
      # Rely on OpenSSL for the initialization vector
      iv = cipher.random_iv

Rails.root: /home/genieacs/opt/genieacs-gui
Application Trace <http://localhost:3000/#> | Framework Trace
<http://localhost:3000/#> | Full Trace <http://localhost:3000/#>

activesupport (5.0.0) lib/active_support/message_encryptor.rb:72:in
`key=' <http://localhost:3000/#>
activesupport (5.0.0) lib/active_support/message_encryptor.rb:72:in
`_encrypt' <http://localhost:3000/#>
activesupport (5.0.0) lib/active_support/message_encryptor.rb:58:in
`encrypt_and_sign' <http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:592:in
`commit' <http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:465:in
`[]=' <http://localhost:3000/#>
actionpack (5.0.0)
lib/action_dispatch/middleware/session/cookie_store.rb:117:in
`set_cookie' <http://localhost:3000/#>
rack (2.0.1) lib/rack/session/abstract/id.rb:353:in `commit_session'
<http://localhost:3000/#>
rack (2.0.1) lib/rack/session/abstract/id.rb:224:in `context'
<http://localhost:3000/#>
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
<http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:613:in
`call' <http://localhost:3000/#>
activerecord (5.0.0) lib/active_record/migration.rb:552:in `call'
<http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in
`block in call' <http://localhost:3000/#>
activesupport (5.0.0) lib/active_support/callbacks.rb:97:in
`__run_callbacks__' <http://localhost:3000/#>
activesupport (5.0.0) lib/active_support/callbacks.rb:750:in
`_run_call_callbacks' <http://localhost:3000/#>
activesupport (5.0.0) lib/active_support/callbacks.rb:90:in
`run_callbacks' <http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in
`call' <http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in
`call' <http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in
`call' <http://localhost:3000/#>
actionpack (5.0.0)
lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
<http://localhost:3000/#>
web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
<http://localhost:3000/#>
web-console (3.3.1) lib/web_console/middleware.rb:28:in `block in
call' <http://localhost:3000/#>
web-console (3.3.1) lib/web_console/middleware.rb:18:in `catch'
<http://localhost:3000/#>
web-console (3.3.1) lib/web_console/middleware.rb:18:in `call'
<http://localhost:3000/#>
actionpack (5.0.0)
lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
<http://localhost:3000/#>
railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
<http://localhost:3000/#>
railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
<http://localhost:3000/#>
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in
`block in tagged' <http://localhost:3000/#>
activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in
`tagged' <http://localhost:3000/#>
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in
`tagged' <http://localhost:3000/#>
railties (5.0.0) lib/rails/rack/logger.rb:24:in `call' <http://localhost:3000/#>
sprockets-rails (3.1.1) lib/sprockets/rails/quiet_assets.rb:13:in
`call' <http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in
`call' <http://localhost:3000/#>
rack (2.0.1) lib/rack/method_override.rb:22:in `call' <http://localhost:3000/#>
rack (2.0.1) lib/rack/runtime.rb:22:in `call' <http://localhost:3000/#>
activesupport (5.0.0)
lib/active_support/cache/strategy/local_cache_middleware.rb:28:in
`call' <http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in
`call' <http://localhost:3000/#>
actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in
`call' <http://localhost:3000/#>
rack (2.0.1) lib/rack/sendfile.rb:111:in `call' <http://localhost:3000/#>
railties (5.0.0) lib/rails/engine.rb:522:in `call' <http://localhost:3000/#>
puma (3.5.2) lib/puma/configuration.rb:225:in `call' <http://localhost:3000/#>
puma (3.5.2) lib/puma/server.rb:569:in `handle_request'
<http://localhost:3000/#>
puma (3.5.2) lib/puma/server.rb:406:in `process_client'
<http://localhost:3000/#>
puma (3.5.2) lib/puma/server.rb:271:in `block in run' <http://localhost:3000/#>
puma (3.5.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
<http://localhost:3000/#>

Request

*Parameters*:

None

Toggle session dump <http://localhost:3000/#>

_csrf_token: "v5tswjcOxqPAM7xF0wd/4eJBietGu0KOSSKl2HDgmgI="
session_id: "1d648c503073fffc25fa9e65e8731460"

Toggle env dump <http://localhost:3000/#>

GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.5"
HTTP_CACHE_CONTROL: "max-age=0"
HTTP_VERSION: "HTTP/1.1"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "127.0.0.1"
SERVER_NAME: "localhost"
SERVER_PROTOCOL: "HTTP/1.1"


kindly guide me...

**Comment by zaidka** [comment]
@rcmajhi, this is not related to this thread nor is it an issue. Please take it to the mailing list.

**Comment by LeVanVuong93** [comment]
Hi yasing,
Did you fix this? I am also having problems with adding firmwave. Please help me if that does not bother you.
Thanks you so much.

**Comment by yasing** [comment]
> Hi yasing,
> Did you fix this? I am also having problems with adding firmwave. Please help me if that does not bother you.
> Thanks you so much.

I have fixed this by config file. You should check the file genieacs/config/config.json.
I set FS_HOSTNAME to the IP address of the ACS server. It works for me. Hope it helps.

**Comment by LeVanVuong93** [comment]
> > Hi yasing,
> > Did you fix this? I am also having problems with adding firmwave. Please help me if that does not bother you.
> > Thanks you so much.
> 
> I have fixed this by config file. You should check the file genieacs/config/config.json.
> I set FS_HOSTNAME to the IP address of the ACS server. It works for me. Hope it helps.

Hi Yasing,
Thanks for your information. I have setup FS_HOSTNAME to the IP addess of ACS server. After I retry add firmware and have issue as below:

"FAULTCODE:
9808

FAULTSTRING:
Receive firmware length error"

Have you get that issue ?
If you have fixed that issue, please support to me fix it.
Thanks you so much.

**Comment by LeVanVuong93** [comment]
> > Hi yasing,
> > Did you fix this? I am also having problems with adding firmwave. Please help me if that does not bother you.
> > Thanks you so much.
> 
> I have fixed this by config file. You should check the file genieacs/config/config.json.
> I set FS_HOSTNAME to the IP address of the ACS server. It works for me. Hope it helps.

Hi yasing,
I have fixed this by your support.
Thanks you so much !
