### ISSUE TITLE
import XML file with vendor objets

### ISSUE THREAD

**Issue by skaith** [zaidka/genieacs#195]
Hi all.
I have a big trouble with genie. I try to manage a zte router with it but i dont get all objets from CPE. Vendor provides me a xml file with a large tree of objets but i don know how to import it to my ACS.
Can someone help me? 
kind regards!

**Comment by akcoder** [comment]
Github is for defect tracking. Please take support issues to the mailing
list.

**Comment by skaith** [comment]
sorry, where i can find help about my issue?

**Comment by DrumSergio** [comment]
Hi @skaith !

Please notice that if you're using v1.1 of GenieACS, it doesn't fetch all the parameters from every CPE.

Anyway, talk about it with some more info in the mailing list: http://lists.genieacs.com/mailman/listinfo
