### ISSUE TITLE
Router not showing up on GenieACS

### ISSUE THREAD

**Issue by etnisevil** [zaidka/genieacs#196]
Router not showing up on GenieACS
GienieACS server don’t see request from totolink  routers ,router sent soap  request 
GenieACS server  --branch master are installed on Ubuntu 16.04  root user 
For redirect request to localhost:7547 first was used nginx and when apache2 
Cwmp, nbi and fs process starts without any error. All autch was disabled and firewall was disabled.   
I

**Comment by DrumSergio** [comment]
Hi @etnisevil !

Could you explain it with more info? Including some logs, or if you haven't, some traces.

Anyway, I think the best is to discuss it in the mailing list: http://lists.genieacs.com/mailman/listinfo
