### ISSUE TITLE
Cisco 867 Resources exceeded

### ISSUE THREAD

**Issue by slackr31337** [zaidka/genieacs#197]
When adding a new device (CISCO867VAE) the refreshObject task returns "Resources exceeded" fault. Unable to get the device parameters.

**Comment by DrumSergio** [comment]
Hi, @slackr31337 !

Could you put some more info? Which are the server specs?

Anyway, if you're unsure this is a bug, it's best to post this question in the mailing list http://lists.genieacs.com/mailman/listinfo
