### ISSUE TITLE
[vulnerability] Patch for NTP Injection

### ISSUE THREAD

**Issue by DrumSergio** [zaidka/genieacs#199]
Following [last post](https://github.com/zaidka/genieacs/issues/138#issuecomment-266052335) from Issue #138 there's been seen some botnets attacking port 7547 via command injection through some options for NTP Servers.

More info [here](http://morris.guru/quick-tr069-botnet-writeup-triage/)

This can be mitigated through a nginx option, but I think it's best to implement from GenieACS itself.

How do you think this could be implemented through a PR?

Thank you!

**Comment by zaidka** [comment]
That attack is targeted at CPEs, not the ACS. As far as the ACS is concerned, it's just a malformed message that causes an error to be thrown. Not much to be done I guess.

**Comment by DrumSergio** [comment]
Ok. Thanks!
