### ISSUE TITLE
Failed at the libxmljs install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by chrisawad** [zaidka/genieacs#200]
This is on the latest build of CentOS 7.
I tried to do it via "npm i -g genieacs" first, and the same error occurred as did on the V1.0 branch.

> make: Leaving directory `/opt/genieacs/node_modules/libxmljs/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 3.10.0-514.el7.x86_64
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /opt/genieacs/node_modules/libxmljs
> gyp ERR! node -v v6.9.5
> gyp ERR! node-gyp -v v3.5.0
> gyp ERR! not ok
> genieacs@1.0.7 /opt/genieacs
> ├── coffee-script@1.12.3
> ├─┬ hiredis@0.4.1
> │ ├── bindings@1.2.1
> │ └── nan@2.5.1
> ├─┬ mongodb@1.4.40
> │ ├─┬ bson@0.2.22
> │ │ └── nan@1.8.4
> │ ├─┬ kerberos@0.0.11
> │ │ └── nan@1.8.4
> │ └─┬ readable-stream@2.2.2
> │   ├── buffer-shims@1.0.0
> │   ├── core-util-is@1.0.2
> │   ├── inherits@2.0.3
> │   ├── isarray@1.0.0
> │   ├── process-nextick-args@1.0.7
> │   ├── string_decoder@0.10.31
> │   └── util-deprecate@1.0.2
> └── redis@0.12.1
> 
> npm ERR! Linux 3.10.0-514.el7.x86_64
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
> npm ERR! node v6.9.5
> npm ERR! npm  v4.1.2
> npm ERR! code ELIFECYCLE
> 
> npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the libxmljs package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs libxmljs
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls libxmljs
> npm ERR! There is likely additional logging output above.

**Comment by zaidka** [comment]
Not an issue. Please use the mailing list for support.

**Comment by DrumSergio** [comment]
Hi @chrisawad !

This may be related to the NodeJS version you're using, but we can bring you more help in the mailing list, as @zaidka said. Post there with more info about what you've installed and the steps you've gone through, please: http://lists.genieacs.com/mailman/listinfo
