### ISSUE TITLE
MongoError when uploading file

### ISSUE THREAD

**Issue by mjducharme** [zaidka/genieacs#207]
I am receiving an error message when trying to upload a file:

Unexpected error (500): MongoError: Can't get executor for query { files_id: "miked.alter", n: { $gte: 0 } }

The file upload fails. GenieACS seems to work apart from this.

**Comment by DrumSergio** [comment]
Hi @mjducharme !

This issue tracker is intended to be used for bug tracking. For these types of issues, ask it in the [Users mailing list](lists.genieacs.com). It may be a bug, but first ask it there, so we can help you out and pinpoint whether it's a bug or not.
And more info would be great, like software versions' installed (including MongoDB and GenieACS versions, at least), type of file uploaded, size, exact steps, and more info...

Thank you!

**Comment by mjducharme** [comment]
Hi,

I have resolved the issue by upgrading from GenieACS 1.0.7 to the current 1.1.0 alpha.

**Comment by DrumSergio** [comment]
Thank you for answering, @mjducharme 

If you use GenieACS-GUI v1.1 then you need to use GenieACS base v1.1. The same happens for v1.0. 

Please, close the issue if you can. 

Regards

**Comment by mjducharme** [comment]
Yes I figured. What I had first was GenieACS 1.0.7 and GUI 1.0. This error occurred. Then I upgraded GUI to latest github source. The issue persisted. Then I upgraded GenieACS to 1.1.0 alpha and the issue disappeared.
