### ISSUE TITLE
Regex via API is not working when inside a $(operator)

### ISSUE THREAD

**Issue by DrumSergio** [zaidka/genieacs#208]
When performing a basic regex, it works:

```
curl -i 'http://my.server.com:7557/devices/?query=%7B"_id"%3A"/^000B82/"%7D'
```

or, translated:

```
{"_id" : "/^000B82/"}
```

That would search for devices with the same OUI (just an example, it's obvious it's not the best way to do it)

But if you want to do something like searching the rest of the devices (The ones which doesn't have that OUI):

```
{"_id" : {"$ne" : "/^000B82/"}}
```

Then that doesn't work, as the API treats it like a plain value:

```
curl -i 'http://my.server.com:7557/devices/?query=%7B"_id"%3A%7B"%24ne"%3A"/^000B82"%7D%7D'
```

I can see it replies me with ALL the CPEs, but it should only reply me with one.
I've tried with another queries with operators and without regex, and it works. The problem is when you try to introduce there JavaScript regular expression objects. That would be a good feature to add to nbi.coffee, as [the MongoDB documentation tells it's supporting this type of regex inside an operator](https://docs.mongodb.com/manual/reference/operator/query/regex/#in-expressions)

This has been an investigation after [this mail at the mailing list](http://lists.genieacs.com/pipermail/users/2017-February/001186.html)

**Comment by zaidka** [comment]
Doesn't look like MongoDB supports that. Tried the following in Mongo client:

    db.devices.count({"_id" : {"$ne" : /^202BC1/}})

and got the error "Can't have regex as arg to $ne."

**Comment by DrumSergio** [comment]
I have a device whose _id is 000B82-HT701-000b8288226 connected to an isolated instance with no other CPEs connected.

When I send the following:

`db.devices.find({"_id" : {$in: [ /000B82-HT701-000b82882268/ ]}})`

It's working perfectly without errors.

And it's working also:

`db.devices.find({"_id" : {$ne: [ /randomstring/ ]}})`

which is outputting the same as the first command. (If I invert regex arguments between both commands, nothing is printed, and that's a sign it's working ok)

But when I try to call it via curl using NBI:

`curl -i 'http://my.server.com:7557/devices/?query=%7B"_id"%3A%7B"%24ne"%3A/randomstring/%7D%7D'`

It gives me the following error:

`HTTP/1.1 400 Bad Request
GenieACS-Version: 1.1.0-alpha
Date: Mon, 06 Mar 2017 12:35:18 GMT
Connection: keep-alive
Transfer-Encoding: chunked

SyntaxError: Unexpected token / in JSON at position 14`

**Comment by zaidka** [comment]
The query needs to be a proper JSON string. Regular expressions must be quoted like a regular string and the API will interpret them as regex. This API call:

    curl -I http://localhost:7557/devices/?query=%7B%22_id%22%3A%7B%22%24ne%22%3A%5B%22%2F%5E202BC1%5C%5C-BM632w%5C%5C-0000000%24%2F%22%5D%7D%7D

gives the same result as this query:

    db.devices.count({"_id":{"$ne":[/^202BC1\-BM632w\-0000000$/]}})
