### ISSUE TITLE
addtag in preset causes adding another senseless tag

### ISSUE THREAD

**Issue by mrakotiq** [zaidka/genieacs#211]
It's very weird and I can not figure out where it formed.
The first tag added to device from preset causes adding another undesirable tag. This tag come from precondition rule of another preset.  Very difficult for explanation with my english. Maybe it will be clear from the screenshots.

To make it clear NNNNP string is not used anywhere else in the system
version last GIT 1.1

![genieacs_tag_issue_device](https://cloud.githubusercontent.com/assets/15812752/23561778/f6bad30c-003f-11e7-9674-800d95ecd4fc.png)
![genieacs_tag_issue_ont_preset](https://cloud.githubusercontent.com/assets/15812752/23561779/f6bc7f86-003f-11e7-90b3-9e8db742f5f4.png)
![genieacs_tag_issue_port_preset](https://cloud.githubusercontent.com/assets/15812752/23561777/f6b96594-003f-11e7-8c21-7e1da2f7a514.png)

**Comment by zaidka** [comment]
That's odd! Could you post the preset objects as stored in the database? Simply run "db.presets.find()" in MongoDB CLI client.

**Comment by mrakotiq** [comment]
Attaching preset dump from our lab enviroment.

[genieacs_addtag_issue_preset_dump.txt](https://github.com/zaidka/genieacs/files/818546/genieacs_addtag_issue_preset_dump.txt)

**Comment by zaidka** [comment]
There's nothing out of the ordinary there. I failed to reproduce the issue locally. Did this happen once or can you reliably reproduce it?

**Comment by mrakotiq** [comment]
Well that's bad :-|
Problem is 100% reproducible our environment. When do:
1) Factory reset CPE + Delete from devices
2) New Device registred and when tag from preset is addet will also spawn the unwanted tag
It looks that unwanted tag come from forgoten/reused variable/object. But can not figure out where.

I tried to do some debug logs in different locations, but without success. Any recommendations where to look?

**Comment by mrakotiq** [comment]
One more remark.
When remove tags from already registered device and  do refresh. Everything is as it should be.

**Comment by zaidka** [comment]
I managed to reproduce it after deleting the device. What is this sorcery! I'm looking into it.
