### ISSUE TITLE
Can't install using libxmljs 0.14.4

### ISSUE THREAD

**Issue by Prophecy67** [zaidka/genieacs#212]
Using CentOS7, Installed gcc-c++, gcc, make, mongodb-server and client, redis etc. What am I missing?

make: Leaving directory `/usr/lib/node_modules/genieacs/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-514.6.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/genieacs/node_modules/libxmljs
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/usr/lib
└── (empty)

npm ERR! Linux 3.10.0-514.6.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-g" "genieacs"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

**Comment by akcoder** [comment]
Please close this issue and take this question to the mailing list. GitHub is for defect tracking, not installation issues. 

-dan

**Comment by Prophecy67** [comment]
It's not as much installation issues, But a definite NPM issue when 'installing' as well. It's not as easy as following the how-to anymore since a lot of deps (libxmljs, bson) need to be actually NPM linked to get to a working scenario.. But I'll drop it then?

**Comment by akcoder** [comment]
Don't drop it, take it to the mailing list :)

**Comment by DrumSergio** [comment]
Hi @Prophecy67 !

We really want to help you, but it's best to follow the guides. [Post it in the mailing list](http://lists.genieacs.com) along with the node version you're using, npm version, what steps did you follow... More info, more help! :)
