### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by mhils** [zaidka/genieacs#213]
Hi,

What is the preferred method to report security vulnerabilites for genieacs?

Thanks,
Max

**Comment by zaidka** [comment]
I would prefer all discussions to go to the mailing list. For potentially serious vulnerabilities I guess it's best to drop me an email (see my profile). Thanks.

**Comment by mhils** [comment]
Thanks for the quick reply. Do you prefer encrypted email communication or plaintext?

**Comment by zaidka** [comment]
I don't mind either way. Sounds like you're about to ruin my day.

**Comment by mhils** [comment]
I try not to. :-)

Our main find is not specific to genieacs, so we need some time to coordinate with other folks. Just asking now so that I have your email address ready. Thanks again!
