### ISSUE TITLE
soap.js - crash if boolean is empty

### ISSUE THREAD

**Issue by seimnseimn** [zaidka/genieacs#215]
Hi Zaid,

I have a device which incorrectly sends an empty boolean as a value.
I fixed it quite easily with replacing in soap.js

93:   else if (v === "false" || v === "FALSE" || v === "False" || v === "0" || v ==="")
96:     throw new Error("Invalid boolean value '" + v + "'");

I did not want to issue a pull request for this but I guess we could allow an empty boolean to be interpreted as a false? I don't see that this would compromise anything?

**Comment by zaidka** [comment]
A similar workaround was just implemented in 1a5fd65f. Rather than assume the value to be false, it uses the original string as-is when it fails to parse it.

**Comment by seimnseimn** [comment]
This seems not to work. When the device has an empty boolean or empty int/unsignedint the device is not put into acs correctly. I guess you can simulate this quite easily

**Comment by zaidka** [comment]
I just double checked and it's working as expected: it shows a warning and keeps the invalid value as a string without trying to parse it.
