### ISSUE TITLE
CWMP is doing its own SetParameterValues following GetParameterValuesResponse

### ISSUE THREAD

**Issue by spencerlambert** [zaidka/genieacs#218]
This is happening in version 1.1.1 to me.  I'm running a diagnostic ping, which requires that I first set `InternetGatewayDevice.IPPingDiagnostics.DiagnosticsState` to `Requested`.

## My API call to get things started.
```
POST to http://my-genie-server:7557/devices/00019F-AC1200MS-12MS001288/tasks?timeout=3000&connection_request
{
  "name":"setParameterValues",
  "parameterValues":[
    [
      "InternetGatewayDevice.IPPingDiagnostics.DiagnosticsState",
      "Requested"
    ]
  ]
}
```

The devices runs the ping test and changes the `DiagnosticsState` to `Completed`, replying with a `8 DIAGNOSTIC COMPETE` inform.

## Device make an inform after the diagnostic is complete. 
```
<Event xsi:type='soap-enc:Array' soap-enc:arrayType='cwmp:EventStruct[1]'>
<EventStruct>
<EventCode>8 DIAGNOSTICS COMPLETE</EventCode>
<CommandKey></CommandKey>
</EventStruct>
</Event>
```

I now need to verify that the diagnostic was completed, so I do a `getParameterValues` request.

## This is the XML the ACS send to the device. 
```
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
  <soap-env:Header>
    <cwmp:ID soap-env:mustUnderstand="1">15b08bf0c0b000</cwmp:ID>
  </soap-env:Header>
  <soap-env:Body>
    <cwmp:GetParameterValues>
      <ParameterNames soap-enc:arrayType="xsd:string[1]">
        <string>InternetGatewayDevice.IPPingDiagnostics.DiagnosticsState</string>
      </ParameterNames>
    </cwmp:GetParameterValues>
  </soap-env:Body>
</soap-env:Envelope>
```

## This is the reply the device makes
```
<?xml version='1.0' encoding='UTF-8'?>
<soap-env:Envelope xmlns:soap-env='http://schemas.xmlsoap.org/soap/envelope/' xmlns:soap-enc='http://schemas.xmlsoap.org/soap/encoding' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:cwmp='urn:dslforum-org:cwmp-1-0'>
<soap-env:Header>
<cwmp:ID soap-env:mustUnderstand='1'>15b08bf0c0b000</cwmp:ID>
</soap-env:Header>
<soap-env:Body>
<cwmp:GetParameterValuesResponse>
<ParameterList xsi:type='soap-enc:Array' soap-enc:arrayType='cwmp:ParameterValueStruct[1]'>
<ParameterValueStruct>
<Name>InternetGatewayDevice.IPPingDiagnostics.DiagnosticsState</Name>
<Value xsi:type='xsd:string'>Complete</Value>
</ParameterValueStruct>
</ParameterList>
</cwmp:GetParameterValuesResponse>
</soap-env:Body>
</soap-env:Envelope>
```

## Oh, nice it's Complete.  What?!? Wait a minute here ACS!  Why are you doing a SetParameterValues?  I didn't request this.
```
2017-03-26T03:53:10.974Z [INFO] [MY DEVICE IP] 00019F-AC1200MS-12MS001288: ACS request; acsRequestId="15b08bf0c0b200" acsRequestName="SetParameterValues"
```

## The ACS then fires off this XML message to the device.
```
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
  <soap-env:Header>
    <cwmp:ID soap-env:mustUnderstand="1">15b08bf0c0b200</cwmp:ID>
  </soap-env:Header>
  <soap-env:Body>
    <cwmp:SetParameterValues>
      <ParameterList soap-enc:arrayType="cwmp:ParameterValueStruct[1]">
        <ParameterValueStruct>
          <Name>InternetGatewayDevice.IPPingDiagnostics.DiagnosticsState</Name>
          <Value xsi:type="xsd:string">Requested</Value>
        </ParameterValueStruct>
      </ParameterList>
      <ParameterKey/>
    </cwmp:SetParameterValues>
  </soap-env:Body>
</soap-env:Envelope>
```

## Noooo!  The ACS has overridden the value on the devices, causing a new diagnostic to run.

Why is the ACS trying to update the value on the device, when it's different from the db, rather than updating the db?

**Comment by zaidka** [comment]
How are you originally setting the parameter to "Requested"?

**Comment by spencerlambert** [comment]
I have another router I can point at your ACS, so you can test it.  It's easiest if it's behind NAT which would require STUN.

**Comment by spencerlambert** [comment]
I'm using the `setParameterValues` NBI API call.

**Comment by zaidka** [comment]
Can you capture traffic using tcpdump or Wireshark of the session where the parameter is first set?

**Comment by spencerlambert** [comment]
As I ponder on this, it could be caused by the `presets` I create along side of setting the values.  I want the ACS to restore values like the SSID and Passphrase when the device is factory reset.  My guess is the ACS reads the presets and if they differ from what is on the device, it fires off a set value.  At this time, there is a preset based on the Serial Number of the device, and it has `InternetGatewayDevice.IPPingDiagnostics.DiagnosticsState` set to `Requested`.

Does `presets` logic fire when doing a `getParameterValues` call?

**Comment by zaidka** [comment]
Presets are tested at all times. The session will not end until all presets are satisfied.

**Comment by spencerlambert** [comment]
Ahhh...  That's got to be it.

Is there something different besides presets that would run when a device is factory reset?

**Comment by zaidka** [comment]
> Is there something different besides presets that would run when a device is factory reset?

No.

I'll go ahead and close this then.
