### ISSUE TITLE
Preset filtered by event not working.

### ISSUE THREAD

**Issue by rplatel** [zaidka/genieacs#219]
We are trying to set up a preset to refresh some parameters.  Configuring it with no filters, everything works as expected.  If we add any event, the preset never fires. 

I think I tracked the issue down to these lines in cwmp.coffee:applyPresets:

```
    deviceEvents = {}
    for p in sessionContext.deviceData.paths.find(['Events', '*'], false, true)
      if sessionContext.timestamp <= sessionContext.deviceData.attributes.get(p)?.value?[1][0]
        deviceEvents[p[1]] = true
```

I'm not sure what this is supposed to be checking but doing some printf debugging, I found that `deviceEvents` is always empty.

For our RG, for a "2 PERIODIC"  `sessionContext.deviceData.attributes.get(p)?.value?[1][0]` is always undefined while `sessionContext.timestamp` is always approximately now, so the test always fails.  

Maybe the sense of the test is backwards and it should be >=?

**Comment by zaidka** [comment]
Can you share steps to reproduce the issue? I created a preset with the event "2 PERIODIC" and it seems to work as expected.

**Comment by rplatel** [comment]
Nothing fancy.  We are on the latest commit from GitHub.  We have the preset pictured here, if we leave the event blank the preset works as expected, if we put any event in, it never fires.  Confirmed by tcpdump'ing between the RG and GenieACS.  


![screenshot 2017-03-27 15 39 04](https://cloud.githubusercontent.com/assets/1406848/24374638/9a35109e-1303-11e7-8ce7-982a846676b2.png)

**Comment by zaidka** [comment]
Yeah, that works fine with me. Maybe your device isn't sending the correct event code?

**Comment by rplatel** [comment]
I'll paste below what the device is sending.  

Can you give me a sense of what that test is checking? As I say, it looks like `sessionContext.deviceData.attributes.get(p)?.value?[1][0]` is always `undefined` for this device. 


```
127.000.000.001.37186-127.000.000.001.17547: POST / HTTP/1.0
X-Real-IP: XXX.XXX.XXX.XXX
Host: acs.hb.dev.tucows.net:7547
Connection: close
Content-Length: 2551
User-Agent: CyberGarage-HTTP/1.0
SOAPAction:
Content-Type: text/xml
Authorization: Basic ***********************=

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
 <SOAP-ENV:Header>
  <cwmp:ID SOAP-ENV:mustUnderstand="1">S162V12000092</cwmp:ID>
 </SOAP-ENV:Header>
 <SOAP-ENV:Body>
  <cwmp:Inform>
   <DeviceId>
    <Manufacturer>ZyXEL</Manufacturer>
    <OUI>E8377A</OUI>
    <ProductClass>EMG3425-Q10A</ProductClass>
    <SerialNumber>S162V12000092</SerialNumber>
   </DeviceId>
   <Event SOAP-ENC:arrayType="cwmp:EventStruct[1]">
    <EventStruct>
     <EventCode>2 PERIODIC</EventCode>
     <CommandKey></CommandKey>
    </EventStruct>
   </Event>
   <MaxEnvelopes>1</MaxEnvelopes>
   <CurrentTime>2016-09-22T22:50:52</CurrentTime>
   <RetryCount>0</RetryCount>
   <ParameterList SOAP-ENC:arrayType="cwmp:ParameterValueStruct[8]">
    <ParameterValueStruct>
     <Name>InternetGatewayDevice.DeviceSummary</Name>
     <Value xsi:type="xsd:string">InternetGatewayDevice:1.0[](Baseline:1, EthernetLAN:1, WiFiLAN:1, WiFiWMM:1, WiFiWPS:1, EthernetWAN:1)</Value>
    </ParameterValueStruct>
    <ParameterValueStruct>
     <Name>InternetGatewayDevice.DeviceInfo.SpecVersion</Name>
     <Value xsi:type="xsd:string"></Value>
    </ParameterValueStruct>
    <ParameterValueStruct>
     <Name>InternetGatewayDevice.DeviceInfo.HardwareVersion</Name>
     <Value xsi:type="xsd:string">A01</Value>
    </ParameterValueStruct>
    <ParameterValueStruct>
     <Name>InternetGatewayDevice.DeviceInfo.SoftwareVersion</Name>
     <Value xsi:type="xsd:string">V1.00(AAYJ.4)C0_20160603</Value>
    </ParameterValueStruct>
    <ParameterValueStruct>
     <Name>InternetGatewayDevice.DeviceInfo.ProvisioningCode</Name>
     <Value xsi:type="xsd:string"></Value>
    </ParameterValueStruct>
    <ParameterValueStruct>
     <Name>InternetGatewayDevice.ManagementServer.ConnectionRequestURL</Name>
     <Value xsi:type="xsd:string">http://XXX.XXX.XXX.XXX:30005</Value>
    </ParameterValueStruct>
    <ParameterValueStruct>
     <Name>InternetGatewayDevice.ManagementServer.ParameterKey</Name>
     <Value xsi:type="xsd:string"></Value>
    </ParameterValueStruct>
    <ParameterValueStruct>
     <Name>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress</Name>
     <Value xsi:type="xsd:string">XXX.XXX.XXX.XXX</Value>
    </ParameterValueStruct>
   </ParameterList>
  </cwmp:Inform>
 </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by zaidka** [comment]
Are you able to reproduce this using the simulator?

**Comment by rplatel** [comment]
Figured it out! 

We have nginx in front of genieacs-cwmp doing http-auth.  

It worked as expected with the simulator when connecting directly to GenieACS but didn't work when connecting to nginx in front of GenieACS.

Nginx was breaking the cwmp conversation into single http-request/responses each on a new socket, and this was causing the preset to not work.  

My guess is that when Genie gets the POST on a new socket, it no longer has the <CurrentTime> from the initial inform.

Modifying our nginx.conf as follows resolved the issue (via: https://ma.ttias.be/enable-keepalive-connections-in-nginx-upstream-proxy-configurations/):
```
[...]
   # genieacs-cwmp
+  upstream cwmp_upstream {
+    server 127.0.0.1:17547;
+    keepalive 16;
+  }
   server {
     listen 7547;
     location / {
         proxy_set_header   X-Real-IP $remote_addr;
         proxy_set_header   Host      $http_host;
-        proxy_pass         http://127.0.0.1:17547;
+        proxy_set_header Connection "";
+        proxy_http_version 1.1;
+        proxy_pass         http://cwmp_upstream;
[...]
```

**Comment by zaidka** [comment]
Hmm, that doesn't look right. Continuing the session over a new TCP connection shouldn't cause this behavior. I'll have to look into it.

**Comment by rfdrake** [comment]
I experienced the same issue with nginx.  I appear to be running a newer version than 84e79bd so I think this problem still exists.

The workaround posted by @rplatel works fine though.  It might be best just to document this as a potential thing on the GenieACS-Auth-Config wiki page.

**Comment by rplatel** [comment]
@rfdrake check out issue #281 , with @zaidka's fix above, we had to turn off keep-alives in nginx.

**Comment by rfdrake** [comment]
@rplatel what kind of errors are you seeing in the logs when you hit #281?  I see errors occasionally that I can't track down, things like channel faults for Invalid Parameter Name, but I'm not sure if those are caused by nginx or some other problem I have.

**Comment by rplatel** [comment]
@rfdrake what we saw was in INFORMs that span multiple HTTP requests, the response from GenieACS on the second or other subsequent request was "Invalid Session"
