### ISSUE TITLE
getParameterValues calls utilizing wildcards do not work properly

### ISSUE THREAD

**Issue by spencerlambert** [zaidka/genieacs#220]
I think the issue relates to the function setting `NextLevel` value in the SOAP XML request: https://github.com/zaidka/genieacs/blob/48f861a6a529f11b82ba5c8c969135b0a2f26e81/lib/soap.js#L172

It looks to me, this is the code ultimately responsible for setting `NextLevel`: https://github.com/zaidka/genieacs/blob/ceeb213899b99b29a424570d2bdda4f4271742d0/lib/session.coffee#L796-L833

Here is my use case.  My TR-069 device has a feature to make neighborhood WiFi Scans, reporting back all the WiFi APs it can see.  These APs are listed on a parameter tree named 'InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.'.

To get the results I'm adding the following task on the device, using the NBI.

```json
{
  "name": "getParameterValues",
  "parameterNames": [
  	"InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.*"
  ]
}
```

If my local mongo db doesn't have anything for `InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.`, the SOAP XML call to the devices ends up as:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
  <soap-env:Header>
    <cwmp:ID soap-env:mustUnderstand="1">15b11d95bbc002</cwmp:ID>
  </soap-env:Header>
  <soap-env:Body>
    <cwmp:GetParameterNames>
      <ParameterPath>InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.</ParameterPath>
      <NextLevel>1</NextLevel>
    </cwmp:GetParameterNames>
  </soap-env:Body>
</soap-env:Envelope>
```

Otherwise, if old results are in the mongo db, the SOAP XML gets `NextLevel` set to `0`, which causes the device to respond in a miss-leading way, making the ACS think there are no results.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
  <soap-env:Header>
    <cwmp:ID soap-env:mustUnderstand="1">15b11d9c155002</cwmp:ID>
  </soap-env:Header>
  <soap-env:Body>
    <cwmp:GetParameterNames>
      <ParameterPath>InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.</ParameterPath>
      <NextLevel>0</NextLevel>
    </cwmp:GetParameterNames>
  </soap-env:Body>
</soap-env:Envelope>
```

This leads to my main question, why even refer to the past data in the mongo db when making a wildcard `getParameterValues`?  The parameter tree could change without prior warning.  I would think, a wildcard `getParameterValues` should assume it may not fully understand the parameter tree, so it should only rely on data it gets from the device, in real-time, as it navigates the parameter tree, making follow up device requests as needed.

**Comment by zaidka** [comment]
Looks like it's working as expected. You're trying to fetch only the immediate children, not all descendants. If the device doesn't report any children when nextLevel is true but does when it's false, then that's a device issue for sure.

> This leads to my main question, why even refer to the past data in the mongo db when making a wildcard getParameterValues?

It uses prior knowledge about the data model to determine weather it's more efficient to fetch immediate children or all descendants for a given set of declarations. The behavior you're seeing is a side-effect of that heuristic.

**Comment by spencerlambert** [comment]
But I want all the descendants, that's what I thought the wildcard did.

`InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.*`

**Comment by zaidka** [comment]
The wildcard matches a single path segment. To get all descendants you'll need to specify a path for each level (e.g. Result.*, Result.*.*, Result.*.*.*, etc.).

>  It's making two different SOAP XML requests from the same NBI call, depending on the data already in mongo db for a device.

Assuming the CPE responses are valid, it shouldn't be toggling back and forth for every request after the first one. If that's the case please share debug log, or better yet replicate the problem using the simulator.

**Comment by spencerlambert** [comment]
Yes, it could be an issue with the CPE because the reply back is different depending on whether `NextLevel` is 1 or 0. 

### CPE reply list when NextLevel=1
```
InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.1
InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.2
InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.3
.
.
.
InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.24
```

### CPE reply list when NextLevel=1
```
InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.24
InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.24
InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.24
.
.
.
InternetGatewayDevice.X_READYNET_WIFI.NeighboringWiFiDiagnostic.Result.24
```

**Comment by spencerlambert** [comment]
I'm closing this as it appears to be a CPE issue.  If someone has CPE's doing the same things, a simple but hackish way to fix it is to have `estimateGpnCount()` always return true.

https://github.com/zaidka/genieacs/blob/ceeb213899b99b29a424570d2bdda4f4271742d0/lib/session.coffee#L798
