### ISSUE TITLE
Unable to Install Genieacs

### ISSUE THREAD

**Issue by rajeshmorla** [zaidka/genieacs#224]
Hello Team/ @zaidka 
While executing **npm install -g genieacs**, we are facing issues, please find the below error message and attached log file:

> genieacs@1.1.1 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\genieacs
> npm run configure

> genieacs@1.1.1 configure C:\Users\Administrator\AppData\Roaming\npm\node_modules\genieacs
> cp -n ./config/config-sample.json ./config/config.json

'cp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! genieacs@1.1.1 configure: `cp -n ./config/config-sample.json ./config/config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the genieacs@1.1.1 configure script 'cp -n ./config/config-sample.json ./config/config.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the genieacs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cp -n ./config/config-sample.json ./config/config.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs genieacs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls genieacs
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-04-04T11_40_31_054Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! genieacs@1.1.1 install: `npm run configure`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the genieacs@1.1.1 install script 'npm run configure'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the genieacs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run configure
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs genieacs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls genieacs
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-04-04T11_40_34_831Z-debug.log
PS C:\Users\Administrator>

[2017-04-04T11_41_50_642Z-debug.txt](https://github.com/zaidka/genieacs/files/893008/2017-04-04T11_41_50_642Z-debug.txt)

**Comment by DrumSergio** [comment]
Hi @rajeshmorla !

GenieACS is not meant to be installed in a Windows system. That's why it doesn't recognize "cp" command.
Try with the Linux distro of your choice. You have some tutorials in the Wiki page.

Anyway, this is intended to bug tracking. Better to ask these type of questions in the [mailing list of GenieACS](http://lists.genieacs.com/)

**Comment by rajeshmorla** [comment]
Hi @DrumSergio ,

Thanks for the info !
I will try to install it on Ubuntu...
