### ISSUE TITLE
Invalid Parameter Name

### ISSUE THREAD

**Issue by Ragnar87** [zaidka/genieacs#230]
Genieacs is requesting parameters outside what the CPE provides in a GetParameterNamesResponse, which causes CPE's with a PPP connection to fail and send a Invalid parameter name response.

### GetParameterNames from the server to the CPE
`    <soap-env:Envelope
        xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/"
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
        <soap-env:Header>
            <cwmp:ID
                soap-env:mustUnderstand="1">
                15ba07df6a1100
                </cwmp:ID>
            </soap-env:Header>
        <soap-env:Body>
            <cwmp:GetParameterNames>
                <ParameterPath>
                    InternetGatewayDevice.DeviceInfo.
                    </ParameterPath>
                <NextLevel>
                    1
                    </NextLevel>
                </cwmp:GetParameterNames>
            </soap-env:Body>
        </soap-env:Envelope>`

### GetParameterNamesResponse from CPE
`<soapenv:Header>
            <cwmp:ID
                soapenv:mustUnderstand="1">
                15ba07df6a1100
                </cwmp:ID>
            </soapenv:Header>
        <soapenv:Body>
            <cwmp:GetParameterNamesResponse>
                <ParameterList
                    soap:arrayType="cwmp:ParameterInfoStruct[33]">
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.Manufacturer
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.ManufacturerOUI
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.ModelName
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.Description
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.ProductClass
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.SerialNumber
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.HardwareVersion
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.SoftwareVersion
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.ModemFirmwareVersion
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.AdditionalHardwareVersion
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.SpecVersion
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.ProvisioningCode
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.UpTime
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.FirstUseDate
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.DeviceLog
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_SoftwareVersionPassiveBank
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_MobileAPN
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_OperatorMode
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_RequestedOperatorCode
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_RequestedTechnology
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_PIN
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_PUK
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_DialOnDemand
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_DoDDelay
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_IdleTimeout
                            </Name>
                        <Writable>
                            1
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_Uptime
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_RxBytes
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_TxBytes
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_ModemManufacturer
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_Model
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.X_000E50_SerialExtended
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.VendorConfigFileNumberOfEntries
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    <ParameterInfoStruct>
                        <Name>
                            InternetGatewayDevice.DeviceInfo.VendorConfigFile.
                            </Name>
                        <Writable>
                            0
                            </Writable>
                        </ParameterInfoStruct>
                    </ParameterList>
                </cwmp:GetParameterNamesResponse>
            </soapenv:Body>
        </soapenv:Envelope>`

### GetParameterValues from server to CPE
`<soap-env:Envelope
        xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/"
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:cwmp="urn:dslforum-org:cwmp-1-0">
        <soap-env:Header>
            <cwmp:ID
                soap-env:mustUnderstand="1">
                15ba07df6a1101
                </cwmp:ID>
            </soap-env:Header>
        <soap-env:Body>
            <cwmp:GetParameterValues>
                <ParameterNames
                    soap-enc:arrayType="xsd:string[7]">
                    <string>
                        InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.KeyPassphrase
                        </string>
                    <string>
                        InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID
                        </string>
                    <string>
                        InternetGatewayDevice.DeviceInfo.Manufacturer
                        </string>
                    <string>
                        InternetGatewayDevice.DeviceInfo.ProductClass
                        </string>
                    <string>
                        InternetGatewayDevice.DeviceInfo.SerialNumber
                        </string>
                    <string>
                        InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MACAddress
                        </string>
                    <string>
                        InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress
                        </string>
                    </ParameterNames>
                </cwmp:GetParameterValues>
            </soap-env:Body>
        </soap-env:Envelope>`

_InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1_ doesn't exist on the CPE's with PPP connections and is causing the CPE to send a 9005 InvalidParameterName error

If I refresh the InternetGatewayDevice. object, the refresh works fine, but I was wondering if there was a different solution to this?

**Comment by zaidka** [comment]
That missing was probably there initially but was later deleted and Genie assumed it's still there. To work around this issue you can specify a timestamp value for the "path" attribute in your declare call: declare("a.b.c", {path: Date.now()...})
