### ISSUE TITLE
CWMP TypeError exception on incoming Inform

### ISSUE THREAD

**Issue by LuKePicci** [zaidka/genieacs#233]
Just finished updating from an old (working) version of genieacs.

CWMP daemon is returning this sad error:

`2017-05-14T16:15:54.597Z [ERROR] Uncaught exception; exceptionName="TypeError" exceptionMessage="Cannot read property 'text' of undefined" exceptionStack="TypeError: Cannot read property 'text' of undefined\n    at Object.request (/usr/local/lib/node_modules/genieacs/lib/soap.js:463:94)\n    at f (/usr/local/lib/node_modules/genieacs/lib/cwmp.js:747:20)\n    at getSession (/usr/local/lib/node_modules/genieacs/lib/cwmp.js:647:12)\n    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/genieacs/lib/cwmp.js:741:12)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:188:7)\n    at endReadableNT (_stream_readable.js:975:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)"`
`2017-05-14T16:16:24.582Z [ERROR] Worker died; pid=16547 exitCode=0`

I see also another user in the microtik forum having the same issue, he also posted an envelope, please take a look (https://forum.mikrotik.com/viewtopic.php?t=121463).

**Comment by zaidka** [comment]
The ID element in the SOAP header seems to be missing.

**Comment by LuKePicci** [comment]
Yeah, I can confirm, also my CPE is sending empty
`<SOAP-ENV:Header/>`
so no id attribute exists. Has genieacs changed how it handles this scenario since oldest releases?

**Comment by zaidka** [comment]
Yeah. It used to accept requests with no ID. The ID is a required element as per the specs so I'd suggest reporting this to Microtik. But I'll go ahead and make it accept requests with no ID since it has no significance as far as the server side is concerned.

**Comment by LuKePicci** [comment]
My CPE is not a Microtik one, is basen on Cisco OpenRG and shipped by a major international ISP, kinda impossible to report the issue hoping in some intervention 😅

**Comment by akcoder** [comment]
You would be surprised. I've reported defects to smartrg and had them fixed. 

-dan
