### ISSUE TITLE
How to determine what acs url to be configured in CPE?

### ISSUE THREAD

**Issue by ymagesh** [zaidka/genieacs#235]
Hi,

i have freshly installed genieacs and made all the services up. GUI is also up and running fine. Now i want to communicate to this ACS server from easycwmp client. I am running both GenieACS and Easycwmp on aws.

GenieACS is up and running fine. able to access gui using http://<IP>:3000

In both the EC2 instances we made it to allow all traffic.

1. How to identify the ACS URL from genieACS. So that i can provide in the easycwmp uci configuration.
	config acs
        option url http://54.210.130.183:7547/openacs/acs  ==> Not sure about the path (/openacs/acs) in the URL. Until port is fine.

**How to determine what acs url to be configured in CPE?** i got struck here. Could you pls help?

Thanks,
Magesh

**Comment by zaidka** [comment]
Use the mailing list.

**Comment by sansh1420** [comment]
@zaidka 
Same issue! What do you mean by mailing list?

**Comment by akcoder** [comment]
If only there was some way of searching the Internet. Some sort of site where you put in keywords and then get results to your questions…

-dan

**Comment by sansh1420** [comment]
@akcoder  did try that, no luck!

**Comment by akcoder** [comment]
http://bfy.tw/IXjf

-dan
