### ISSUE TITLE
UPGRADING GENIEACS AND SOME WORRIES

### ISSUE THREAD

**Issue by tundeoyeyemi** [zaidka/genieacs#239]
I'm running a test with the GenieACS for a few devices. I have the installation running for over one year though i have not used it much. 
I will like to start using it more now. I have the following version installed:

[root@tr069 ~]# ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

[root@tr069 ~]# node -v
v0.12.7
[root@tr069 ~]# rails --version
Rails 4.2.5
[root@tr069 ~]# mongo --version
MongoDB shell version: 3.2.0-rc3-75-g5b3257d

[root@tr069 ~]# redis-server --version
Redis server v=3.0.5 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=f5022d1cd7398f95

My questions:
1. What do I need to upgrade and how do I do it without breaking the codes?
2. I do experience the following errors in the CWMP log. What is the cause and how do I fix it?
2017-06-07T14:03:55.749Z - Error: IPC channel is already disconnected
3. How do we get updates for any additional features added to this ACS?

**Comment by zaidka** [comment]
Please use the mailing list. See https://genieacs.com/community/.
