### ISSUE TITLE
How to add Devices

### ISSUE THREAD

**Issue by AGITEL83** [zaidka/genieacs#246]
Hi all,
I got a fresh install and functionning genieacs server (with gui) but I'm desperately searching for a procedure or any way to add a tr069-device to manage.
Could you explain me how to do it ?
My server is a Ubuntu 16.04 one.
Thanks.

**Comment by akcoder** [comment]
The issue tracker is for defects. Please close this and ask your question on the mailing list. 

-dan

**Comment by wikileaks1987** [comment]
You need to update ACS information on your device and Genieacs will automatically fetch the details of the device automatically. Please make sure that your device supports TR069 and also it should not be in bridge mode.

**Comment by sansh1420** [comment]
Same issue! 

I did add ACS Information on my device which supports TR069, but I am still not able to see my device on Genieacs!
