### ISSUE TITLE
Problems with connection request

### ISSUE THREAD

**Issue by akafortyseven** [zaidka/genieacs#249]
I'm trying to use connection request and use this command
```
  curl -i 'http://localhost:7557/devices/D463FE-ABCABDD00042/tasks?connection_request' \
  -X POST \
  --data '{"name":"refreshObject", "objectName":""}'
```
I see in wireshark that server sends GET to the page which it founds in field "Device.ManagementServer.ConnectionRequestURL" in previous Inform message and client answers with "401 Unauthorized" and then nothing happens. 
![1111111111111111111111111111111](https://user-images.githubusercontent.com/25382234/28676122-7f668dca-72f2-11e7-8905-fbcb0885164b.jpg)
I tried different forms of auth.json (default and modified), tried to use "D463FE-ABCABDD00042" as 'someUsername' and empty string ("") as 'somePassword' (because "Device.ManagementServer.ConnectionRequestPassword" is "blank"), I also tried to use data from fields "Device.ManagementServer.ConnectionRequestUsername" and "Device.ManagementServer.Username" as 'someUsername' but every time conversation stops after 401 message from the client. I also tried different socket time-outs (up to 10 seconds) and this didn't help. All other conversations (from client to server) work OK.
How to make connection request work properly?

**Comment by zaidka** [comment]
The 401 response indicates you're using incorrect credentials. I'll go ahead and close this but feel free to reopen if you have reasons to believe this could be a bug. Otherwise, take this to the mailing list for help.
