### ISSUE TITLE
How use use easycwmp with GenieACS

### ISSUE THREAD

**Issue by misterpy** [zaidka/genieacs#253]
Hi there, 

this is more of a question

I'm trying to use easycwmp with GenieACS.

When I run the inform request from easycwmp, I am able to see the device as online in GenieACS. However there is some values that is not recorded by GenieACS.

The example is: Device.IP.Interface.3.Stats.BytesSent

How can I make sure that the device is sending the parameter to GenieACS?

Can you help point me in the right direction on how can I debug the connection between easycwmp and GenieACS?

Your help is greatly appreciated!

**Comment by akcoder** [comment]
The issue tracker is for defects. This is not a defect. Please close this
and take it to the mailing list.

**Comment by misterpy** [comment]
Alright will do so! Thanks.
