### ISSUE TITLE
Just a few 'Device parameters', Heeeeelp

### ISSUE THREAD

**Issue by Lazar1994** [zaidka/genieacs#254]
Hi,

I successfully installed Genieacs and connected the router, the software recognizes the router, but  it displays several parameters in 'Device parameters'. When I create a preset by serial number for SSID and PPPoE username / password, nothing happens.

Thanks. 

Best Regards,
Lazar.

![pic1-wifi-param](https://user-images.githubusercontent.com/31245241/29566610-a9580674-874a-11e7-8146-b8402e828f9f.png)

**Comment by akcoder** [comment]
The issue tracker is for defect tracking, not support. Please close this
issue and take this to the mailing list.

-dan
