### ISSUE TITLE
https://github.com/zaidka/genieacs/wiki/GenieACS-v1.1.x-installation-in-Ubuntu-14.04-Server

### ISSUE THREAD

**Issue by ValerioBaroni** [zaidka/genieacs#255]
Hello,
i just installed GeniaACS following your link https://github.com/zaidka/genieacs/wiki/GenieACS-v1.1.x-installation-in-Ubuntu-14.04-Server, but a can't find "parameters.json" in genieacs/config/, i want change my configuration like this guide  https://github.com/zaidka/genieacs/wiki/Tutorial---Modifying-%27listing-device%27-page-and-adding-Aliasses.

Can you help me? 

Best Regards,

**Comment by akcoder** [comment]
First, github is for defects, not configuration questions. Second, the
tutorial is out of date. I have updated the page with a note that it only
applies to v1.0. To create parameter aliases, please see the virtual
parameters <https://github.com/zaidka/genieacs/wiki/Virtual-Parameters>
page on the wiki.
