### ISSUE TITLE
Listing devices empty

### ISSUE THREAD

**Issue by shajalvola** [zaidka/genieacs#258]
I installed on centos 7, genieacs and genieacs-gui, connected remote cliente tr069 mikrotik.
But don't see "Serial number // Product class // Software version // MAC // IPW //  LAN SSID" 
![listing devices empty](https://user-images.githubusercontent.com/32171973/30704839-34b6c654-9ef4-11e7-83aa-91be6abcb790.png)
only show "Last inform"

**Comment by zoto13** [comment]
just met same issue. this index info is defined in genieacs-gui/config/index_parameters.yml.
if your device follow tr181 data model, you should customize this file cause it is tr98 by default. 
here is mine:
# cat index_parameters.yml 
Serial number: Device.DeviceInfo.SerialNumber
OUI: Device.DeviceInfo.ManufacturerOUI
Software version: Device.DeviceInfo.SoftwareVersion
IP: Device.IP.Interface.2.IPv4Address.1.IPAddress
Tag: _tags

**Comment by kulakoff** [comment]
how to use tr181 data model and tr98.

**Comment by akcoder** [comment]
GitHub is for defect tracking, not installation help. Please take your
questions to the mailing list.

-dan

**Comment by mankomal** [comment]
@zoto13 your solution doesnt works I think this needs to be looked into when I try to do this change only think I am able to get is the Software Version everything else is still blank 

My index_parameters.yml: 
Serial Number: Device.DeviceInfo.SerialNumber
Product Class: Device.DeviceInfo.ProductClass
Software version: Device.DeviceInfo.SoftwareVersion
OUI: Device.DeviceInfo.ManufacturerOUI
IP: Device.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress
WLAN SSID: Device.LANDevice.1.WLANConfiguration.1.SSID
Tag: _tags
