### ISSUE TITLE
Preset with regex precondition not working

### ISSUE THREAD

**Issue by timbalmer** [zaidka/genieacs#259]
Hello,

I ran into an issue when using a precondition for a preset which is a regex.

For example I have this preset / precondition:

```
{
    "_id": "PushConfig",
    "channel": "3",
    "weight": 0,
    "precondition": "{\"Device.DeviceInfo.ProvisioningCode\":\"/^TEST-.*/\"}",
    "configurations": [
      {
        "type": "provision",
        "name": "DownloadISPDefaultConfig"
      }
    ],
    "schedule": "",
    "events": {
      "1 BOOT": true
    }
  }
```
When I check in the GUI this preset is matching the correct devices, so for example TEST-LAB-01 and TEST-LAB-02 match but not ACC-LAB-01. 

However when it comes to actually executing the configuration specified by the preset it is not working. That means, whatever regex I specify in the precondition gives the result that the configurations are never executed. When I remove the precondition or just use an exact match then the same configurations are executed just fine (on the 1 BOOT event in this case).

Even with debug enabled I see nothing at all in the logs, it just seems like regex preconditions in a preset never match although I absolutely sure they do (which is also confirmed by the GUI).

GenieACS version: 1.1.1

Any ideas?

**Comment by zaidka** [comment]
This is unfortunately not a bug but a limitation in v1.1. This version introduced major under the hood changes to lay the groundwork to eventually make GenieACS database engine agnostic.

To emulate a "starts with" query you can use greater than and less than operators. Something like this:

    Device.DeviceInfo.ProvisioningCode >= TEST-
    Device.DeviceInfo.ProvisioningCode < TEST.

Note the dot character is what comes after the dash character in the ASCII table. This may look a little hacky but if a "starts with" operator is to be added to Genie then that's how it would be implemented internally.

**Comment by timbalmer** [comment]
Alright, thanks for the workarround!

**Comment by ealcerreca** [comment]
Hello,
I try to same the same preset but using IP address.
Like  all devices with the IP 10.10.0.*
But I don't get success.
Could you give me any clue?
