### ISSUE TITLE
Error with the maximum number of clients in an ONT

### ISSUE THREAD

**Issue by leonardopc1991** [zaidka/genieacs#260]
I have problems with ONT of the brand gcom, these ONT can be configured the maximum of connected clients, the problem is that when making the change of SSID or change of presharedkey the maximum clients will stay in 1 and only allows a device to connect .

help me please

**Comment by akcoder** [comment]
This is a support question. Please take this to the mailing list and close
this issue.

**Comment by leonardopc1991** [comment]
@akcoder what is the mailing list please

**Comment by akcoder** [comment]
If only there was some way to search the internet for the information you
seek...

**Comment by leonardopc1991** [comment]
-_-
