### ISSUE TITLE
tr069 http error code: 500

### ISSUE THREAD

**Issue by shajalvola** [zaidka/genieacs#266]
i have one router mikrotik client and tr069,but not connect geniacs 
error : last session error "http error code: 500"
![image](https://user-images.githubusercontent.com/32171973/31375734-d0e58bfc-ada2-11e7-88eb-e2436c8b3796.png)

**Comment by zaidka** [comment]
This doesn't belong here. Please review the [contributing guidelines](https://github.com/zaidka/genieacs/blob/master/CONTRIBUTING.md) before opening a Github Issue.
