### ISSUE TITLE
Preset Schedule

### ISSUE THREAD

**Issue by xujianningkp** [zaidka/genieacs#267]
I subscribed mailinglist last week but still haven't got any confirmation...

Just want to know the string format for the preset schedule. What does 3600 0 3 * * 1-5 means? Currently, I've configured the ACS so any CPE phone home, it will performs firmware upgrade. Any way we can schedule a time window for ACS to push firmware out to CPE? I'm on V1.1.1 Any feedback will be appreciated.

![image](https://user-images.githubusercontent.com/6878935/31403270-3ea26294-adbe-11e7-85f9-791095bdc157.png)

**Comment by mths0x5f** [comment]
I wanna know this too.

**Comment by akcoder** [comment]
GitHub is for defect tracking, not configuration questions. Please take this to the mailing list. 

-dan

**Comment by jameswmcnab** [comment]
I had this question as well, It's not described in the documentation or the user interface but I did find this:

> The format is "<duration> <cron expression>". The cron expression
> specifies when the preset is active, and the duration is the time
> window in seconds.

> The preset will be active for any informs received during the specified
> time window

Source: https://www.mail-archive.com/users@lists.genieacs.com/msg01177.html
