### ISSUE TITLE
Uncaught exception when registering many devices

### ISSUE THREAD

**Issue by megachips** [zaidka/genieacs#269]
Oct 19 08:57:28 genieacs-cwmp: 2017-10-18T19:57:28.080Z [ERROR] Uncaught exception; exceptionName="TypeError" exceptionMessage="Cannot read property 'connection' of undefined" exceptionStack="TypeError: Cannot read property 'connection' of undefined\n    at flatten (/usr/lib/node_modules/genieacs/lib/logger.js:138:63)\n    at formatSimple (/usr/lib/node_modules/genieacs/lib/logger.js:209:3)\n    at accessLog (/usr/lib/node_modules/genieacs/lib/logger.js:289:27)\n    at Object.accessInfo (/usr/lib/node_modules/genieacs/lib/logger.js:296:3)\n    at sendAcsRequest (/usr/lib/node_modules/genieacs/lib/cwmp.js:703:10)\n    at /usr/lib/node_modules/genieacs/lib/cwmp.js:418:16\n    at rpcRequest (/usr/lib/node_modules/genieacs/lib/session.js:1004:12)\n    at /usr/lib/node_modules/genieacs/lib/session.js:861:14\n    at clear (/usr/lib/node_modules/genieacs/lib/session.js:1674:12)\n    at rpcRequest (/usr/lib/node_modules/genieacs/lib/session.js:856:12)"

**Comment by akcoder** [comment]
Please include information about your environment. Which version of
GenieACS you are running, Node version, etc...

**Comment by zaidka** [comment]
I ran into the same issue. Don't need more details. Will fix soon.
