### ISSUE TITLE
NoMethodError in Devices#show

### ISSUE THREAD

**Issue by leighataylor** [zaidka/genieacs#276]
Hi,

I have enabled TR-069 on a Polycom VVX310 and pointed it to a newly installed GenieACS server and can see the Polycom online under devices however, when clicking on show under the devices page I get the following error:

> NoMethodError in Devices#show
> Showing /home/ubuntu/genieacs-gui/app/views/devices/_commands.html.erb where line #20 raised:
> 
> undefined method `html_safe' for nil:NilClass
> Did you mean?  html_safe?
> Extracted source (around line #20):
>              
> <% if can?(:create, 'files') %>
> <% software_version = @device['InternetGatewayDevice']['DeviceInfo']['SoftwareVersion']['_value'] rescue @device['Device']['DeviceInfo']['SoftwareVersion']['_value'] rescue '' %>
> <div><%= link_to 'Add Firmware', {controller: 'files', action: 'new', params: {oui: @device['_deviceId']['_OUI'].html_safe, product_class: @device['_deviceId']['_ProductClass'].html_safe, version: software_version.html_safe }} %></div>
> <% end %>
> 
> <% if can?(:delete, 'devices') %>
> 
> Trace of template inclusion: app/views/devices/show.html.erb
> 
> Rails.root: /home/ubuntu/genieacs-gui
> 
> Application Trace | Framework Trace | Full Trace
> app/views/devices/_commands.html.erb:20:in `_app_views_devices__commands_html_erb__1259697473837672279_70284593825560'
> app/views/devices/show.html.erb:42:in `_app_views_devices_show_html_erb__4406547463505039881_70284593136900'
> Request
> 
> Parameters:
> 
> {"id"=>"0004F2-VVX%20310-0004F2DD57A2"}
> Toggle session dump
> Toggle env dump
> Response
> 
> Headers:
> 
> None

Does anyone know why this is?

**Comment by zaidka** [comment]
Please use the mailing list for help. This exception is coming from genieacs-gui so it doesn't make sense to open an issue here anyway.
