### ISSUE TITLE
How to execute API

### ISSUE THREAD

**Issue by frankbl** [zaidka/genieacs#33]
Hello, this is a question from one of my prior thread that is closed already.  But anyhow, regarding your comment: "To do a scheduled reboot, you need to do that using the API. Simply insert a reboot task with a specific start and expiry time. But I have plans at a later stage to add a feature to presets to allow you to do just that."

How do I use API to "insert" a reboot task?  Is there a command line I do or is a web service or?

Thank you for your help!

**Comment by maalaouiolfa** [comment]
I want to add an API that uploads a file from the device to genieacs.Someone has an idea about that?

**Comment by akcoder** [comment]
GitHub is for defect tracking, not support requests. Please take your
question to forum.genieacs.com
