### ISSUE TITLE
Using presets

### ISSUE THREAD

**Issue by 5700** [zaidka/genieacs#36]
Hi,

I am using 'presets' to set values of parameters and can change existing parameters of a CPE if they already exist.  What is the best way to create new objects within a tree (say if I do a factory reset).  I have seen it happen in my tcpflow analysis, but am unable to reproduce it.  It seems it may be automatic under some circumstances.

For example,  I am normally having a type of 'value' for each parameter (this could a the problem), but for the objects themselves have a type of 'object'.  This does not seem to work.  How should I construct my 'preset' for provisioning when objects do not exist?  Do they get created automatically if they don't exist under certain circumstances?

```
{
      "precondition" : "{\"summary.productClass\":\"BLAH\",\"_tags\":{\"$ne\":\"VOICE\"}}",
      "configurations" : [

    #skip a few lines

    {
      "name"  : "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile",
      "value" : "",
      "type"  : "object"
    },
    {
      "name"  : "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1",
      "value" : "",
      "type"  : "object"
    },
    {
      "name"  : "InternetGatewayDevice.Services.VoiceService.1.VoiceProfile.1.Enable",
      "value" : "Enabled",
      "type"  : "value"
    },

    #skip a few lines
```

Thanks in advance, Stuart

**Comment by engee974** [comment]
Hi,
i'm trying to declare the new summary parameters for "InternetGatewayDevice.Services.VoiceService.1.VoiceProfileNumberOfEntries" but it returns blank.
The CPE value is "0".

an issue ?

**Comment by crawc** [comment]
Do you have a packet capture of the transaction?

Chris

**Comment by engee974** [comment]
No need of capture. 
When i open the device in the front end: 
Summary for InternetGatewayDevice.Services.VoiceService.1.VoiceProfileNumberOfEntries = Blank
Device Parameters for InternetGatewayDevice.Services.VoiceService.1.VoiceProfileNumberOfEntries = 0

**Comment by zaidka** [comment]
This is not related to this subject of this issue. Please create a new issue in genieacs-gui, or preferably discuss in the mailing list first if you're not sure it's a bug.

**Comment by fhocorp** [comment]
Hi ! 
With my Livebox 2 i have this error with my ACS for creating a new object with preset :

![image](https://cloud.githubusercontent.com/assets/6709117/13383692/80a60c9c-de8d-11e5-9003-0925ea640d98.png)

Any idea ?

**Comment by fhocorp** [comment]
Hi ! I have this error with my Livebox 2 on my ACS Server :
![image](https://cloud.githubusercontent.com/assets/6709117/13383783/d9ae5960-de8e-11e5-8550-728054e188cb.png)

Any ideas ?
