### ISSUE TITLE
Adding a field to the Database

### ISSUE THREAD

**Issue by gabyayan** [zaidka/genieacs#48]
Hello Zaid,

Is it possible to add a custom field to the mongodb database and then display it in the GUI? What I am trying to do is the following:

I need to match the WiMAX BSID with the site name and add the serving site name to the each device's document in the DB in order to be able to display the site name in the GUI. Thanks.

**Comment by zaidka** [comment]
If it's just for showing in the GUI, then you could customize your GUI to show the site name given the BSID. That's exactly what I'm doing for one deployment.
