### ISSUE TITLE
refresh GenieACS database cache

### ISSUE THREAD

**Issue by frankbl** [zaidka/genieacs#50]
It seems when GenieACS check if the tr-069 "inbound" message is from a "new" device, it checks from some sort of memory cache and not the actual mongo db?  Is there a way to "refresh" the cache, or do I have to reboot the server or re-start the GenieACS software?  I have build my web site (under vb.net) to delete a "device" from device collection (via Mongodb .net driver), but GenieACS still "think" the device is there until I do a reboot of the server.

Thank you!

**Comment by Thegodbia** [comment]
please can someone assist me on how to use the curl API from the API reference page? Thank You in advance.

**Comment by akcoder** [comment]
Please use the mailing list for this.
http://lists.genieacs.com/mailman/listinfo
