### ISSUE TITLE
TP-Link TD-W8980 won't complete CWMP session

### ISSUE THREAD

**Issue by slimey99uk** [zaidka/genieacs#55]
I'm not sure if this is a client issue, or a problem with GenieACS - but I don't have another ACS to test against.

The Inform on boot from the TP-Link never completes, so the client just sits retrying. The full parameter list does not get downloaded. From genieacs-cwmp output:

11 Dec 16:09:04 - 14CC20-IGD-14CC20580689: Inform (1 BOOT,2 PERIODIC,4 VALUE CHANGE); retry count 1485
11 Dec 16:09:10 - 14CC20-IGD-14CC20580689: Inform (1 BOOT,2 PERIODIC,4 VALUE CHANGE); retry count 1486
11 Dec 16:09:15 - 14CC20-IGD-14CC20580689: Inform (1 BOOT,2 PERIODIC,4 VALUE CHANGE); retry count 1487
11 Dec 16:09:20 - 14CC20-IGD-14CC20580689: Inform (1 BOOT,2 PERIODIC,4 VALUE CHANGE); retry count 1488
11 Dec 16:09:25 - 14CC20-IGD-14CC20580689: Inform (1 BOOT,2 PERIODIC,4 VALUE CHANGE); retry count 1489
11 Dec 16:09:30 - 14CC20-IGD-14CC20580689: Inform (1 BOOT,2 PERIODIC,4 VALUE CHANGE); retry count 1490
[etc]

If I turn on debugging, I see GenieACS replies, but the client doesn't seem to continue the conversation:
[Removed because it doesn't like me pasting in XML :) ]

**Comment by slimey99uk** [comment]
Well, I've just had TP-Link Support email me a development build of firmware for the TD-W8980 which they claim fixes CWMP. I'll be testing it tomorrow...

**Comment by zaidka** [comment]
I'm closing this one. Feel free to reopen if you're still facing issues.
