### ISSUE TITLE
Removing GetAllParameters on first inform

### ISSUE THREAD

**Issue by mannyveloso** [zaidka/genieacs#58]
Hi!

I just started poking around GenieACS, and was wondering: how do I remove the GetParameter call that gets queued up when a device first informs? I think that's the refreshObject in the task queue.

If you can point me to the part of the code that does that I can also queue my own tasks, hopefully.

**Comment by zaidka** [comment]
Just noticed this, sorry. When the ACS detects a new device, it fetches all its parameter tree. So yes, that's from the refreshObject task as you guessed.

You can queue your own tasks by using the API. But I'm guessing you already know that by now.
