### ISSUE TITLE
what's the option path of genieacs

### ISSUE THREAD

**Issue by sinkcup** [zaidka/genieacs#62]
Hello, I have install genieacs on linux server IP is 192.168.198.173, I run genieacs-cwmp  genieacs-fs  genieacs-nbi on it. and genieacs-gui run is ok too.

then I install freecwmp on openwrt router ( IP 192.168.198.205), but I don't known genieacs's path, I use this config:

# freecwmp uci configuration

    config local
        option interface 'eth1'
        option port '7547'
        option ubus_socket '/var/run/ubus.sock'
        option date_format '%FT%T%z'
        list event 'bootstrap'
        list event 'boot'

    config acs
        option scheme 'http'
        option username 'freecwmp'
        option password 'freecwmp'
        option hostname '192.168.198.173'
        option port '7547'
        option path '/openacs/acs'

Is this port '7547' and path '/openacs/acs' right?

I run it on openwrt, `/etc/init.d/freecwmpd start`

return error as this:

    config_init_local(59):: freecwmp.@local[0].interface=eth1
    config_init_local(69):: freecwmp.@local[0].port=7547
    config_init_local(93):: freecwmp.@local[0].ubus_socket=/var/run/ubus.sock
    config_init_local(75):: freecwmp.@local[0].date_format=%FT%T%z
    config_init_local(102):: freecwmp.@local[0].event=bootstrap
    config_init_local(102):: freecwmp.@local[0].event=boot
    config_init_acs(180):: freecwmp.@acs[0].scheme=http
    config_init_acs(186):: freecwmp.@acs[0].username=freecwmp
    config_init_acs(192):: freecwmp.@acs[0].password=freecwmp
    config_init_acs(198):: freecwmp.@acs[0].hostname=192.168.198.173
    config_init_acs(208):: freecwmp.@acs[0].port=7547
    config_init_acs(214):: freecwmp.@acs[0].path=/openacs/acs
    config_init_device(324):: freecwmp.@device[0].oui=HiWiFi
    config_init_device(330):: freecwmp.@device[0].product_class=j1-freecwmp
    config_init_device(336):: freecwmp.@device[0].serial_number=D4EE0703A62A
    config_init_device(318):: freecwmp.@device[0].manufacturer=freecwmp
    config_init_device(342):: freecwmp.@device[0].hardware_version=example_hw_version
    config_init_device(348):: freecwmp.@device[0].software_version=example_sw_version

    +++ HTTP SERVER CONFIGURATION +++
    ip: '192.168.198.205'
    port: '7547'
    --- HTTP SERVER CONFIGURATION ---
    +++ HTTP CLIENT CONFIGURATION +++
    http_client_init(62):: url: http://freecwmp:freecwmp@192.168.198.173:7547/openacs/acs
    http_client_init(68):: ssl_verify: SSL certificate validation disabled.
    --- HTTP CLIENT CONFIGURATION ---
    > POST /openacs/acs HTTP/1.1
    Authorization: Basic ZnJlZWN3bXA6ZnJlZWN3bXA=
    Host: 192.168.198.173:7547
    Accept: */*
    User-Agent: freecwmp
    Content-Type: text/xml
    Content-Length: 2709
    Expect: 100-continue

    < HTTP/1.1 100 Continue
    < HTTP/1.1 200 OK
    < Server: GenieACS/1.0.0
    < SOAPServer: GenieACS/1.0.0
    < Content-Type: text/xml; charset="utf-8"
    < Set-Cookie: session=7f93d1b0c1d62bd9
    < Content-Length: 512
    < Date: Mon, 12 Jan 2015 08:47:47 GMT
    < Connection: keep-alive
    < 
    +++ RECEIVED HTTP RESPONSE (PART) +++
    <?xml version="1.0" encoding="UTF-8"?>
    <soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-2"><soap-env:Header><cwmp:ID soap-env:mustUnderstand="1"/></soap-env:Header><soap-env:Body><cwmp:InformResponse><MaxEnvelopes>1</MaxEnvelopes></cwmp:InformResponse></soap-env:Body></soap-env:Envelope>
    --- RECEIVED HTTP RESPONSE (PART) ---
    +++ RECEIVED HTTP RESPONSE +++
    <?xml version="1.0" encoding="UTF-8"?>
    <soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-2"><soap-env:Header><cwmp:ID soap-env:mustUnderstand="1"/></soap-env:Header><soap-env:Body><cwmp:InformResponse><MaxEnvelopes>1</MaxEnvelopes></cwmp:InformResponse></soap-env:Body></soap-env:Envelope>
    --- RECEIVED HTTP RESPONSE ---
    > POST /openacs/acs HTTP/1.1
    Authorization: Basic ZnJlZWN3bXA6ZnJlZWN3bXA=
    Host: 192.168.198.173:7547
    Accept: */*
    Cookie: session=7f93d1b0c1d62bd9
    User-Agent: freecwmp
    Content-Type: text/xml
    Content-Length: 0

    < HTTP/1.1 200 OK
    < Server: GenieACS/1.0.0
    < SOAPServer: GenieACS/1.0.0
    < Content-Type: text/xml; charset="utf-8"
    < Content-Length: 561
    < Date: Mon, 12 Jan 2015 08:47:47 GMT
    < Connection: keep-alive
    < 
    +++ RECEIVED HTTP RESPONSE (PART) +++
    <?xml version="1.0" encoding="UTF-8"?>
    <soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-2"><soap-env:Header><cwmp:ID soap-env:mustUnderstand="1">54b38a333479de2f260d803c</cwmp:ID></soap-env:Header><soap-env:Body><cwmp:GetParameterNames><ParameterPath/><NextLevel>0</NextLevel></cwmp:GetParameterNames></soap-env:Body></soap-env:Envelope>
    --- RECEIVED HTTP RESPONSE (PART) ---
    +++ RECEIVED HTTP RESPONSE +++
    <?xml version="1.0" encoding="UTF-8"?>
    <soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-2"><soap-env:Header><cwmp:ID soap-env:mustUnderstand="1">54b38a333479de2f260d803c</cwmp:ID></soap-env:Header><soap-env:Body><cwmp:GetParameterNames><ParameterPath/><NextLevel>0</NextLevel></cwmp:GetParameterNames></soap-env:Body></soap-env:Envelope>
    --- RECEIVED HTTP RESPONSE ---
    cwmp_handle_messages(158): xml handling message failed
    cwmp_inform(106): handling xml message failed

**Comment by akcoder** [comment]
Path is /

-dan

**Comment by sinkcup** [comment]
OK. thanks.
