### ISSUE TITLE
after push a file "1 Firmware Upgrade Image", the cwmp client auto exit

### ISSUE THREAD

**Issue by sinkcup** [zaidka/genieacs#63]
server : genieacs, genieacs-gui
client : easycwmp openwrt
What's I do:
genieacs-gui -> Files -> New File
genieacs-gui -> Devices -> Show -> Push File
then I see the client request XML, "FileType" "URL" are all right, download success to file `/tmp/easycwmp_download`, then the client auto exit.
I run `/etc/init.d/easycwmpd start`, the client auto exit after `{ "command": "inform", "class": "parameter" }`.
I reboot the router, then run `/etc/init.d/easycwmpd start`, still auto exit.
I find a new file on router `/etc/easycwmp/.backup.xml`, I delete it, easycwmpd can start.

why I see `{"command":"apply", "class":"download", "argument":"1 Firmware Upgrade Image"}` auto run after download, but it don't take effect.
I try to run it manually, apply success! after reboot, I ssh login the router, it has upgrade from 0.9005 to 0.9008 success.
Question : download ok, auto apply it, why it don't take effect.

![1](https://cloud.githubusercontent.com/assets/4971414/5772333/ee0f80ea-9d8b-11e4-9852-d76bfb0a1a2a.png)
![add_file](https://cloud.githubusercontent.com/assets/4971414/5772336/f2fd6cde-9d8b-11e4-9ddc-12cd925a8282.png)
![push_file](https://cloud.githubusercontent.com/assets/4971414/5772337/f637078e-9d8b-11e4-8dce-6049e6e3e2f0.png)
![http_digest_auth_fail_response](https://cloud.githubusercontent.com/assets/4971414/5772446/d52350b4-9d8d-11e4-9a93-3b61cad83214.png)
![debug_download](https://cloud.githubusercontent.com/assets/4971414/5772448/db2d888a-9d8d-11e4-931f-c875c6659d6c.png)
![download_success](https://cloud.githubusercontent.com/assets/4971414/5772450/def50bf0-9d8d-11e4-8145-1d9227bcd8a2.png)
![start](https://cloud.githubusercontent.com/assets/4971414/5772342/06295fa2-9d8c-11e4-845f-c7ccee645eef.png)
![back](https://cloud.githubusercontent.com/assets/4971414/5772480/407ffdf8-9d8e-11e4-83da-fbcbead16558.png)
![rm_ok](https://cloud.githubusercontent.com/assets/4971414/5772376/9b956b26-9d8c-11e4-9b2d-9c563ee7a310.png)
![manually](https://cloud.githubusercontent.com/assets/4971414/5772608/2f556336-9d90-11e4-90b5-b9b25b71f7c6.png)

**Comment by zaidka** [comment]
Please report client issues to the client's issue tracker. This is only for GenieACS issues.
