### ISSUE TITLE
http_digest_auth_fail_response: header: Digest realm="realm@easycwmp"

### ISSUE THREAD

**Issue by sinkcup** [zaidka/genieacs#64]
server : genieacs, genieacs-gui
client : easycwmp openwrt
openwrt router is online. when I change ssid on genieacs-gui, it notice 

    Tasks added to queue and will be committed when device is online

and at the same time, the easycwmpd on the router notice

    +++ RECEIVED HTTP REQUEST +++
    http_digest_auth_fail_response(322):: http_digest_auth_fail_response: header: Digest realm="realm@easycwmp",qop="auth",nonce="1dcfd6db7522b17e240cc0c0a3210e3600001422",opaque="328458fab28345ae87ab3210a8513b14eff452a2"--- RECEIVED HTTP REQUEST ---
    +++ HTTP SERVER CONNECTION FAILED +++

wait, after 1 minute, the easycwmp client pull from acs, it take effect success.

someone has the same problem at 2014-09-25, see http://support.easycwmp.org/view.php?id=12

![2015-01-16 16 16 38](https://cloud.githubusercontent.com/assets/4971414/5773356/93fdc61e-9d9c-11e4-89c9-13b68a37c303.png)
![2015-01-16 16 18 34](https://cloud.githubusercontent.com/assets/4971414/5773366/bb774d32-9d9c-11e4-8763-8200099df99b.png)

**Comment by zaidka** [comment]
Your connection request authentication credentials are invalid. Enter the correct credentials in config/auth.js.

**Comment by sinkcup** [comment]
I change config/auth.js, then run genieacs, still this error.
![2015-01-18 11 28 59](https://cloud.githubusercontent.com/assets/4971414/5791281/cbafc21e-9f05-11e4-8fea-b01436ad46ae.png)

**Comment by HarryZrui** [comment]
can you cat your /etc/config/easycwmp ?
