### ISSUE TITLE
How add composite object in one task?

### ISSUE THREAD

**Issue by ttt443412644** [zaidka/genieacs#65]
Hello. 
I want to add object InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1 within inner object InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection in one task. 

Apart a can add objects:
curl -i 'http://localhost:7557/devices/00304F-IGD-22AABBCC2DAC/tasks?connection_request' -X POST --data '{"name":"addObject", "objectName":"InternetGatewayDevice.WANDevice.1.WANConnectionDevice", 
"parameterValues":[
["WANPPPConnectionNumberOfEntries", "1", "xsd:unsignedInt"],
["WANDSLLinkConfig.Enable", "true", "xsd:boolean"],
["WANDSLLinkConfig.LinkType", "EoA", "xsd:string"],
["WANDSLLinkConfig.DestinationAddress", "PVC:0/35", "xsd:string"],
["WANDSLLinkConfig.ATMEncapsulation", "LLC", "xsd:string"],
["WANDSLLinkConfig.ATMQoS", "UBR", "xsd:string"]
]}'

Then get number of WANConnectionDevice and create second object:
curl -i 'http://localhost:7557/devices/00304F-IGD-22AABBCC2DAC/tasks?connection_request' -X POST --data '{"name":"addObject", "objectName":"InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection", 
"parameterValues":[
["Enable", "true", "xsd:boolean"],
["Name", "pppoe1", "xsd:string"],
["Username", "user", "xsd:string"],
["Password", "pass", "xsd:string"],
["NATEnabled", "true", "xsd:boolean"]
]}'

But this method very long...

Help me.
Thank you.

**Comment by zaidka** [comment]
I'm afraid it's not possible to do that in a single task.
