### ISSUE TITLE
How do i can list CPE WPA Pass?

### ISSUE THREAD

**Issue by evilr4bbit** [zaidka/genieacs#66]
i try do inform my devices , but acs server can't show WPA password!whY?

**Comment by evilr4bbit** [comment]
i guess my device is WPA2 so GenieACS just cwmp 1.0,so cant show pass

**Comment by akcoder** [comment]
Per the spec, for both KeyPassphrase and PreSharedKey "When read, this
parameter returns an empty string, regardless of the actual value."

One device I have (A Thomson TG585) can be configured to return the
passphrase, but that is not the norm.

-dan

**Comment by akcoder** [comment]
BTW, there is a mailing list that is better suited for these types of
questions.

http://lists.genieacs.com/mailman/listinfo

-dan

**Comment by evilr4bbit** [comment]
when i check cwmp data model 2.0 "Device:WiFi." it can return WPA-Personal or another , so i guess is data model problem,btw thanks reply
