### ISSUE TITLE
API: fetching tasks by "id" does not work

### ISSUE THREAD

**Issue by LovingFox** [zaidka/genieacs#68]
Hello!

I cannot fetch tasks by "id" via API:

    # query={"_id":"54de06342acb0b10130750e1"}
    curl -s 'http://localhost:7557/tasks/?query=%7B%22_id%22%3A%2254de06342acb0b10130750e1%22%7D' | python -m json.tool
    []

But I can do it by "device" and by other vars (for example "objectName"):

    # ?query={"device":"00259E-HG8245H-48575443E204802C"}
    curl -s 'http://localhost:7557/tasks/?query=%7B%22device%22%3A%2200259E-HG8245H-48575443E204802C%22%7D' | python -m json.tool
    [
        {
            "_id": "54de06342acb0b10130750e1",
            "device": "00259E-HG8245H-48575443E204802C",
            "fault": {
                "detail": {
                    "Fault": {
                        "FaultCode": "9002",
                        "FaultString": "Internal error"
                    }
                },
                "faultcode": "Client",
                "faultstring": "CWMP fault"
            },
            "name": "addObject",
            "objectName": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection",
            "retries": 1,
            "timestamp": "2015-02-13T14:17:04.977Z"
        },
        {
            "_id": "54de06955108dcd60f219f72",
            "device": "00259E-HG8245H-48575443E204802C",
            "fault": {
                "detail": {
                    "Fault": {
                        "FaultCode": "9002",
                        "FaultString": "Internal error"
                    }
                },
                "faultcode": "Client",
                "faultstring": "CWMP fault"
            },
            "name": "addObject",
            "objectName": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection",
            "retries": 1,
            "timestamp": "2015-02-13T14:18:42.129Z"
        }
    ]

    # query={"objectName":"InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection"}
    curl -s 'http://localhost:7557/tasks/?query=%7B%22objectName%22%3A%22InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection%22%7D' | python -m json.tool
    [
        {
            "_id": "54de06342acb0b10130750e1",
            "device": "00259E-HG8245H-48575443E204802C",
            "fault": {
                "detail": {
                    "Fault": {
                        "FaultCode": "9002",
                        "FaultString": "Internal error"
                    }
                },
                "faultcode": "Client",
                "faultstring": "CWMP fault"
            },
            "name": "addObject",
            "objectName": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection",
            "retries": 1,
            "timestamp": "2015-02-13T14:17:04.977Z"
        },
        {
            "_id": "54de06955108dcd60f219f72",
            "device": "00259E-HG8245H-48575443E204802C",
            "fault": {
                "detail": {
                    "Fault": {
                        "FaultCode": "9002",
                        "FaultString": "Internal error"
                    }
                },
                "faultcode": "Client",
                "faultstring": "CWMP fault"
            },
            "name": "addObject",
            "objectName": "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection",
            "retries": 1,
            "timestamp": "2015-02-13T14:18:42.129Z"
        }
    ]

**Comment by zaidka** [comment]
I can confirm the issue. Will patch soon. Thanks!
