### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Winnetou** [zaidka/genieacs#70]
I am struggling to install genieacs on ubuntu, I keep on getting erro messages like the one:

>npm http 200 https://registry.npmjs.org/kerberos/-/kerberos-0.0.9.tgz
>npm http GET https://registry.npmjs.org/bindings/1.1.1
>npm http GET https://registry.npmjs.org/nan/1.1.2
>npm http 200 https://registry.npmjs.org/bindings/1.1.1
>npm http GET https://registry.npmjs.org/bindings/-/bindings-1.1.1.tgz
>npm http 200 https://registry.npmjs.org/nan/1.1.2
>npm http GET https://registry.npmjs.org/nan/-/nan-1.1.2.tgz
>gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
>gyp ERR! configure error 
>gyp ERR! stack Error: `gyp` failed with exit code: 1
>gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
>gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
>gyp ERR! System Linux 3.13.0-44-generic
>gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
>gyp ERR! npm http 200 https://registry.npmjs.org/bindings/-/bindings-1.1.1.tgz
>cwd /usr/local/lib/node_modules/genieacs/node_modules/hiredis
>gyp ERR! node -v v0.10.25
>gyp ERR! node-gyp -v v0.10.10
>gyp ERR! not ok 
>npm WARN This failure might be due to the use of legacy binary "node"
>npm WARN For further explanations, please read
>/usr/share/doc/nodejs/README.Debian
> 
>npm ERR! weird error 1
>npm http 200 https://registry.npmjs.org/nan/-/nan-1.1.2.tgz
>npm ERR! Error: ENOENT, lstat '/home/ubuntu/tmp/npm-31937-em4z96OT/1424183999585->0.9878946484532207/package/build/Release/obj.target/bson/ext/bson.o'
>npm ERR! If you need help, you may report this log at:
>npm ERR!     <http://github.com/isaacs/npm/issues>
>npm ERR! or email it to:
>npm ERR!     <npm-@googlegroups.com>
>
>npm ERR! System Linux 3.13.0-44-generic
>npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "genieacs"
>npm ERR! cwd /home/ubuntu
>npm ERR! node -v v0.10.25
>npm ERR! npm -v 1.3.10
>npm ERR! path /home/ubuntu/tmp/npm-31937-em4z96OT/1424183999585->0.9878946484532207/package/build/Release/obj.target/bson/ext/bson.o
>npm ERR! fstream_path /home/ubuntu/tmp/npm-31937-em4z96OT/1424183999585->0.9878946484532207/package/build/Release/obj.target/bson/ext/bson.o
>npm ERR! fstream_type File
>npm ERR! fstream_class FileWriter
>npm ERR! code ENOENT
>npm ERR! errno 34
>npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
>npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
>npm ERR! 
>npm ERR! Additional logging details can be found in:
>npm ERR!     /home/ubuntu/npm-debug.log
>npm ERR! not ok code 0

**Comment by zaidka** [comment]
Not sure what might be causing this. Try updating your npm.

**Comment by zaidka** [comment]
Hope you managed to get it to install. If not, feel free to reopen the issue.

**Comment by zfiser** [comment]
found solution here http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu
