### ISSUE TITLE
NULL request of objects

### ISSUE THREAD

**Issue by jpereira** [zaidka/genieacs#75]
Hi,
I have tested the genie with my vdsl router Techinicolor TD5336. but don't completes the inform because the Genie request a null object. e.g: InternetGatewayDevice.LANDevice.1.WLANConfiguration.(null).Enable

you can check the complete payload in http://54.94.225.88/debug/CC03FA-DSL%2520CPE-4D534442400035.dump

The problem is because the CPE responds correctly with index of 7 itens. but the Genie request a refresh of (null).

**Comment by zaidka** [comment]
The null index seems to come from the CPE. I saw this in GetParameterNamesResponse:

    <ParameterInfoStruct>
        <Name>InternetGatewayDevice.LANDevice.1.WLANConfiguration.(null).</Name>
        <Writable>0</Writable>
    </ParameterInfoStruct>
