### ISSUE TITLE
Error: PCDATA invalid Char value 2

### ISSUE THREAD

**Issue by JimJian** [zaidka/genieacs#76]
Hi
I got a problem when I use my CPE to connect the genieacs
the error message is:

19 Mar 16:05:54 - 123456789012345678901234-STB-1452002: Inform
 (6 CONNECTION REQUEST); 
retry count 1
19 Mar 16:05:54 - 123456789012345678901234-STB-1452002: Started task 
refreshObject(550a82e60d21f2ab79fb21a2)
util.error: Use console.error instead
2015-03-19T08:05:55.182Z - Error: PCDATA invalid Char value 2

    at Error (native)
    at Object.module.exports.fromXml 
(/usr/local/lib/node_modules/genieacs/n
ode_modules/libxmljs/lib/document.js:120:21)
    at Object.exports.request (/usr/local/lib/node_modules/genieacs/lib/soap.js:373:20)
    at /usr/local/lib/node_modules/genieacs/lib/cwmp.js:638:26
    at /usr/local/lib/node_modules/genieacs/lib/cwmp.js:575:12
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at try_callback (/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply 
(/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> 
(/usr/local/lib/node_modules/genieacs/node_modules/redis/index.js:321:14)

have somebody can tell me how to solve it?
thanks!

**Comment by zaidka** [comment]
Copying my comment from the mailing list:

Looks like your CPE is sending invalid XML. Use tcpdump or Wireshark to
find the offending part if you'd like to report it to the vendor.
Meanwhile, try setting the configuration option "XML_PARSE_RECOVER" to
true in your config.json. This tells the XML parser to try to recover
from parsing errors when possible.

**Comment by ttt443412644** [comment]
I solved same problem. 
soap.js -> request function

httpRequest.getBody() return invalid content (as binary) in section InternetGatewayDevice.DeviceConfig.ConfigFile,
then libxmljs.parseXml have error. 

I cut that value from source data
