### ISSUE TITLE
Fault information for multiple parameters not properly stored in the DB

### ISSUE THREAD

**Issue by sindhujak** [zaidka/genieacs#78]
I tried Set Parameter request from REST API for 3 parameter with fault values. But the faulty task stored in the DB has information only about the last parameter and the rest two parameters information are not stored in the DB

**Comment by zaidka** [comment]
Could you please share the fault XML response from the CPE?

**Comment by sindhujak** [comment]
<SOAP-ENV:Fault>
<faultcode>Client</faultcode>
<faultstring xsi:type="xsd:string">CWMP FAULT</faultstring>

<detail><cwmp:Fault>
<FaultCode xsi:type="xsd:unsignedInt">9003</FaultCode>
<FaultString xsi:type="xsd:string">Invalid Arguments</FaultString>
<SetParameterValuesFault>
<ParameterName xsi:type="xsd:string">Device.X_M0000C.AGNSS.MesgSubmissionRetryCount</ParameterName>
<FaultCode xsi:type="xsd:unsignedInt">9007</FaultCode>
<FaultString xsi:type="xsd:string">Value out of range</FaultString>
</SetParameterValuesFault>
<SetParameterValuesFault>
<ParameterName xsi:type="xsd:string">Device.X_M0000C.PTPMasterg82651.LeaseLimit</ParameterName>
<FaultCode xsi:type="xsd:unsignedInt">9007</FaultCode>
<FaultString xsi:type="xsd:string">Value out of range</FaultString>
</SetParameterValuesFault>
<SetParameterValuesFault>
<ParameterName xsi:type="xsd:string">Device.X_M0000C.AGNSS.ServerHttpVersion</ParameterName>
<FaultCode xsi:type="xsd:unsignedInt">9007</FaultCode>
<FaultString xsi:type="xsd:string">String too long</FaultString>
</SetParameterValuesFault>
</cwmp:Fault></detail>
</SOAP-ENV:Fault>

**Comment by sindhujak** [comment]
This is the DB collection for that faulty task.

{ "_id" : ObjectId("55116986fd3aef9f0afef223"), "name" : "setParameterValues", "parameterValues" : [ [ "Device.X_M0000C.AGNSS.MesgSubmissionRetryCount", "2000", "xsd:unsignedInt" ], [ "Device.X_M0000C.PTPMasterg82651.LeaseLimit", "1001", "xsd:unsignedInt" ], [ "Device.X_M0000C.AGNSS.ServerHttpVersion", " MGAssistNow_libMGA104", "xsd:string" ] ], "device" : "M0000C-CPE-000000000000", "timestamp" : ISODate("2015-03-24T13:46:27.957Z"), "fault" : { "faultcode" : "Client", "faultstring" : "CWMP FAULT", "detail" : { "Fault" : { "FaultCode" : "9003", "FaultString" : "Invalid Arguments", "SetParameterValuesFault" : { "ParameterName" : "Device.X_M0000C.AGNSS.ServerHttpVersion", "FaultCode" : "9007", "FaultString" : "String too long" } } } }, "retries" : 1 }

**Comment by zaidka** [comment]
This unfortunately cannot be fixed without breaking compatibility. I may be making some changes to tasks for the next release so I'll make sure to have this sorted out. Until then, you could check parameter faults one by one.
