### ISSUE TITLE
Session Expiry when empty HTTP is sent

### ISSUE THREAD

**Issue by sarabjit1983** [zaidka/genieacs#79]
Hi,

I am trying to test TR069 CPE using genieACS,
I can see the inform request-response successful but when the CPE is sending empty HTTP Request for terminating session, the ACS is sending back an error reporting "session has expired".

Any help would be great on this. Am I missing out on something?

![a](https://cloud.githubusercontent.com/assets/11965240/7164243/a049770e-e3bc-11e4-8fa1-f10fea078954.png)

Thanks.

**Comment by hollyshao** [comment]
Hi, 
Is there your http request has cookie info? 
I encounter this problem，and i found that my inform http request with no cookie info, I suspect this is the cause.

**Comment by zaidka** [comment]
I think I have answered sarabjit1983 elsewhere and forgot about this ticket. The usual solution to common cookie issues is to add the following configuration:

    "COOKIES_PATH" : "/"

**Comment by sarabjit1983** [comment]
Hello Zaid,

Yes you are absolutely right, u answered me on LinkedIn for this :)
But now we are facing some other issue,
we tried to send across GetParameterValues/SetParameterValues from GenieACS
but while looking at wireshark captures no message seems to be getting sent
from GenieACS and other thing we noticed was that the device was getting
offline after sometime.

Any help on this would be extremely helpful.

Thanks
Sarab

**Comment by zaidka** [comment]
This could be due to incorrect connection request credentials. Either disable connection request authentication in the device or ensure the credentials in config/auth.js match the device settings. If that doesn't work, let's take this to the mailing list.

**Comment by Saidurga21** [comment]
Even connection Request credentials are correct not able to push the file to the device and observing the error 500 saying that task name not recognized...
