### ISSUE TITLE
CPE doesn´t finish the cwmp session against GenieACS server

### ISSUE THREAD

**Issue by jgomezberrio** [zaidka/genieacs#82]
Hi , 
I´m evaluating GenieACS as our new ACS platform for a big project we need to handle using TR-69 protocol, but i´m finding an issue with new CPE routers we are deploying. 
It seems that there is a kind of missunderstanding of the cookies handling at CPE device. 
This same CPE i tested against other open source platforms, such as OpenACS and they work fine, but i decided to use GenieACS cause the user interface is more user friendly for my NOC operators. 

I paste here the CPE log information: 

Host:10.0.1.63
User-Agent:TR069_AGENT/1.0
Content-Length:2963
Connection:keep-alive
Content-Type:text/xml; charset=utf-8
SOAPAction:

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cwmp="urn:dslforum-org:cwmp-1-0"><SOAP-ENV:Header><cwmp:ID SOAP-ENV:mustUnderstand="1">inform</cwmp:ID></SOAP-ENV:Header><SOAP-ENV:Body SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><cwmp:Inform><DeviceId><Manufacturer>AMIT</Manufacturer><OUI>005018</OUI><ProductClass>AX-1122</ProductClass><SerialNumber>00501867EB89</SerialNumber></DeviceId><Event xsi:type="SOAP-ENC:Array" SOAP-ENC:arrayType="cwmp:EventStruct[3]"><EventStruct><EventCode>1 BOOT</EventCode><CommandKey></CommandKey></EventStruct><EventStruct><EventCode>X 005018 StunError</EventCode><CommandKey></CommandKey></EventStruct><EventStruct><EventCode>2 PERIODIC</EventCode><CommandKey></CommandKey></EventStruct></Event><MaxEnvelopes>1</MaxEnvelopes><CurrentTime>2015-04-26T08:23:32</CurrentTime><RetryCount>0</RetryCount><ParameterList xsi:type="SOAP-ENC:Array" SOAP-ENC:arrayType="cwmp:ParameterValueStruct[10]"><ParameterValueStruct><Name>InternetGatewayDevice.DeviceInfo.SpecVersion</Name><Value xsi:type="xsd:string">1.0</Value></ParameterValueStruct><ParameterValueStruct><Name>InternetGatewayDevice.DeviceInfo.HardwareVersion</Name><Value xsi:type="xsd:string">1.23</Value></ParameterValueStruct><ParameterValueStruct><Name>InternetGatewayDevice.DeviceInfo.SoftwareVersion</Name><Value xsi:type="xsd:string">00TF0.6006_03251530</Value></ParameterValueStruct><ParameterValueStruct><Name>InternetGatewayDevice.DeviceInfo.Description</Name><Value xsi:type="xsd:string">3G Router</Value></ParameterValueStruct><ParameterValueStruct><Name>InternetGatewayDevice.DeviceInfo.Customerid</Name><Value xsi:type="xsd:string">00501867EB89</Value></ParameterValueStruct><ParameterValueStruct><Name>InternetGatewayDevice.DeviceInfo.ProvisioningCode</Name><Value xsi:type="xsd:string">amit.gpr2</Value></ParameterValueStruct><ParameterValueStruct><Name>InternetGatewayDevice.ManagementServer.ConnectionRequestURL</Name><Value xsi:type="xsd:string">http://183.171.209.194:8099/0</Value></ParameterValueStruct><ParameterValueStruct><Name>InternetGatewayDevice.ManagementServer.ParameterKey</Name><Value xsi:type="xsd:string"></Value></ParameterValueStruct><ParameterValueStruct><Name>InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANPPPConnection.1.ExternalIPAddress</Name><Value xsi:type="xsd:string">183.171.209.194</Value></ParameterValueStruct><ParameterValueStruct><Name>InternetGatewayDevice.DeviceSummary</Name><Value xsi:type="xsd:string">InternetGatewayDevice:1.0[](Baseline:1,EthernetLAN:1,WiFiLAN:1,EthernetWAN:1     ,Time:1,IPPing:1     ,Baseline:2,EthernetLAN:2     ,Time:2,TraceRoute:1)</Value></ParameterValueStruct></ParameterList></cwmp:Inform></SOAP-ENV:Body></SOAP-ENV:Envelope>

Sun Apr 26 08:23:32 2015,comm.c[336](func_send): release qbuf to empty_qbuf_head ok.
Sun Apr 26 08:23:32 2015,comm.c[279](func_send): wait SEM_SEND.
Sun Apr 26 08:23:32 2015,handler.c[715](handle_recv_data): WAITTING SEM_RECV ........
Sun Apr 26 08:23:33 2015,comm.c[435](func_recv): colin bbb TO func_recv countqn=0
Sun Apr 26 08:23:33 2015,comm.c[436](func_recv): insert qbuf to recv_qbuf_head ok.
Sun Apr 26 08:23:33 2015,comm.c[493](func_recv): post SEM_RECV.
Sun Apr 26 08:23:33 2015,comm.c[402](func_recv): colin aaa TO func_recv countqn=1
Sun Apr 26 08:23:33 2015,comm.c[410](func_recv): get qbuf from empty_qbuf_head ok.
Sun Apr 26 08:23:33 2015,comm.c[418](func_recv): colin ready to sock_recv.
Sun Apr 26 08:23:33 2015,handler.c[717](handle_recv_data): GET SEM_RECV Successful
Sun Apr 26 08:23:33 2015,handler.c[769](handle_recv_data): Recv Data : HTTP/1.1 200 OK
Server: GenieACS/1.0.0
SOAPServer: GenieACS/1.0.0
Content-Type: text/xml; charset="utf-8"
Set-Cookie: session=ae59db0eb2def60c
Content-Length: 527
Date: Sun, 26 Apr 2015 08:23:32 GMT
Connection: keep-alive

<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cwmp="urn:dslforum-org:cwmp-1-0"><soap-env:Header><cwmp:ID soap-env:mustUnderstand="1">inform</cwmp:ID></soap-env:Header><soap-env:Body><cwmp:InformResponse><MaxEnvelopes>1</MaxEnvelopes></cwmp:InformResponse></soap-env:Body></soap-env:Envelope>

Sun Apr 26 08:23:33 2015,handler.c[780](handle_recv_data): Start Parse http header
Sun Apr 26 08:23:33 2015,httparser.c[534](parse_cookie): !!!!!malloc cookie_tmp, size:54, loc:0x5fee90
Sun Apr 26 08:23:33 2015,httparser.c[552](parse_cookie): Receive cookie data is :
session=ae59db0eb2def60c
Sun Apr 26 08:23:33 2015,httparser.c[561](parse_cookie): !!!!!free cookie_tmp:0x5fee90
Sun Apr 26 08:23:33 2015,httparser.c[228](parse_http_header): colin case 200 parse_http_header FORMAT_ERROR 2
Sun Apr 26 08:23:33 2015,handler.c[478](handle_termination): Start exec task
Sun Apr 26 08:23:33 2015,param_attri.c[693](read_attr_conf): malloc attr_array_tmp :0
Sun Apr 26 08:23:33 2015,cpe_task_list.c[290](exec_task): The cpe_task_list is NULL
Sun Apr 26 08:23:33 2015,handler.c[480](handle_termination): Exec task successful 
Sun Apr 26 08:23:33 2015,global_res.c[76](post_signal): send signal to thread success
Sun Apr 26 08:23:34 2015,global_res.c[76](post_signal): send signal to thread success
Sun Apr 26 08:23:34 2015,comm.c[699](sock_recv): recv timeout
Sun Apr 26 08:23:34 2015,comm.c[429](func_recv): colin test 2 no receive
Sun Apr 26 08:23:34 2015,comm.c[435](func_recv): colin bbb TO func_recv countqn=1
Sun Apr 26 08:23:34 2015,comm.c[436](func_recv): insert qbuf to recv_qbuf_head ok.
Sun Apr 26 08:23:34 2015,comm.c[493](func_recv): post SEM_RECV.
Sun Apr 26 08:23:35 2015,handler.c[560](handle_termination): Post signal SIG_ABORT to p_send p_recv
Sun Apr 26 08:23:35 2015,handler.c[568](handle_termination): Handler thread will closed
Sun Apr 26 08:23:35 2015,comm.c[286](func_send): entering SEM_SEND....
Sun Apr 26 08:23:35 2015,comm.c[293](func_send): get send qbuf from send_qbuf_head failure.
Sun Apr 26 08:23:35 2015,comm.c[1559](destroy_comm_modules_res): =======colin empty_qbuf = 7 send_qbuf=0 recv_qbuf=1 ======
Sun Apr 26 08:23:35 2015,comm.c[358](func_send): comm stop.= end func_send()
# 

Comparing the logs with OpenACS it seems that the GenieACS platform doesn´t send the Path=/ in the cookies data session. 

I attach you the GenieACS logs : http://pastebin.com/KeEPRUPu

**Comment by zaidka** [comment]
Try adding the following option to config.json:

    "COOKIES_PATH" : "/"

**Comment by akcoder** [comment]
I added this to the trouble shooting page
<https://github.com/zaidka/genieacs/wiki/Troubleshooting-GenieACS>

**Comment by jgomezberrio** [comment]
Thanks for the info. After configuring the config.json with that parameter, now the http header can be processed by the CPE successfully.
Now i have other issue cause worker dies after the HTTP-POST from CPE.
I´ve been checking in the issues database and applied different solutions but still can not get it working. Do you think we can get it working with a workaround?

27 Apr 20:35:38 - 005018-AX%2D1122-00501867E867: Inform (1 BOOT); retry count 0
27 Apr 20:35:38 - 005018-AX%2D1122-00501867E867: Started task refreshObject(553efe8ea194bf6a0f5c6c29)
2015-04-28T03:35:38.929Z - TypeError: Object function (name, content) {
    var elem = Element(this.doc(), name, content);
    this.addChild(elem);
    return elem;
} has no method 'text'
    at Object.exports.response (/genieacs/lib/soap.js:527:17)
    at /genieacs/lib/cwmp.js:346:24
    at b (domain.js:183:18)
    at try_callback (/genieacs/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/genieacs/node_modules/redis/index.js:685:13)
    at HiredisReplyParser.<anonymous> (/genieacs/node_modules/redis/index.js:321:14)
    at HiredisReplyParser.emit (events.js:95:17)
    at HiredisReplyParser.execute (/genieacs/node_modules/redis/lib/parser/hiredis.js:43:18)
    at RedisClient.on_data (/genieacs/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/genieacs/node_modules/redis/index.js:102:14)

27 Apr 20:35:38 - Worker 4372 died (0)
27 Apr 20:35:39 - Worker 4433 listening to 0.0.0.0:7547
27 Apr 20:35:41 - 005018-AX%2D1122-00501867E867: Inform (X 005018 StunError); retry count 0
27 Apr 20:35:41 - 005018-AX%2D1122-00501867E867: Started task refreshObject(553efe8ea194bf6a0f5c6c29)
2015-04-28T03:35:41.406Z - TypeError: Object function (name, content) {
    var elem = Element(this.doc(), name, content);
    this.addChild(elem);
    return elem;
} has no method 'text'
    at Object.exports.response (/genieacs/lib/soap.js:527:17)
    at /genieacs/lib/cwmp.js:346:24
    at b (domain.js:183:18)
    at try_callback (/genieacs/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/genieacs/node_modules/redis/index.js:685:13)
    at HiredisReplyParser.<anonymous> (/genieacs/node_modules/redis/index.js:321:14)
    at HiredisReplyParser.emit (events.js:95:17)
    at HiredisReplyParser.execute (/genieacs/node_modules/redis/lib/parser/hiredis.js:43:18)
    at RedisClient.on_data (/genieacs/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/genieacs/node_modules/redis/index.js:102:14)

27 Apr 20:35:41 - Worker 4375 died (0)
27 Apr 20:35:41 - Worker 4445 listening to 0.0.0.0:7547

**Comment by zaidka** [comment]
That's weird! Have you made any changes to soap.coffee or soap.js files?

**Comment by jgomezberrio** [comment]
Hi Zaid, 
first of all sorry for the delay in my answer, i did some modifications to soap.coffee but i reestablished as it was after installation. Then, now this problem disappeared. 
Now I have other issues, because the server is showing the device, but it says: invalid parameter name, i´m collecting the information to send it to you.

**Comment by zaidka** [comment]
No problem. Unless you're confident it's a bug, please use the mailing list (http://lists.genieacs.com/mailman/listinfo/users) for more visibility. I'd like to keep github for discussing bug reports and feature requests only.
