### ISSUE TITLE
backup devices collections

### ISSUE THREAD

**Issue by LuCe86** [zaidka/genieacs#83]
Hi
I want to create a backup devices collection (e.g. named t_devices).
I want to save all the TR-069 of each cpe in this new collection, so if I have the require a factory reset for example, I can recover the custom configurations automatically.

I know there is the command db.devices.copyTO (newcollection) , but I can't use it because the copy would be excessive.

thanks

**Comment by zaidka** [comment]
This is old I completely forgot about it, sorry. My suggest is to only back up the important parameter and push them using the API when necessary.
