### ISSUE TITLE
NoMethodError in Devices#show

### ISSUE THREAD

**Issue by FabienBazille** [zaidka/genieacs#84]
Hello zaidka,
First sorry for my bad english, and thanks you for the great project you made.
I'm using genieacs during a training, and it was working well since yesterday, I feel like the refresh is not working very well because when it refreh the values doesn't change (the current rate), and second problem I would like to attach a Yealink SIPphone and it attach well, but i think the telephone can't handle correctly the RPc methods.

Here is my error:

NoMethodError in Devices#show

Showing /home/serveurcom/genieacs-gui/app/views/devices/show.html.erb where line #155 raised:

undefined method `[]' for nil:NilClass

Extracted source (around line #155):   
	

    </div>
    <% end %>
    <% if can?(:create, 'files') %>
    <div><%= link_to 'Add Firmware', {controller: 'files', action: 'new', params: {oui: @device['summary.oui'].html_safe, product_class: @device['summary.productClass'].html_safe, version: @device['summary.softwareVersion']['_value'].html_safe }}  %></div>
    <% end %>
    
    <% if can?(:delete, 'devices') %>

Rails.root: /home/serveurcom/genieacs-gui
Application Trace | Framework Trace | Full Trace

app/views/devices/show.html.erb:155:in `_app_views_devices_show_html_erb___505456723577925096_70140418041240'
app/controllers/devices_controller.rb:107:in `block in show'
app/controllers/application_controller.rb:40:in `can?'
app/controllers/devices_controller.rb:101:in `show'

Request

Parameters:

{"id"=>"001565-SIP%2DT48G-0015655c6484"}

If you have any ideas, i take it.

Edit: During a packet capture only the ping work well, when i try to refresh some values, i should have some HTTP request but only TCP connection appears between the ACS and the CPE (a modem)

**Comment by akcoder** [comment]
The refresh might be timing out. Try increasing
the GET_PARAMETER_NAMES_DEPTH_THRESHOLD  value to 2, and then 3 if it still
times out. https://github.com/zaidka/genieacs/wiki/GenieACS-General-Config
Make sure you restart the cwmp process after making changes.

-dan

**Comment by FabienBazille** [comment]
Thanks for the answer, i made the change it seems not working better.
And do you have any ideas for the SIP Phone he can't use the method to get the software, i think.
Take a look at my devices page:
![capture equipements](https://cloud.githubusercontent.com/assets/12166059/7412894/3bd68c9e-ef47-11e4-8ff9-5163fdc3d9e7.PNG)
And when i clik on show for the SIP phone it appears the page on my first post.

By the way again another problem (yes you will hate me ^^), i have some issues with my cisco router 800 series who made only inform then no more inform, I have to restart genieacs or cwmp agent on the router.

Sorry for the long post and all my problems.

**Comment by akcoder** [comment]
Sorry I have no experience with SIP.

**Comment by FabienBazille** [comment]
I found the problem was in the show.html.erb, because of the firmware, if i delete that sample of code i can access the show page again:

<div><%= link_to 'Add Firmware', {controller: 'files', action: 'new', params: {oui: @device['summary.oui'].html_safe, product_class: @device['summary.productClass'].html_safe, version: @device['summary.softwareVersion']['_value'].html_safe }}  %></div>
<% end %>

I'm trying a workaround who display the button "add firmware" for all the devices except this device but i d'ont really now how to do i'm really new to Ruby:

<% if can?(:create, 'files') && @device['_id']!= "001565-SIP%252DT48G-0015655c6484"%>
<div><%= link_to 'Add Firmware', {controller: 'files', action: 'new', params: {oui: @device['summary.oui'].html_safe, product_class: @device['summary.productClass'].html_safe, version: @device['summary.softwareVersion']['_value'].html_safe }}  %></div>
<% end %>

It's a bit rough, maybe i can just exclude all the SIP device who seems not working well, something like that in the expression : @device['_id']!= "*SIP*"

Thanks for your time 

Regards

Fabien B

**Comment by akcoder** [comment]
@device['_id']!= "SIP" will not work. The _id parameter is the internal id generated by genie acs. If you know it's your SIP devices giving you trouble, you can wrap that in an if statement and check on the oui.

The bigger question though is why do the sip devices not have oui, product class an/or software version? Those are mandatory parameters according to the spec.


-dan

**Comment by akcoder** [comment]
You can also wrap that bit of code in some guard code - check that the parameters are not nil. That would be the correct way of handling this. 

-dan

**Comment by awnz** [comment]
Hi, I've hit the same thing - again with a Yealink phone (SIP-T41P). It's reporting its hardware version only under "Device.DeviceInfo.HardwareVersion" instead of "summary.HardwareVersion". Manufacturer bug?

**Comment by akcoder** [comment]
Change the parameters.json file like so:

From:
  "InternetGatewayDevice.DeviceInfo.HardwareVersion" : {"alias" :
"summary.hardwareVersion"},
To:
  "Device.DeviceInfo.HardwareVersion" : {"alias" :
"summary.hardwareVersion"},

**Comment by awnz** [comment]
Thanks, but won't that break other devices? In my test install, I do have devices that report InternetGatewayDevice.DeviceInfo.HardwareVersion. Is there a way to have both?

**Comment by akcoder** [comment]
You can use the regex. Look at some of the other regex in there to get an idea. If you still need help, let me know. And I'll give you a ride back when I get to work tomorrow.

-dan

**Comment by awnz** [comment]
Ok this is what I changed in parameters.json:

As normal up to this line:

    "_deviceId._Manufacturer" : {"alias" : "summary.manufacturer"},

then:

    "/^.*/.DeviceInfo.HardwareVersion" : {"alias" : "summary.hardwareVersion"},
    "Device.LAN.MACAddress" : {"alias" : "summary.mac"},
    "Device.LAN.IPAddress" : {"alias" : "summary.ip"},
    "Device.DeviceInfo.SoftwareVersion" : {"alias" : "summary.softwareVersion"},

then back to normal from this line:

    "InternetGatewayDevice.DeviceInfo.SoftwareVersion" : {"alias" : "summary.softwareVersion"},

Looks like if you define multiple sources for the same alias, it will take the latest one that matches, is that right?

In my case the two types of devices connecting to my GenieACS are a NetComm NF4V internet gateway which has the HardwareVersion, SoftwareVersion etc data under "InternetGatewayDecvice.", and Yealink phones with that info under "Device.". The above works for me. No claims as to whether or not it will break things for others!

@akcoder not sure what you mean by giving me a ride back, are you thinking of someone else?
Besides, over here, tomorrow's Saturday - and the start of a long weekend. I'll be avoiding work.

**Comment by akcoder** [comment]
Lol. I used Siri and it obviously added words 😄.

-dan

**Comment by awnz** [comment]
Wow, that chanced an amazingly coherent sentence there - impressive.

**Comment by Hezliman** [comment]
To clear it up, as a vendor you can choose either to implement "Device.yadder.yadder" (see TR-181) or "InternetGatewayDevice.yadder.yadder" (see TR-098) for the (root)data-model, depending on the kind of HW you're implementing TR-069 functionality for.

For more information on that http://www.broadband-forum.org/cwmp.php

**Comment by akcoder** [comment]
This should work as well:

"/^[InternetGatewayDevice|Device]$/.DeviceInfo.HardwareVersion" :
{"alias" : "summary.hardwareVersion"},

**Comment by awnz** [comment]
Yes that's much more elegant. For making it easier to work with non-gateway devices, (SIP phones being one use case), could that work as a nicer default in parameters.json?

**Comment by zaidka** [comment]
Coincidentally, that's exactly what I did a few hours ago.

**Comment by awnz** [comment]
Awesome, thanks :)

Bug now fixed then?

**Comment by FabienBazille** [comment]
It works with the latest version of GenieACS ! 
I think I can close that issue now.

Thanks you.

**Comment by jaluapen** [comment]
Try to get IMSI info the index web, any help there,, sorry newbie
InternetGatewayDevice.WEB_GUI.Status.LTE_Status.LTE_System.IMSI

**Comment by GLENDIS** [comment]
I have two types of dispotivos (different), one of them brings in the parameter InternetGatewayDevice.DeviceInfo.SerialNumber
the serial number and the other one brings the MAC.
I was reviewing and the device that brings the MAC in InternetGatewayDevice.DeviceInfo.SerialNumber,
it also has another parameter (InternetGatewayDevice.DeviceInfo.X_HW_SerialNumber) that if it brings the serial number, the one that I need.

My query is, how can you make the files index_parameters.yml and summary_parameters.yml display the Serial number for
all types of devices.

Also, I do not find parameters.json in the path the genieacs / config / parameters.json and in any other route.

Serial number: InternetGatewayDevice.DeviceInfo.SerialNumber
Serial number: InternetGatewayDevice.DeviceInfo.X_HW_SerialNumber

![img1](https://user-images.githubusercontent.com/47321714/52347127-f9736780-29ff-11e9-9b6a-7789e07489ee.png)
![img2](https://user-images.githubusercontent.com/47321714/52347133-fd06ee80-29ff-11e9-96f0-62f8908d2204.png)

**Comment by akcoder** [comment]
Please close this issue. GitHub is for defect tracking, not support
requests.

-dan
