### ISSUE TITLE
Problem with non-unique serial number

### ISSUE THREAD

**Issue by ttt443412644** [zaidka/genieacs#87]
I try to use your product on our subscribers. But some CPE transmit the wrong serial number as the 00304F-IGD-999999999999999999 or 00304F-IGD-001122334455. Your product identifies them as a single device CPE. I can't work with them.
Is there any way to work with such CPE, having the same serial numbers?

**Comment by akcoder** [comment]
I had a similar issue with our cpes, except the oui would switch between 000000 and ffffff on every boot. The solution was to make the vendor fix the bug. 

-dan
