### ISSUE TITLE
Power server

### ISSUE THREAD

**Issue by ttt443412644** [zaidka/genieacs#88]
What should be the power of the server for comfortable work with, for example, 10000 CPEs, 50000 CPEs

**Comment by zaidka** [comment]
Sorry, missed this one. This can very depending on your setup. There's a test client in "test" directory that you can use to simulate a number of devices. You could simulate a 1000 devices and based on that estimate the specs you'll need to handle 10k or 50k devices.

Zaid

PS: It's best to use the mailing lists for general questions. Github issues is for bug reports or feature requests.
