### ISSUE TITLE
http_digest_auth_fail_response with easycwmp

### ISSUE THREAD

**Issue by eckertfo** [zaidka/genieacs#91]
Hello,

i have the same problem with easycwmp an geniesacs combination and https enbaled like #64

If i add on the cpe side the password and username and set the same password and username in /config/auth.js on genieacs i get the message

+++ RECEIVED HTTP REQUEST +++
http_digest_auth_fail_response(322):: http_digest_auth_fail_response: header: Digest realm="realm@easycwmp",qop="auth",nonce="d45048332fdf2ba2df6532f51030b7bb000032ae",opaque="328458fab28345ae87ab3210a8513b14eff452a2"--- RECEIVED HTTP REQUEST ---
+++ HTTP SERVER CONNECTION FAILED +++

if i deleted the password and username on the cpe everything works fine

Kind Regards

Flo

**Comment by akcoder** [comment]
Did you restart the cwmp process after making changes to the config.js file?

-dan

**Comment by eckertfo** [comment]
Hello,

I have only edited the config/auth.js wirh my password and username as seen
in the example and yes i restarted the genieas-cwmp. I also restarted the
EasyCwmp an i have seen in the logs that the right password and username
was set.

Kind regards

Flo
Am 27.05.2015 16:34 schrieb "Dan Morphis" <notifications@github.com>:

**Comment by eckertfo** [comment]
Hallo,

Can any one give me a hint where the problem is? Is it on the cpe (easycwmp) or acs (genieacs) problem? Does it work with other software on the cpe side? Does any ont tested with this (my) configuration?

Kind regards

Flo

PS: I also use https does this influence the authentication? From ACS to CPE

**Comment by zaidka** [comment]
Flo, try updating your genieacs installation to the latest release (1.0.4) as there's a workaround to authentication issue in some devices. If that doesn't help, please provide TCP dump from tcpdump or Wireshark.

**Comment by eckertfo** [comment]
I update to this Version but it does not resolve my issue! Tomorrow i will
do a tcpdump and have a look what goes wrong.

Thanks Flo
Am 17.06.2015 11:16 schrieb "Zaid Abdulla" <notifications@github.com>:

**Comment by eckertfo** [comment]
Hello,

sorry i am a little late i worked on an other project.

1. I made a connection request with the browser with password set on the cpe side and the auth was an success (tcpdump host 10.1.3.62 and port 7547 -w success.pcap)

2. If I do this with genieacs webgui this fails (tcpdump host 10.1.3.62 and port 7547 -w failed.pcap)

I looked into the sources of genieacs and i think it looks fine til "HTTP/1.1 401 Unauthorized"  after that nothing is send to the cpe.
I send you the tcpdump pcap files over e-mail

Flo

**Comment by l-y-n-x** [comment]
Hi,
I'm investigating the same problem. Looks like the HTTP GET request to the CPE runs into an error: [Error: socket hang up] code: 'ECONNRESET'.
The tcp session has been closed by the CPE via FIN, no RST around...

**Comment by zaidka** [comment]
I may have found the cause of the problem. The client is sending a response without Content-Length header or a terminating CRLF sequence (in case of chunked encoding) which Node.js interprets, correctly so, as invalid HTTP response. Working around this involves implementing HTTP GET on top of Node.js sockets which isn't trivial. I suspect it worked using a web browser because browsers always seem to be more lenient towards this kind of quirks. I suggest you contact EasyCWMP guys to investigate.

**Comment by eckertfo** [comment]
Hello Zaid,

thank you very much for your investigation! I will ask the easycwmp guys as you suggest.

Kind regards

Flo

**Comment by eckertfo** [comment]
Hallo Zaid,

we have test it. As you have said in an email we have added an additional "CRLF" in to easycwmp. I will report it to the easycwmp guys to add an additional "CRLF" at the end of the header. Thank you very much for your help.

By for now

Flo
