### ISSUE TITLE
Wrong IP bind 

### ISSUE THREAD

**Issue by FabienBazille** [zaidka/genieacs#93]
Hi,

I'm performing an issue when i wanna push a configuration file on a device, the FS bind the old IP, and not mine, I don't know why because my genieacs's config seems ok.
Take a look at it:

![config json](https://cloud.githubusercontent.com/assets/12166059/7860385/d46597b8-0548-11e5-93f1-4444a64e7192.png)
![config-coffee1](https://cloud.githubusercontent.com/assets/12166059/7860388/d46c9bb2-0548-11e5-873d-fee334a77638.png)
![config-coffee2](https://cloud.githubusercontent.com/assets/12166059/7860387/d46c6a52-0548-11e5-8838-4189f9a89243.png)
![wrong ip bind](https://cloud.githubusercontent.com/assets/12166059/7860386/d46a210c-0548-11e5-9979-98acda481323.png)

The capture tell to the CPE a wrong IP and then the device reject it.
When I perform a change in the config file I do a "npm run compile"
If you have any idea of what is happening.

PS: I use the script genieacs-start.sh at my home directory and the folder genieacs and genieacs-gui are both on the home directory too. And I changed the Preset_cache_duration hoping that was that but it seems not

Best regards,

Fabien B

**Comment by akcoder** [comment]
You only need to change the config.js file. Did you restart the genie
processes after changing the config?

-dan

**Comment by FabienBazille** [comment]
Here is my genieacs/lib/config.js file:
var allConfig, arg, argv, common, get, k, options, path, setConfig, v, _ref, _ref1;

path = require('path');

common = require('./common');

options = {
  CONFIG_DIR: {
    type: 'string',
    "default": 'config'
  },
  MONGODB_CONNECTION_URL: {
    type: 'string',
    "default": 'mongodb://127.0.0.1/genieacs'
  },
  REDIS_PORT: {
    type: 'int',
    "default": 6379
  },
  REDIS_HOST: {
    type: 'string',
    "default": '127.0.0.1'
  },
  REDIS_DB: {
    type: 'int',
    "default": 0
  },
  CWMP_WORKER_PROCESSES: {
    type: 'int',
    "default": 4
  },
  CWMP_PORT: {
    type: 'int',
    "default": 7547
  },
  CWMP_INTERFACE: {
    type: 'string',
    "default": '192.168.2.175'
  },
  CWMP_SSL: {
    type: 'bool',
    "default": false
  },
  NBI_WORKER_PROCESSES: {
    type: 'int',
    "default": 2
  },
  NBI_PORT: {
    type: 'int',
    "default": 7557
  },
  NBI_INTERFACE: {
    type: 'string',
    "default": '192.168.2.175'
  },
  NBI_SSL: {
    type: 'bool',
    "default": false
  },
  FS_WORKER_PROCESSES: {
    type: 'int',
    "default": 2
  },
  FS_PORT: {
    type: 'int',
    "default": 7567
  },
  FS_INTERFACE: {
    type: 'string',
    "default": '192.168.2.175'
  },
  FS_SSL: {
    type: 'bool',
    "default": false
  },
  FS_IP: {
    type: 'string',
    "default": '192.168.2.175'
  },

And yes I restart genieacs with ./genieacs-stop.sh and ./genieacs-start.sh
