### ISSUE TITLE
What is MongoDB for?

### ISSUE THREAD

**Issue by SvenJ31** [zaidka/genieacs#94]
What service/proces (CWMP, NBI, FS, Redis, Rails) uses MongoDB and why does it use MongoDB

**Comment by akcoder** [comment]
MongoDB is used to store the configuration/state of the CPE, presets, etc.

**Comment by SvenJ31** [comment]
So what service uses MongoDB. As mentioned in the question: "What service/proces (CWMP, NBI, FS, Redis, Rails) uses MongoDB and why does it use MongoDB".

**Comment by akcoder** [comment]
Cwmp, nbi, fs. Mongo is the storage engine. 

-dan

**Comment by SvenJ31** [comment]
And what is Redis for. On internet i found that this also some sort of Database

**Comment by akcoder** [comment]
Redis is the caching layer.

-dan

**Comment by SvenJ31** [comment]
Could you please explain to me how the processes communicate with each other with a short description on how they work and what they do? Thanks!

**Comment by akcoder** [comment]
No :)

-dan
