### ISSUE TITLE
Delete Devices

### ISSUE THREAD

**Issue by SvenJ31** [zaidka/genieacs#96]
Is there a way to delete a device that is not used anymore?

**Comment by zaidka** [comment]
Yes, you can find it in the device page in genieacs-gui. Please use the mailing list for general questions. Github issues are for bug reports only.

**Comment by SvenJ31** [comment]
I cant find a Device page in Genieacs-gui, could u please explain me how?

 

Van: Zaid Abdulla [mailto:notifications@github.com] 
Verzonden: donderdag 4 juni 2015 16:09
Aan: zaidka/genieacs
CC: SvenJ31
Onderwerp: Re: [genieacs] Delete Devices (#96)

 

Yes, you can find it in the device page in genieacs-gui. Please use the mailing list for general questions. Github issues are for bug reports only.

**Comment by akcoder** [comment]
Take this to the mailing list and I'll be happy to answer your question.

-dan
